//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_507 = RegionPhoneMetadata(
    code: 507,
    timezone: "America/Panama",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_3/4", national: "XXX-XXXX", international: "XXX-XXXX")
		.init(id: "fmt2_4/4", national: "XXXX-XXXX", international: "XXXX-XXXX")
		.init(id: "tollfree_3/3/4", national: "XXX XXX XXXX", international: "XXX XXX XXXX")
	],
    operators: [
		.init(id: "cable_wireless", name: "Cable & Wireless")
		.init(id: "claro", name: "Claro")
		.init(id: "digicel", name: "Digicel")
		.init(id: "mobilphone", name: "Mobilphone")
		.init(id: "telefonica_moviles", name: "Telefónica Móviles")
	],
    ranges: [
		.init(prefix: "00800", length: ["11"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "10", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "111", length: ["7"], areaCodeLength: nil, operator: "claro", format: "fmt1_3/4")
		.init(prefix: "11[479]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "123", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "1[23]7", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "13[013]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "14[17]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "15[05]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "16[058]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "161", length: ["7"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt1_3/4")
		.init(prefix: "17[017]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "176", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "18[2358]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "19[1389]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "2[0235-79]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "21[0-7]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "21[89]", length: ["7"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt1_3/4")
		.init(prefix: "24[013-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "28[02-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "3[089]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "31[0-7]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "32[0-4]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "325", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "333", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "34[0-79]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "35[0-35]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "36[068]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "37[0-8]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "400", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "43[0-579]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "44", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "47[0-57-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "5[01]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "52[0-7]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "5[56]0", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "579", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "60", length: ["8"], areaCodeLength: nil, operator: "digicel", format: "fmt2_4/4")
		.init(prefix: "61[0-5]", length: ["8"], areaCodeLength: nil, operator: "digicel", format: "fmt2_4/4")
		.init(prefix: "616", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "61[78]", length: ["8"], areaCodeLength: nil, operator: "claro", format: "fmt2_4/4")
		.init(prefix: "619", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "62", length: ["8"], areaCodeLength: nil, operator: "claro", format: "fmt2_4/4")
		.init(prefix: "63[0-2]", length: ["8"], areaCodeLength: nil, operator: "claro", format: "fmt2_4/4")
		.init(prefix: "63[347]", length: ["8"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt2_4/4")
		.init(prefix: "63[5689]", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "64", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "65[0-5]", length: ["8"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt2_4/4")
		.init(prefix: "65[6-9]", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "66[0-4]", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "66[5-9]", length: ["8"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt2_4/4")
		.init(prefix: "67", length: ["8"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt2_4/4")
		.init(prefix: "68[0478]", length: ["8"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt2_4/4")
		.init(prefix: "68[1-3569]", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "69[014-689]", length: ["8"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt2_4/4")
		.init(prefix: "69[237]", length: ["8"], areaCodeLength: nil, operator: "telefonica_moviles", format: "fmt2_4/4")
		.init(prefix: "70[09]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "72[0-26-8]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "73[03]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "7[49]0", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "744", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "75[06-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "755", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "76[0156]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "77[0-24-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "78[5-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "800", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "800", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt2_4/4")
		.init(prefix: "800", length: ["10"], areaCodeLength: nil, operator: nil, format: "tollfree_3/3/4")
		.init(prefix: "809", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "81[01]", length: ["7"], areaCodeLength: nil, operator: "mobilphone", format: "fmt1_3/4")
		.init(prefix: "822", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "82[89]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "83", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "84[0-24-689]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "85[014]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "855", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "860", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "87[23]", length: ["7"], areaCodeLength: nil, operator: "cable_wireless", format: "fmt1_3/4")
		.init(prefix: "87[78]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "88[02]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "886", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "900", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "90[5-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "91[03578]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "91[16]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "92[036-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "93[3579]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "936", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "940", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "95[0457-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "96[05-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "97[04-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "981", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "98[35-8]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
		.init(prefix: "99", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_3/4")
	]
)

