//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_90 = RegionPhoneMetadata(
    code: 90,
    timezone: "Europe/Istanbul",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_3/3/2/2", national: "(#XXX) XXX XX XX", international: "XXX XXX XX XX")
		.init(id: "fixed_3/3/4", national: "#XXX XXX XXXX", international: "XXX XXX XXXX")
		.init(id: "mobile_3/3/2/2", national: "#XXX XXX XX XX", international: "XXX XXX XX XX")
		.init(id: "tollfree_3/3/6-7", national: "#XXX XXX XXXXXX*", international: "XXX XXX XXXXXX*")
		.init(id: "uan_3/1/3", national: "XXX X XXX", international: )
	],
    operators: [
		.init(id: "Foniv_telecommunications_services", name: "Foniv Telecommunications Services")
		.init(id: "alfa_telekom", name: "Alfa iletisim")
		.init(id: "assistant_telecom", name: "Assistant Telecom")
		.init(id: "duru_telekom", name: "Duru Telekom")
		.init(id: "hatnet", name: "HATNET BILGI ILETISIM TEKNOLOJILERI")
		.init(id: "isnet", name: "Isnet")
		.init(id: "kktc_telsim", name: "KKTC Telsim")
		.init(id: "kuzey_kibris_turkcell", name: "Kuzey Kibris Turkcell")
		.init(id: "medium_telecommunications_services", name: "Medium Telecommunications Services")
		.init(id: "mobilisim", name: "Mobilisim Mobil Bilisim")
		.init(id: "netgsm", name: "Netgsm")
		.init(id: "nida", name: "Nida Telekomunikasyon")
		.init(id: "pasifik_telekom", name: "Pasifik Telekom")
		.init(id: "pelicell", name: "Pelicell Telecommunications")
		.init(id: "roitel", name: "Roitel")
		.init(id: "selam", name: "Selam Mobile")
		.init(id: "ttm", name: "TTM")
		.init(id: "turk_telekom", name: "Turk Telekom")
		.init(id: "turkcell", name: "Turkcell")
		.init(id: "vodafone", name: "Vodafone")
	],
    ranges: [
		.init(prefix: "212", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "216", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "222", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "224", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "226", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "228", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "232", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "236", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "242", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "246", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "248", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "252", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "256", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "258", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "262", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "264", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "266", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "272", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "274", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "276", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "282", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "284", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "286", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "288", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "312", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "318", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "322", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "324", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "326", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "328", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "332", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "338", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "342", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "344", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "346", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "348", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "352", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "354", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "356", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "358", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "362", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "364", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "366", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "368", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "370", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "372", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "374", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "376", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "378", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "380", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "382", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "384", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "386", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "388", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "392", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "412", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "414", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "416", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "422", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "424", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "426", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "428", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "432", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "434", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "436", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "438", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "442", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "444", length: ["7"], areaCodeLength: nil, operator: nil, format: "uan_3/1/3")
		.init(prefix: "446", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "452", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "454", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "456", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "458", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "462", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "464", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "466", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "472", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "474", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "476", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "478", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "482", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "484", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "486", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "488", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/2/2")
		.init(prefix: "50[15-7]", length: ["10"], areaCodeLength: nil, operator: "turk_telekom", format: "mobile_3/3/2/2")
		.init(prefix: "510[015-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "5102[07-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510210", length: ["10"], areaCodeLength: nil, operator: "pasifik_telekom", format: "mobile_3/3/2/2")
		.init(prefix: "51021[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "51022[0-37]", length: ["10"], areaCodeLength: nil, operator: "netgsm", format: "mobile_3/3/2/2")
		.init(prefix: "51022[4-689]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "51023[013-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510232", length: ["10"], areaCodeLength: nil, operator: "Foniv_telecommunications_services", format: "mobile_3/3/2/2")
		.init(prefix: "51024[0-35-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510244", length: ["10"], areaCodeLength: nil, operator: "nida", format: "mobile_3/3/2/2")
		.init(prefix: "51025[0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510255", length: ["10"], areaCodeLength: nil, operator: "ttm", format: "mobile_3/3/2/2")
		.init(prefix: "51026[0-57-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510266", length: ["10"], areaCodeLength: nil, operator: "medium_telecommunications_services", format: "mobile_3/3/2/2")
		.init(prefix: "510300", length: ["10"], areaCodeLength: nil, operator: "mobilisim", format: "mobile_3/3/2/2")
		.init(prefix: "5103[01][1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510310", length: ["10"], areaCodeLength: nil, operator: "assistant_telecom", format: "mobile_3/3/2/2")
		.init(prefix: "5103[25-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "5103[34][0-24-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510333", length: ["10"], areaCodeLength: nil, operator: "roitel", format: "mobile_3/3/2/2")
		.init(prefix: "510343", length: ["10"], areaCodeLength: nil, operator: "isnet", format: "mobile_3/3/2/2")
		.init(prefix: "510400", length: ["10"], areaCodeLength: nil, operator: "duru_telekom", format: "mobile_3/3/2/2")
		.init(prefix: "5104[058][1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "5104[1-467]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510450", length: ["10"], areaCodeLength: nil, operator: "pelicell", format: "mobile_3/3/2/2")
		.init(prefix: "510480", length: ["10"], areaCodeLength: nil, operator: "alfa_telekom", format: "mobile_3/3/2/2")
		.init(prefix: "51049[0-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "510499", length: ["10"], areaCodeLength: nil, operator: "hatnet", format: "mobile_3/3/2/2")
		.init(prefix: "512", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/4")
		.init(prefix: "516[02-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "5161[0-57-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "51616", length: ["10"], areaCodeLength: nil, operator: "turkcell", format: "mobile_3/3/2/2")
		.init(prefix: "524", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "53[0-24-9]", length: ["10"], areaCodeLength: nil, operator: "turkcell", format: "mobile_3/3/2/2")
		.init(prefix: "533[0-79]", length: ["10"], areaCodeLength: nil, operator: "turkcell", format: "mobile_3/3/2/2")
		.init(prefix: "5338[0-289]", length: ["10"], areaCodeLength: nil, operator: "turkcell", format: "mobile_3/3/2/2")
		.init(prefix: "5338[3-7]", length: ["10"], areaCodeLength: nil, operator: "kuzey_kibris_turkcell", format: "mobile_3/3/2/2")
		.init(prefix: "54[013-9]", length: ["10"], areaCodeLength: nil, operator: "vodafone", format: "mobile_3/3/2/2")
		.init(prefix: "542[0-79]", length: ["10"], areaCodeLength: nil, operator: "vodafone", format: "mobile_3/3/2/2")
		.init(prefix: "5428[0-49]", length: ["10"], areaCodeLength: nil, operator: "vodafone", format: "mobile_3/3/2/2")
		.init(prefix: "5428[5-8]", length: ["10"], areaCodeLength: nil, operator: "kktc_telsim", format: "mobile_3/3/2/2")
		.init(prefix: "55[1-59]", length: ["10"], areaCodeLength: nil, operator: "turk_telekom", format: "mobile_3/3/2/2")
		.init(prefix: "561011", length: ["10"], areaCodeLength: nil, operator: "selam", format: "mobile_3/3/2/2")
		.init(prefix: "56161", length: ["10"], areaCodeLength: nil, operator: "turkcell", format: "mobile_3/3/2/2")
		.init(prefix: "59221[12]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "592461", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "59[46]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/2/2")
		.init(prefix: "800", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/4")
		.init(prefix: "800", length: ["12", "13"], areaCodeLength: nil, operator: nil, format: "tollfree_3/3/6-7")
		.init(prefix: "811", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/4")
		.init(prefix: "850", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/4")
		.init(prefix: "8[89]8", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/4")
		.init(prefix: "900", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/4")
	]
)

