//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_218 = RegionPhoneMetadata(
    code: 218,
    timezone: "Europe/Bucharest",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_2/7", national: "#XX-XXXXXXX", international: "XX-XXXXXXX")
	],
    operators: [
		.init(id: "almadar", name: "Al-Madar")
		.init(id: "libyana", name: "Libyana")
		.init(id: "ltt", name: "Libya Telecom & Technology")
	],
    ranges: [
		.init(prefix: "205", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "206", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "21", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "22[0-35-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "224", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "23", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "24", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "25[013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "252", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "26", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "271", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "272", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "274", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "275", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "277", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "279", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "281", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "282", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "284", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "31", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "322", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "323", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "325", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "326", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "41", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "421", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "422", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "423", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "425", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "427", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "452", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "453", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "454", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "47", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "481", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "482", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "484", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "51", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "521", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "522", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "523", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "524", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "526", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "529", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "53", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "54", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "551", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "553", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "554", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "555", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "57", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "581", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "582", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "583", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "584", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "61", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "62[0-2]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "623", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "624", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "625", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "626", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "627", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "628", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "629", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "63", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "6[49]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "652", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "653", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "654", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "655", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "657", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "67", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "681", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "682", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "683", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "684", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "685", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "71", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "721", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "723", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "724", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "725", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "726", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "727", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "729", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "73[05-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "731", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "732", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "733", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "734", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "81", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "82[02-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "821", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "84", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "851", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "852", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "854", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "884", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt1_2/7")
		.init(prefix: "9[13]", length: ["9"], areaCodeLength: nil, operator: "almadar", format: "fmt1_2/7")
		.init(prefix: "9[24]", length: ["9"], areaCodeLength: nil, operator: "libyana", format: "fmt1_2/7")
		.init(prefix: "9[56]", length: ["9"], areaCodeLength: nil, operator: "ltt", format: "fmt1_2/7")
	]
)

