//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_30 = RegionPhoneMetadata(
    code: 30,
    timezone: "Europe/Athens",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "all_3/3/4", national: "XXX XXX XXXX", international: "XXX XXX XXXX")
		.init(id: "athens_and_personal_2/4/4", national: "XX XXXX XXXX", international: "XX XXXX XXXX")
		.init(id: "fixed_4/6", national: "XXXX XXXXXX", international: "XXXX XXXXXX")
		.init(id: "toll_free_3/3-4/5", national: "XXX XXX* XXXXX", international: "XXX XXX* XXXXX")
	],
    operators: [
		.init(id: "amd_telecom", name: "AMD Telecom")
		.init(id: "apifon", name: "Apifon")
		.init(id: "bws", name: "BWS")
		.init(id: "compatel", name: "Compatel")
		.init(id: "cosmote", name: "Cosmote")
		.init(id: "cyta", name: "Cyta")
		.init(id: "forthnet", name: "Forthnet")
		.init(id: "inter_telecom", name: "Inter Telecom")
		.init(id: "m_stat", name: "M-STAT")
		.init(id: "mi_carrier_services", name: "MI Carrier Services")
		.init(id: "ose", name: "OSE")
		.init(id: "ote", name: "OTE")
		.init(id: "oteglobe", name: "OTEGlobe")
		.init(id: "premium_net_international", name: "Premium Net International")
		.init(id: "sia_netbalt", name: "SIA NETBALT")
		.init(id: "vodafone", name: "Vodafone")
		.init(id: "wind", name: "Wind")
		.init(id: "yuboto", name: "Yuboto")
	],
    ranges: [
		.init(prefix: "21", length: ["10"], areaCodeLength: nil, operator: nil, format: "athens_and_personal_2/4/4")
		.init(prefix: "2221", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2222", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2223", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2224", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2226", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2227", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2228", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2229", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2231", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2232", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2233", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2234", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2235", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2236", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2237", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2238", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2241", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2242", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2243", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2244", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2245", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2246", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2247", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2251", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2252", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2253", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2254", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2261", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2262", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2263", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2264", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2265", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2266", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2267", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2268", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2271", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2272", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2273", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2274", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2275", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2281", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2282", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2283", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2284", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2285", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2286", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2287", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2288", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2289", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2291", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2292", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2293", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2294", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2295", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2296", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2297", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2298", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2299", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "231", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "2321", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2322", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2323", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2324", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2325", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2327", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2331", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2332", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2333", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2341", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2343", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2351", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2352", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2353", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2371", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2372", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2373", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2374", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2375", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2376", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2377", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2381", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2382", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2384", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2385", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2386", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2391", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2392", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2393", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2394", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2395", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2396", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2397", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2399", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "241", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "2421", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2422", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2423", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2424", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2425", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2426", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2427", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2428", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2431", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2432", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2433", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2434", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2441", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2443", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2444", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2445", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2461", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2462", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2463", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2464", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2465", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2467", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2468", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2491", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2492", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2493", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2494", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2495", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "251", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "2521", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2522", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2523", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2524", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2531", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2532", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2533", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2534", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2535", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2541", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2542", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2544", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2551", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2552", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2553", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2554", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2555", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2556", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2591", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2592", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2593", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2594", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "261", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "2621", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2622", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2623", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2624", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2625", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2626", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2631", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2632", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2634", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2635", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2641", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2642", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2643", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2644", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2645", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2646", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2647", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2651", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2653", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2654", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2655", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2656", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2657", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2658", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2659", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2661", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2662", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2663", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2664", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2665", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2666", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2671", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2674", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2681", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2682", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2683", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2684", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2685", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2691", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2692", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2693", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2694", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2695", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2696", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "271", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "2721", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2722", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2723", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2724", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2725", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2731", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2732", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2733", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2734", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2735", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2736", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2741", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2742", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2743", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2744", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2745", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2746", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2747", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2751", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2752", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2753", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2754", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2755", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2757", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2761", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2763", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2765", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2791", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2792", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2795", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2796", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2797", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "281", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "2821", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2822", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2823", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2824", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2825", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2831", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2832", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2833", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2834", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2841", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2842", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2843", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2844", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2891", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2892", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2893", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2894", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2895", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "2897", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "5005000", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_4/6")
		.init(prefix: "685[02-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6851[0-7]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "68518[0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "685185", length: ["10"], areaCodeLength: nil, operator: "cyta", format: "all_3/3/4")
		.init(prefix: "68519", length: ["10"], areaCodeLength: nil, operator: "cyta", format: "all_3/3/4")
		.init(prefix: "6855[05][05]", length: ["10"], areaCodeLength: nil, operator: "cyta", format: "all_3/3/4")
		.init(prefix: "685501", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "68550[2-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6855[1-4679]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "68555[1-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "68558[0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "685585", length: ["10"], areaCodeLength: nil, operator: "cyta", format: "all_3/3/4")
		.init(prefix: "68[78][0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "68[78]500", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "68[78]50[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "68[78]5[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "689[0-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "689900", length: ["10"], areaCodeLength: nil, operator: "oteglobe", format: "all_3/3/4")
		.init(prefix: "689901", length: ["10"], areaCodeLength: nil, operator: "m_stat", format: "all_3/3/4")
		.init(prefix: "68990[2-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6899[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6900", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "690[1-5]00", length: ["10"], areaCodeLength: nil, operator: "mi_carrier_services", format: "all_3/3/4")
		.init(prefix: "690[1-4]0[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "690[1-4][1-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "690[1-4]9[0-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "690[1-4]99", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "69050[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6905[1-46]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69055[0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "690555", length: ["10"], areaCodeLength: nil, operator: "amd_telecom", format: "all_3/3/4")
		.init(prefix: "69057[0-36-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69057[45]", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "69058[0-79]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "690588", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "69059[0-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "690599", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "690[6-9]", length: ["10"], areaCodeLength: nil, operator: "wind", format: "all_3/3/4")
		.init(prefix: "691000", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "691[0467]0[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "691[0467][1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "691[159]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6912[0-24-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69123[0-35-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "691234", length: ["10"], areaCodeLength: nil, operator: "m_stat", format: "all_3/3/4")
		.init(prefix: "6913[0-35-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69134[0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "691345", length: ["10"], areaCodeLength: nil, operator: "forthnet", format: "all_3/3/4")
		.init(prefix: "691400", length: ["10"], areaCodeLength: nil, operator: "amd_telecom", format: "all_3/3/4")
		.init(prefix: "691600", length: ["10"], areaCodeLength: nil, operator: "compatel", format: "all_3/3/4")
		.init(prefix: "691700", length: ["10"], areaCodeLength: nil, operator: "inter_telecom", format: "all_3/3/4")
		.init(prefix: "6918[0-79]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69188[0-79]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "691888", length: ["10"], areaCodeLength: nil, operator: "ose", format: "all_3/3/4")
		.init(prefix: "692[0-25-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6923[0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69235[0-357-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "692354", length: ["10"], areaCodeLength: nil, operator: "premium_net_international", format: "all_3/3/4")
		.init(prefix: "692356", length: ["10"], areaCodeLength: nil, operator: "sia_netbalt", format: "all_3/3/4")
		.init(prefix: "6924[013-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69242[0-79]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "692428", length: ["10"], areaCodeLength: nil, operator: "premium_net_international", format: "all_3/3/4")
		.init(prefix: "693", length: ["10"], areaCodeLength: nil, operator: "wind", format: "all_3/3/4")
		.init(prefix: "694", length: ["10"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/4")
		.init(prefix: "695[015-9]", length: ["10"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/4")
		.init(prefix: "695200", length: ["10"], areaCodeLength: nil, operator: "compatel", format: "all_3/3/4")
		.init(prefix: "6952[01][1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "695210", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6952[23]", length: ["10"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/4")
		.init(prefix: "6952[49]", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "6952[5-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69530", length: ["10"], areaCodeLength: nil, operator: "cyta", format: "all_3/3/4")
		.init(prefix: "695310", length: ["10"], areaCodeLength: nil, operator: "mi_carrier_services", format: "all_3/3/4")
		.init(prefix: "6953[134][1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69532[0-79]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "695328", length: ["10"], areaCodeLength: nil, operator: "premium_net_international", format: "all_3/3/4")
		.init(prefix: "695330", length: ["10"], areaCodeLength: nil, operator: "apifon", format: "all_3/3/4")
		.init(prefix: "695340", length: ["10"], areaCodeLength: nil, operator: "amd_telecom", format: "all_3/3/4")
		.init(prefix: "69535[0-46-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "695355", length: ["10"], areaCodeLength: nil, operator: "cyta", format: "all_3/3/4")
		.init(prefix: "6953[6-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "695400", length: ["10"], areaCodeLength: nil, operator: "amd_telecom", format: "all_3/3/4")
		.init(prefix: "6954[01][1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "6954[19]0", length: ["10"], areaCodeLength: nil, operator: "mi_carrier_services", format: "all_3/3/4")
		.init(prefix: "6954[2-46-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69545[0-57-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "695456", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "69549[1-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "695499", length: ["10"], areaCodeLength: nil, operator: "m_stat", format: "all_3/3/4")
		.init(prefix: "6960[02-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69601", length: ["10"], areaCodeLength: nil, operator: "ote", format: "all_3/3/4")
		.init(prefix: "696[1-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69[78]", length: ["10"], areaCodeLength: nil, operator: "cosmote", format: "all_3/3/4")
		.init(prefix: "69900", length: ["10"], areaCodeLength: nil, operator: "wind", format: "all_3/3/4")
		.init(prefix: "699010", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "699011", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69901[2-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69902[013-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "699022", length: ["10"], areaCodeLength: nil, operator: "yuboto", format: "all_3/3/4")
		.init(prefix: "6990[35-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "69904[0-579]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "699046", length: ["10"], areaCodeLength: nil, operator: "premium_net_international", format: "all_3/3/4")
		.init(prefix: "699048", length: ["10"], areaCodeLength: nil, operator: "amd_telecom", format: "all_3/3/4")
		.init(prefix: "69909[0-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "699099", length: ["10"], areaCodeLength: nil, operator: "bws", format: "all_3/3/4")
		.init(prefix: "699[1-9]", length: ["10"], areaCodeLength: nil, operator: "wind", format: "all_3/3/4")
		.init(prefix: "70", length: ["10"], areaCodeLength: nil, operator: nil, format: "athens_and_personal_2/4/4")
		.init(prefix: "800", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "800", length: ["11"], areaCodeLength: nil, operator: nil, format: "toll_free_3/3-4/5")
		.init(prefix: "800", length: ["12"], areaCodeLength: nil, operator: nil, format: "toll_free_3/3-4/5")
		.init(prefix: "80[16]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "812", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "8[27]5", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "850", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "89[69]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "90[19]", length: ["10"], areaCodeLength: nil, operator: nil, format: "all_3/3/4")
		.init(prefix: "94", length: ["10"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/4")
	]
)

