//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_880 = RegionPhoneMetadata(
    code: 880,
    timezone: "Asia/Dhaka",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixedline_1/7-8", national: "#X-XXXXXXX*", international: "X-XXXXXXX*")
		.init(id: "fixedline_2/4-6", national: "#XX-XXXX**", international: "XX-XXXX**")
		.init(id: "fixedline_3/3-7", national: "#XXX-XXX****", international: "XXX-XXX****")
		.init(id: "fmt_4/3-6", national: "#XXXX-XXX***", international: "XXXX-XXX***")
	],
    operators: [
		.init(id: "airtel", name: "Airtel")
		.init(id: "banglalink", name: "Banglalink")
		.init(id: "citycell", name: "Citycell")
		.init(id: "grameenphone", name: "Grameenphone")
		.init(id: "robi", name: "Robi")
		.init(id: "teletalk", name: "TeleTalk")
	],
    ranges: [
		.init(prefix: "11", length: ["10"], areaCodeLength: nil, operator: "citycell", format: "fmt_4/3-6")
		.init(prefix: "1[37]", length: ["10"], areaCodeLength: nil, operator: "grameenphone", format: "fmt_4/3-6")
		.init(prefix: "1[49]", length: ["10"], areaCodeLength: nil, operator: "banglalink", format: "fmt_4/3-6")
		.init(prefix: "15", length: ["10"], areaCodeLength: nil, operator: "teletalk", format: "fmt_4/3-6")
		.init(prefix: "16", length: ["10"], areaCodeLength: nil, operator: "airtel", format: "fmt_4/3-6")
		.init(prefix: "18", length: ["10"], areaCodeLength: nil, operator: "robi", format: "fmt_4/3-6")
		.init(prefix: "2222", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "2[45]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "271[0-267]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "272[0-289]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "273[0-29]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "27[46][01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2751", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "275[23]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2763", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "277[017]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2778", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2791", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "280[125]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "281[1-356]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2814", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "282[0157-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "283[1-6]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2839", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2841", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "286[1-35]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "287[1-4]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2875", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "28[89][1256]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "288[3478]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "289[034]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "290[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2902", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2910", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "291[1-4]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "292[568]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "293[3-6]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "295[5-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "296[016-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2963", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "297[0-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "298[0167]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "298[489]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "2985", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_1/7-8")
		.init(prefix: "3020", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3022", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3023", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3024", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3025", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3026", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3027", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3028", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3029", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3032", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3033", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3034", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3035", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3036", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "312[5-7]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "315", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_2/4-6")
		.init(prefix: "31[67]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_2/4-6")
		.init(prefix: "3181", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_2/4-6")
		.init(prefix: "321", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "3221", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3222", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3223", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3224", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3225", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "331", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "3322", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3323", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3324", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3325", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3326", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "341", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "3422", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3424", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3425", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3427", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "351", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "3529", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "361", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "37[02-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "371", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "38[03-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "381", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "382", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3822", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3823", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "3824", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4020", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4027", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4029", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4033", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "41", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_2/4-6")
		.init(prefix: "421", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4222", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4223", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4224", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4225", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4226", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4227", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4228", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "431", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "431", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4320", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4322", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4323", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4324", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4325", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4326", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4327", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4328", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4329", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4332", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "44[0346-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "441", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "442[0-24-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "442[2-46]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4423", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4423[0-46-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "44235[0-57-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "442356", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "445[013-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4452", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4452", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4455", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "448[0-57-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4486[014-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4486[23]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "451", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4523", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4525", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "461", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4623", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4624", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4625", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4626", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4627", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "46528", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4653", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4654", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4655", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4656", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4657", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4658", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4662", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "468", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "471", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "481", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4823", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4854", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "488", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "491", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "4922", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4923", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4924", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4925", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "4953", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "498", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5020", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5023", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5024", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5028", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5029", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "51", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixedline_2/4-6")
		.init(prefix: "521", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5222", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5222", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5224", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5225", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5227", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "531", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5323", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5325", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5326", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5327", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5329", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "541", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5424", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "5426", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "551", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5526", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "561", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "562", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5653", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "568", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "571", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5724", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "581", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "5826", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "591", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "601", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6023", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6024", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "61[7-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6222", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6223", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6224", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6225", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6253", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6254", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6255", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6257", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "628", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "631", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6323", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6324", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6327", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6328", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "641", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6423", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6424", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "644", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "651", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6524", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6527", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "66[0347-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "661", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "66[25]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "666[01346-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6662[0-25-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "66622", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6662[34]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6665[016-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6665[24]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6665[35]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "66653", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "66655", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "668", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6722", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6723", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6724", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6725", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "681", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6822", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6823", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6824", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6825", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "691", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "6922", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6923", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6924", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6925", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "6926", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "702", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "715[3-5]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "716[12]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "717[156]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "7189", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "721", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "722[589]56", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "72258", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "72278", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "72288", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "72298", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "731", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "732", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "741", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "74258", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "742675", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "74268", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "751", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "752[25689]56", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "752[2-9]8", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "761", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "762", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "7716[1267]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "77175", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "77189", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "7722", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "7724", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "781", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "78238", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "78258", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "791", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "792374", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "800", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "80[14-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "802", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "803", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "81", length: ["6", "7"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "8217", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82181", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82208", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82228", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82238", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82248", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "822[59]56", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82268", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82278", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "82298", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "823256", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "831", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "832", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "8332[6-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "841", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "842", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "851", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "852", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "861", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "862", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "871", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "872", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "902", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "903[23]56", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "91", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixedline_2/4-6")
		.init(prefix: "921", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "922", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "923256", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "92328", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "923373", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "931", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "941", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "942", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "951", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "952[4589]56", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
		.init(prefix: "960[469]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "961[0-47]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "963[389]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "9643", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "966[69]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "967[78]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_4/3-6")
		.init(prefix: "981", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixedline_3/3-7")
	]
)

