//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_212 = RegionPhoneMetadata(
    code: 212,
    timezone: "Atlantic/Canary",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: "EH",
    formats: [
		.init(id: "fmt1_3/6", national: "#XXX-XXXXXX", international: "XXX-XXXXXX")
		.init(id: "fmt2_4/5", national: "#XXXX-XXXXX", international: "XXXX-XXXXX")
		.init(id: "fmt4_3/2/2/2", national: "#XXX XX XX XX", international: "XXX XX XX XX")
		.init(id: "fmt5_2/7", national: "#XX-XXXXXXX", international: "XX-XXXXXXX")
	],
    operators: [
		.init(id: "al_hourria_telecom", name: "Al Hourria Telecom")
		.init(id: "inwi", name: "Inwi")
		.init(id: "maroc_telecom", name: "Maroc Telecom")
		.init(id: "meditel", name: "Méditel")
	],
    ranges: [
		.init(prefix: "520", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "521", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "5220", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5221", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "522[2-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "523[18]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5232", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5233", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5234", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5235", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5237", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5240", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5242", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "524[34]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5246", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5247", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5248", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "525", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "52[67]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "5280", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "5282", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5283", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5285", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5286", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5287", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5288", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5289", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "529[0-5]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "529[68]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "529[79]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "530", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "531", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "532", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "53[34]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "5350", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5352", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5353", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "535[45]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "535[69]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5357", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5358", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "536[04]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5362", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5363", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5365", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5366", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5367", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5368", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "537[01]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "537[27]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5373", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5374", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5375", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5376", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5378", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5379", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "538[01]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "538[458]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "538[679]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5393", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5394", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5395", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5396", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5397", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5398", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "5399", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "54[067]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt4_3/2/2/2")
		.init(prefix: "55[03]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt4_3/2/2/2")
		.init(prefix: "5924[0-2]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "59293", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "60", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "61[013568]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "61[2479]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "62[015]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "62[2-48]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "62[679]", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "63[03-58]", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "63[12]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "63[679]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "64[067]", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "64[1-38]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "6[47][459]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "65[0-589]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "65[67]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "66[03-59]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "66[126-8]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "67[0-36-8]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "68[017]", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "68[29]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "68[48]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "69[0589]", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "69[134]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "692[03-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/6")
		.init(prefix: "692[12]", length: ["9"], areaCodeLength: nil, operator: "al_hourria_telecom", format: "fmt1_3/6")
		.init(prefix: "69[67]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "7[01]", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "72[0-2]", length: ["9"], areaCodeLength: nil, operator: "inwi", format: "fmt1_3/6")
		.init(prefix: "75[01]", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "76", length: ["9"], areaCodeLength: nil, operator: "maroc_telecom", format: "fmt1_3/6")
		.init(prefix: "77", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "78[0-3]", length: ["9"], areaCodeLength: nil, operator: "meditel", format: "fmt1_3/6")
		.init(prefix: "80[0-7]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt5_2/7")
		.init(prefix: "80[89]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
		.init(prefix: "89[013-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt5_2/7")
		.init(prefix: "892", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_4/5")
	]
)

