//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_420 = RegionPhoneMetadata(
    code: 420,
    timezone: "Europe/Prague",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_3/3/3", national: "XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "fmt2_3/3/3/3", national: "XXX XXX XXX XXX", international: "XXX XXX XXX XXX")
		.init(id: "fmt3_2/3/3/3", national: "XX XXX XXX XXX", international: "XX XXX XXX XXX")
		.init(id: "fmt4_2/3/3/2", national: "XX XXX XXX XX", international: "XX XXX XXX XX")
	],
    operators: [
		.init(id: "3ton", name: "3ton s.r.o.")
		.init(id: "amcatel", name: "Amcatel")
		.init(id: "axfone", name: "Axfone")
		.init(id: "bsg", name: "BSG")
		.init(id: "cez", name: "CEZ Group")
		.init(id: "coma", name: "COMA")
		.init(id: "compatel", name: "Compatel")
		.init(id: "dialtelecom", name: "Dial Telecom")
		.init(id: "dragon", name: "Dragon Internet")
		.init(id: "eri", name: "Cesky bezdrat")
		.init(id: "fayn", name: "FAYN Telecommunications")
		.init(id: "gomobil", name: "GoMobil")
		.init(id: "gope_systems", name: "GOPE Systems a.s.")
		.init(id: "ha_vel", name: "ha-vel internet")
		.init(id: "ipex", name: "IPEX")
		.init(id: "materna_communications", name: "MATERNA Communications")
		.init(id: "maxprogres", name: "MAXPROGRES")
		.init(id: "metronet", name: "METRONET")
		.init(id: "minitel", name: "miniTEL")
		.init(id: "montyho", name: "MONTYHO TECHNOLOGY s.r.o. (CANISTEC)")
		.init(id: "nordictelecom", name: "Nordic Telecom s.r.o.(Air Telecom - MobilKom)")
		.init(id: "o2", name: "O2")
		.init(id: "plus4u_mobile", name: "Plus4U Mobile s.r.o.")
		.init(id: "poda", name: "PODA a.s. (SkyNet)")
		.init(id: "sazka_sazkova_kancelar", name: "SAZKA sazkova kancelar, a.s")
		.init(id: "sia_net_balt", name: "SIA Net Balt")
		.init(id: "smart_comp", name: "SMART Comp")
		.init(id: "t_mobile", name: "T-Mobile")
		.init(id: "terms", name: "TERMS")
		.init(id: "tesco_mobile", name: "Tesco Mobile CR")
		.init(id: "travel_telekommunikation", name: "TRAVEL TELEKOMMUNIKATION")
		.init(id: "ttquality", name: "TT Quality s.r.o.")
		.init(id: "vectone", name: "Vectone Distribution Czech Republic s.r.o(Mundio)")
		.init(id: "vodafone", name: "Vodafone")
	],
    ranges: [
		.init(prefix: "2", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "3[12]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "35", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "37", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "3[89]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "4[17]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "46", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "48", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "49", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "5[134]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "5[59]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "56", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "57", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "58", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "60[1267]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "60[3-5]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "608", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "70[01]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "702", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "70300", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7030[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "703[1-689]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "70370", length: ["9"], areaCodeLength: nil, operator: "fayn", format: "fmt1_3/3/3")
		.init(prefix: "7037[12457-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "70373", length: ["9"], areaCodeLength: nil, operator: "coma", format: "fmt1_3/3/3")
		.init(prefix: "70376", length: ["9"], areaCodeLength: nil, operator: "bsg", format: "fmt1_3/3/3")
		.init(prefix: "704[0-57]", length: ["9"], areaCodeLength: nil, operator: "sazka_sazkova_kancelar", format: "fmt1_3/3/3")
		.init(prefix: "704[689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "705[0-4]", length: ["9"], areaCodeLength: nil, operator: "cez", format: "fmt1_3/3/3")
		.init(prefix: "7055", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "705[6-9]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "72", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "730[0-25689]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "73030", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7303[1246-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "73033", length: ["9"], areaCodeLength: nil, operator: "axfone", format: "fmt1_3/3/3")
		.init(prefix: "73035", length: ["9"], areaCodeLength: nil, operator: "materna_communications", format: "fmt1_3/3/3")
		.init(prefix: "73040", length: ["9"], areaCodeLength: nil, operator: "compatel", format: "fmt1_3/3/3")
		.init(prefix: "7304[12]", length: ["9"], areaCodeLength: nil, operator: "smart_comp", format: "fmt1_3/3/3")
		.init(prefix: "73043", length: ["9"], areaCodeLength: nil, operator: "poda", format: "fmt1_3/3/3")
		.init(prefix: "7304[4-8]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "73049", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7307[037]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7307[14-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "73072", length: ["9"], areaCodeLength: nil, operator: "amcatel", format: "fmt1_3/3/3")
		.init(prefix: "73[1-9]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "770[0-46]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "77050", length: ["9"], areaCodeLength: nil, operator: "compatel", format: "fmt1_3/3/3")
		.init(prefix: "7705[12]", length: ["9"], areaCodeLength: nil, operator: "3ton", format: "fmt1_3/3/3")
		.init(prefix: "7705[3-9]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "77070", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "7707[12]", length: ["9"], areaCodeLength: nil, operator: "eri", format: "fmt1_3/3/3")
		.init(prefix: "7707[37]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7707[4-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7708[0-4]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "7708[5-9]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "7709", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "77[12]00", length: ["9"], areaCodeLength: nil, operator: "ttquality", format: "fmt1_3/3/3")
		.init(prefix: "7710[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7711[02-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "77111", length: ["9"], areaCodeLength: nil, operator: "minitel", format: "fmt1_3/3/3")
		.init(prefix: "771[2-69]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7717[0-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "77177", length: ["9"], areaCodeLength: nil, operator: "montyho", format: "fmt1_3/3/3")
		.init(prefix: "7718", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "7720[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "772[1-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7727[014-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7727[23]", length: ["9"], areaCodeLength: nil, operator: "ipex", format: "fmt1_3/3/3")
		.init(prefix: "77277", length: ["9"], areaCodeLength: nil, operator: "dragon", format: "fmt1_3/3/3")
		.init(prefix: "77[3-7]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "778[02-79]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "77810", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "778[18][1-9]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt1_3/3/3")
		.init(prefix: "77880", length: ["9"], areaCodeLength: nil, operator: "ha_vel", format: "fmt1_3/3/3")
		.init(prefix: "77900", length: ["9"], areaCodeLength: nil, operator: "ttquality", format: "fmt1_3/3/3")
		.init(prefix: "7790[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "779[1-68]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7797[0-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "77977", length: ["9"], areaCodeLength: nil, operator: "ttquality", format: "fmt1_3/3/3")
		.init(prefix: "77990", length: ["9"], areaCodeLength: nil, operator: "ha_vel", format: "fmt1_3/3/3")
		.init(prefix: "7799[1-68]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "77997", length: ["9"], areaCodeLength: nil, operator: "plus4u_mobile", format: "fmt1_3/3/3")
		.init(prefix: "77999", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "79000", length: ["9"], areaCodeLength: nil, operator: "nordictelecom", format: "fmt1_3/3/3")
		.init(prefix: "7900[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "790[1-4679]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7905[0-79]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79058", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7908[0-24-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79083", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7910", length: ["9"], areaCodeLength: nil, operator: "travel_telekommunikation", format: "fmt1_3/3/3")
		.init(prefix: "791[1-8]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79190", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79191", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "79192", length: ["9"], areaCodeLength: nil, operator: "3ton", format: "fmt1_3/3/3")
		.init(prefix: "79193", length: ["9"], areaCodeLength: nil, operator: "gope_systems", format: "fmt1_3/3/3")
		.init(prefix: "7919[4-9]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "792[0-25]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "7923[0-3679]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "7923[458]", length: ["9"], areaCodeLength: nil, operator: "tesco_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7924[0-4]", length: ["9"], areaCodeLength: nil, operator: "tesco_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7924[5-9]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "79260", length: ["9"], areaCodeLength: nil, operator: "sia_net_balt", format: "fmt1_3/3/3")
		.init(prefix: "7926[1-9]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "7927", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "792[89]", length: ["9"], areaCodeLength: nil, operator: "tesco_mobile", format: "fmt1_3/3/3")
		.init(prefix: "793[0-8]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79390", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7939[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "794[0-8]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "7949", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "795[01]", length: ["9"], areaCodeLength: nil, operator: "vectone", format: "fmt1_3/3/3")
		.init(prefix: "795[23]", length: ["9"], areaCodeLength: nil, operator: "o2", format: "fmt1_3/3/3")
		.init(prefix: "795[4-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79[68]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "797[0-4]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79750", length: ["9"], areaCodeLength: nil, operator: "dialtelecom", format: "fmt1_3/3/3")
		.init(prefix: "7975[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "797[68]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7977[0-2579]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7977[3468]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7979[0-68]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7979[79]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "79900", length: ["9"], areaCodeLength: nil, operator: "maxprogres", format: "fmt1_3/3/3")
		.init(prefix: "799[02][1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7991", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "79920", length: ["9"], areaCodeLength: nil, operator: "metronet", format: "fmt1_3/3/3")
		.init(prefix: "799[3468]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "7995[0-3]", length: ["9"], areaCodeLength: nil, operator: "terms", format: "fmt1_3/3/3")
		.init(prefix: "79954", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7995[56]", length: ["9"], areaCodeLength: nil, operator: "gomobil", format: "fmt1_3/3/3")
		.init(prefix: "79957", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "7995[89]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "799[79][0-8]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "79979", length: ["9"], areaCodeLength: nil, operator: "minitel", format: "fmt1_3/3/3")
		.init(prefix: "79999", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "fmt1_3/3/3")
		.init(prefix: "800", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "8[134]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "90[05689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "9[17]0", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "9[36]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fmt3_2/3/3/3")
		.init(prefix: "95", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "96", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "96", length: ["12"], areaCodeLength: nil, operator: nil, format: "fmt2_3/3/3/3")
		.init(prefix: "96[0189]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt4_2/3/3/2")
		.init(prefix: "96[2-7]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt4_2/3/3/2")
		.init(prefix: "971", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "97[23]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "974", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
		.init(prefix: "976", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/3/3")
	]
)

