//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_233 = RegionPhoneMetadata(
    code: 233,
    timezone: "Africa/Accra",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt_2/3/4", national: "#XX XXX XXXX", international: "XX XXX XXXX")
		.init(id: "toll_3/5", national: "#XXX XXXXX", international: "XXX XXXXX")
	],
    operators: [
		.init(id: "airteltigo", name: "airteltiGO")
		.init(id: "expresso", name: "Expresso")
		.init(id: "mtn", name: "MTN")
		.init(id: "national_security", name: "National Security")
		.init(id: "vodafone", name: "Vodafone")
	],
    ranges: [
		.init(prefix: "[25]0", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/4")
		.init(prefix: "2[367]", length: ["9"], areaCodeLength: nil, operator: "airteltigo", format: "fmt_2/3/4")
		.init(prefix: "24", length: ["9"], areaCodeLength: nil, operator: "mtn", format: "fmt_2/3/4")
		.init(prefix: "25[67]", length: ["9"], areaCodeLength: nil, operator: "mtn", format: "fmt_2/3/4")
		.init(prefix: "28", length: ["9"], areaCodeLength: nil, operator: "expresso", format: "fmt_2/3/4")
		.init(prefix: "29", length: ["9"], areaCodeLength: nil, operator: "national_security", format: "fmt_2/3/4")
		.init(prefix: "302", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "303[0-46-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3035", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "307", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "308[01]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3082[0-5]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3120", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3121", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3122", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3123", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3124", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3125", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3126", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "317", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3180", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3220", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3221", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3222", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3223", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3224", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3225", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "327", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3280", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3320", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3321", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3322", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3323", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "337", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3380", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3420", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3421", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3423", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3424", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3425", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3426", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3427", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3428", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3429[013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "34292", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3430", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3431", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "347", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3480", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3520", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3521", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3522", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3523", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3524", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3525", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3526", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3527", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "357", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3580", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3620", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3621", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3622", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3623", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3624", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3625", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3626", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "367", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3680", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3720", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3721", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3722", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3723", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3724", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3725", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3726", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "377", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3780", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3820", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3821", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3822", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "387", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3880", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3920", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "397", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "3980", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "53", length: ["9"], areaCodeLength: nil, operator: "mtn", format: "fmt_2/3/4")
		.init(prefix: "5[45]", length: ["9"], areaCodeLength: nil, operator: "mtn", format: "fmt_2/3/4")
		.init(prefix: "5[67]", length: ["9"], areaCodeLength: nil, operator: "airteltigo", format: "fmt_2/3/4")
		.init(prefix: "59[1-6]", length: ["9"], areaCodeLength: nil, operator: "mtn", format: "fmt_2/3/4")
		.init(prefix: "59[7-9]", length: ["9"], areaCodeLength: nil, operator: "mtn", format: "fmt_2/3/4")
		.init(prefix: "800", length: ["8"], areaCodeLength: nil, operator: nil, format: "toll_3/5")
	]
)

