//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_82 = RegionPhoneMetadata(
    code: 82,
    timezone: "Asia/Seoul",
    nationalPrefix: 0,
    extraRegion: [],
    formats: [
		.init(id: "fixed_line_1/3-4/4", national: "#X-XXX*-XXXX", international: "X-XXX*-XXXX")
		.init(id: "fixed_line_2/3-4", national: "#XX-XXX*", international: "XX-XXX*")
		.init(id: "fmt_2/3-4/4", national: "#XX-XXX*-XXXX", international: "XX-XXX*-XXXX")
		.init(id: "fmt_2/3/4", national: "#XX-XXX-XXXX", international: "XX-XXX-XXXX")
		.init(id: "fmt_2/4/4", national: "#XX-XXXX-XXXX", international: "XX-XXXX-XXXX")
		.init(id: "personal_2/5/4", national: "#XX-XXXXX-XXXX", international: "XX-XXXXX-XXXX")
		.init(id: "short_code_5", national: "#XXXXX", international: )
		.init(id: "toll_free_5/2/3/4", national: "XXXXX XX XXX XXXX", international: )
		.init(id: "toll_free_5/3-4/4", national: "XXXXX XXX* XXXX", international: )
		.init(id: "toll_free_5/3/3", national: "XXXXX XXX XXX", international: )
		.init(id: "uan_4/4", national: "XXXX-XXXX", international: "XXXX-XXXX")
	],
    operators: [
		.init(id: "__onse_telecom", name: "Onse Telecom")
		.init(id: "__samsung_networks", name: "Samsung networks")
		.init(id: "__sejong_telecom", name: "Sejong Telecom")
		.init(id: "__skb", name: "SKB")
		.init(id: "__unknown", name: )
		.init(id: "kt", name: "KT")
		.init(id: "lg", name: "LG U+")
		.init(id: "sk_tellink", name: "SKTellink")
	],
    ranges: [
		.init(prefix: "00308", length: ["11"], areaCodeLength: nil, operator: nil, format: "toll_free_5/3/3")
		.init(prefix: "003[06]8", length: ["12"], areaCodeLength: nil, operator: nil, format: "toll_free_5/3-4/4")
		.init(prefix: "00798", length: ["12", "13"], areaCodeLength: nil, operator: nil, format: "toll_free_5/3-4/4")
		.init(prefix: "00798", length: ["14"], areaCodeLength: nil, operator: nil, format: "toll_free_5/2/3/4")
		.init(prefix: "100", length: ["9", "10"], areaCodeLength: nil, operator: "lg", format: "fmt_2/3-4/4")
		.init(prefix: "101", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "102[01]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "102[2-4]", length: ["9", "10"], areaCodeLength: nil, operator: "lg", format: "fmt_2/3-4/4")
		.init(prefix: "10[29][5-9]", length: ["9", "10"], areaCodeLength: nil, operator: "kt", format: "fmt_2/3-4/4")
		.init(prefix: "103[02-4]", length: ["9", "10"], areaCodeLength: nil, operator: "kt", format: "fmt_2/3-4/4")
		.init(prefix: "103[15-8]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "1039", length: ["9", "10"], areaCodeLength: nil, operator: "lg", format: "fmt_2/3-4/4")
		.init(prefix: "104[015-9]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "10[47][2-4]", length: ["9", "10"], areaCodeLength: nil, operator: "kt", format: "fmt_2/3-4/4")
		.init(prefix: "105[02-4]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "1051", length: ["9", "10"], areaCodeLength: nil, operator: "kt", format: "fmt_2/3-4/4")
		.init(prefix: "105[5-8]", length: ["9", "10"], areaCodeLength: nil, operator: "lg", format: "fmt_2/3-4/4")
		.init(prefix: "10590", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "1059[1-5]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "10596", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "106[019]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "106[2-4]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "106[5-8]", length: ["9", "10"], areaCodeLength: nil, operator: "kt", format: "fmt_2/3-4/4")
		.init(prefix: "1070", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "1071", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "107[5-79]", length: ["9", "10"], areaCodeLength: nil, operator: "lg", format: "fmt_2/3-4/4")
		.init(prefix: "1078", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "108[0-4]", length: ["9", "10"], areaCodeLength: nil, operator: "lg", format: "fmt_2/3-4/4")
		.init(prefix: "108[5-9]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "109[0-4]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "1[17]", length: ["9", "10"], areaCodeLength: nil, operator: "sk_tellink", format: "fmt_2/3-4/4")
		.init(prefix: "12[013-9]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "122[13]", length: ["9", "10"], areaCodeLength: nil, operator: "kt", format: "fmt_2/3-4/4")
		.init(prefix: "15", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "1522", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1533", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1544", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1566", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1577", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1588", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1599", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1[68]", length: ["9", "10"], areaCodeLength: nil, operator: "kt", format: "fmt_2/3-4/4")
		.init(prefix: "16[07]0", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1644", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "166[16]", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1668", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1688", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1800", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1833", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1855", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1877", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "1899", length: ["8"], areaCodeLength: nil, operator: nil, format: "uan_4/4")
		.init(prefix: "19", length: ["9", "10"], areaCodeLength: nil, operator: "lg", format: "fmt_2/3-4/4")
		.init(prefix: "2[1-9]", length: ["8", "9"], areaCodeLength: 1, operator: nil, format: "fixed_line_1/3-4/4")
		.init(prefix: "311", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "31[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "321", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "32[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "331", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "33[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "411", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "41[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "421", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "42[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "431", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "43[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "441", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "44[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "50", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4/4")
		.init(prefix: "50", length: ["11"], areaCodeLength: nil, operator: nil, format: "personal_2/5/4")
		.init(prefix: "511", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "51[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "521", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "52[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "531", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "53[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "541", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "54[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "551", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "55[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "60[2-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "611", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "61[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "621", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "62[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "631", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "63[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "641", length: ["5", "6"], areaCodeLength: 2, operator: nil, format: "fixed_line_2/3-4")
		.init(prefix: "64[1-9]", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fmt_2/3-4/4")
		.init(prefix: "70", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4/4")
		.init(prefix: "80", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/4")
	]
)

