//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_355 = RegionPhoneMetadata(
    code: 355,
    timezone: "Europe/Tirane",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_1/3/4", national: "#X XXX XXXX", international: "X XXX XXXX")
		.init(id: "fixed_2/3/3", national: "#XX XXX XXX", international: "XX XXX XXX")
		.init(id: "fixed_3/5", national: "#XXX XXXXX", international: "XXX XXXXX")
		.init(id: "fmt_3/3-4", national: "#XXX XXX*", international: "XXX XXX*")
		.init(id: "mobile_2/3/4", national: "#XX XXX XXXX", international: "XX XXX XXXX")
	],
    operators: [
		.init(id: "albtelecom", name: "ALBtelecom")
		.init(id: "telekom", name: "Telekom")
		.init(id: "vodafone", name: "Vodafone")
	],
    ranges: [
		.init(prefix: "2[168]0[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "211[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "212[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "213[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "214[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "215[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "216[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "217[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "218[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "219[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "22[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "2[35][2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "24[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "261[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "262[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "263[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "264[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "265[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "266[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "267[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "268[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "269[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "270[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "271[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "272[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "273[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "274[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "275[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "276[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "277[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "278[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "279[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "281[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "282[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "283[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "284[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "285[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "286[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "287[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "288[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "289[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "29[089][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "291[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "292[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "293[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "294[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "295[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "296[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "297[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "31[04-9][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "311[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "312[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "313[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "32[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "33[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "34[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "35[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "360[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "361[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "362[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "363[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "364[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "365[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "366[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "367[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "368[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "369[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "3[79][09][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "371[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "372[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "373[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "374[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "375[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "376[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "377[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "378[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "380[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "381[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "382[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "383[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "384[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "385[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "386[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "387[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "388[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "389[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "391[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "392[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "393[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "394[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "395[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "396[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "397[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "398[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "4[2-5][2-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "4410", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "4505[0-2]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "46", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "47[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "48[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "49[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "51[05-9][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "511[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "512[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "513[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "514[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "52[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "53[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "54[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "55[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "56[06-9][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "561[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "562[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "563[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "564[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "565[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "570[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "571[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "572[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "573[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "574[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "575[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "576[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "577[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "578[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "579[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "580[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "581[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "582[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "583[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "584[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "585[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "586[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "587[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "588[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "589[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "59[089][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "591[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "592[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "593[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "594[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "595[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "596[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "597[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "67[2-9]", length: ["9"], areaCodeLength: nil, operator: "albtelecom", format: "mobile_2/3/4")
		.init(prefix: "68[2-9]", length: ["9"], areaCodeLength: nil, operator: "telekom", format: "mobile_2/3/4")
		.init(prefix: "69", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "mobile_2/3/4")
		.init(prefix: "700[2-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_3/5")
		.init(prefix: "800", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-4")
		.init(prefix: "808[1-9]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-4")
		.init(prefix: "8[19][06-9][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "811[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "812[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "813[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "814[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "815[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "82[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "83[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "84[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "85[2-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "860[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "861[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "862[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "863[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "864[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "865[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "866[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "867[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "868[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "869[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "8[78][089][2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "871[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "872[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "873[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "874[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "875[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "876[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "877[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "881[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "882[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "883[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "884[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "885[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "886[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "887[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "891[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "892[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "893[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "894[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "895[2-9]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/5")
		.init(prefix: "900[1-9]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-4")
	]
)

