//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_65 = RegionPhoneMetadata(
    code: 65,
    timezone: "Asia/Singapore",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_4/4", national: "XXXX XXXX", international: "XXXX XXXX")
		.init(id: "fmt2_4/3/4", national: "XXXX XXX XXXX", international: "XXXX XXX XXXX")
		.init(id: "fmt3_4/4/3", national: "XXXX XXXX XXX", international: "XXXX XXXX XXX")
		.init(id: "fmt4_3/3/4", national: "XXX XXX XXXX", international: "XXX XXX XXXX")
		.init(id: "shortcode_4-5", national: "XXXX*", international: nil)
	],
    operators: [
		.init(id: "changi", name: "Changi Travel Services Pte Ltd")
		.init(id: "m1", name: "M1")
		.init(id: "myrepublic", name: "myrepublic")
		.init(id: "red_one", name: "red one")
		.init(id: "simba", name: "Simba")
		.init(id: "singtel", name: "SingTel")
		.init(id: "starhub", name: "StarHub")
		.init(id: "vivohub", name: "vivohub")
	],
    ranges: [
		.init(prefix: "1800", length: ["11"], areaCodeLength: nil, operator: nil, format: "fmt2_4/3/4")
		.init(prefix: "1900", length: ["11"], areaCodeLength: nil, operator: nil, format: "fmt2_4/3/4")
		.init(prefix: "3[12]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "60", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6[1-578]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "660[0-4]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "660[5-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "661[0-28]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "661[3-79]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "662[014-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6622", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "66[3-57-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6660", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "666[1-357-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6664", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6666", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "69[0-356]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "697[0-5]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "697[6-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "698[0-79]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6988", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "699[0-57-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6996", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "7000", length: ["11"], areaCodeLength: nil, operator: nil, format: "fmt3_4/4/3")
		.init(prefix: "800", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt4_3/3/4")
		.init(prefix: "801[0-7]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "801[89]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "802[017-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "802[23]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8024", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "802[56]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "803[016-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8032", length: ["8"], areaCodeLength: nil, operator: "changi", format: "fmt1_4/4")
		.init(prefix: "803[3-5]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "804[059]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "804[167]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "804[23]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8044", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8048", length: ["8"], areaCodeLength: nil, operator: "myrepublic", format: "fmt1_4/4")
		.init(prefix: "805[0-259]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "805[36-8]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8054", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "806[0-689]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8067", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "807[01]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "807[2-9]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "808[01]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8083", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "81[07]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "81[1356]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "812", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8140", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "814[1-9]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "818[03-79]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "818[12]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8188", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "819[0-79]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8198", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "82[045]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "821[0-79]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8218", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "822[014-79]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8222", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "822[38]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "823", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "826[0-79]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8268", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "827", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "828[013-79]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "828[28]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "829[0-8]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8299", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "83[014]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "832[03-69]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "832[128]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "83[29]7", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "833[0-24-7]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8333", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "833[89]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "835[013-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8352", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8360", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "836[1-479]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8365", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "836[68]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "837[0378]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "837[124-69]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "838[049]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "838[15-7]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "838[238]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "839[0-24-6]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "839[389]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8400", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "840[1-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "841[02-9]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8411", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "84[23]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "844", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "845[0-57-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "84[59]6", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "846[0-79]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "84[69]8", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "847", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "848", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "849[0-5]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8497", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8499", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8500", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "850[13589]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "850[2467]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "851[018]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "851[2-49]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "85[127]5", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "851[67]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "852[018]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "852[2-4]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "852[679]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "853[0-2]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8533", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "853[4-7]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8538", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8539", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "854", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "855[0-68]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8557", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8559", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "856", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "857[0-2]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "857[346-9]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "858[0158]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "858[2-4679]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "859[015]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "859[23]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "859[46-9]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "86[03]0", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "860[1-9]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "861[05-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "861[1-4]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "862[0-2]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "862[3-9]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "863[13-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8632", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "864[06-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "864[1-5]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "865[0-7]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "865[89]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "866[01]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "866[2-579]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "866[68]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "867", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "868[0-29]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "868[3-8]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8690", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "869[1-39]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "869[4-8]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "87[09]0", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "870[1-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "871[023]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "871[14-9]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "872[013]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "872[24-9]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "873[0-24-6]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "873[38]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "873[79]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "874[013-7]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "874[289]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "875[0-3]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "875[45]", length: ["8"], areaCodeLength: nil, operator: "myrepublic", format: "fmt1_4/4")
		.init(prefix: "875[6-9]", length: ["8"], areaCodeLength: nil, operator: "red_one", format: "fmt1_4/4")
		.init(prefix: "8760", length: ["8"], areaCodeLength: nil, operator: "red_one", format: "fmt1_4/4")
		.init(prefix: "8761", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "876[2-4]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8765", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8766", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "876[78]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8769", length: ["8"], areaCodeLength: nil, operator: "myrepublic", format: "fmt1_4/4")
		.init(prefix: "877[0-2]", length: ["8"], areaCodeLength: nil, operator: "vivohub", format: "fmt1_4/4")
		.init(prefix: "877[3-5]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "877[69]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "877[78]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "878[03-5]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "878[126-8]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8789", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "8791", length: ["8"], areaCodeLength: nil, operator: "myrepublic", format: "fmt1_4/4")
		.init(prefix: "879[23]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "879[45]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "8796", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8797", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "879[89]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8800", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "880[1-7]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8808", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8809", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "881[09]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "881[1-368]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "881[457]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "882[0-368]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "882[457]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8829", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "883[01]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "883[24-79]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "883[38]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "884[0156]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "884[23]", length: ["8"], areaCodeLength: nil, operator: "vivohub", format: "fmt1_4/4")
		.init(prefix: "884[48]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "884[79]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "885[0-4679]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "885[58]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "886[013-57]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "886[268]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "8869", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "887[0-589]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "8876", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8877", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "888", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "889[0-4]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "889[5-9]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "89[03][0-4]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "890[5-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "891", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8920", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "892[1-3]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "89[24][4-8]", length: ["8"], areaCodeLength: nil, operator: "simba", format: "fmt1_4/4")
		.init(prefix: "8929", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "893[5-7]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "893[89]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "894[0-3]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "8949", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "895[0-2]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "9000", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "900[1-9]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "90[1358]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "90[26]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "90[479]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "91[0468]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "91[12]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "91[357]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "919[0-8]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "9199", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "92[01568]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "922", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "923[0-6]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "923[7-9]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "924", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "927[0-2]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "927[3-9]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "929[0-4]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "929[5-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "93[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "93[246]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "933[0-3]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "9334", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "933[5-9]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "93[57]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "938", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "939", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "94[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "94[258]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "94[37]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "944", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "946", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "949[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "9499", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "95", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "9[67]0", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "96[13-7]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "962", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "96[89]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "971", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "97[23578]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "97[469]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "9800", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "980[1-589]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "980[67]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "981[0-25-9]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "981[34]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "98[239]", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "98[47]", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
		.init(prefix: "985", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "986", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "988[0-7]", length: ["8"], areaCodeLength: nil, operator: "starhub", format: "fmt1_4/4")
		.init(prefix: "9888", length: ["8"], areaCodeLength: nil, operator: "singtel", format: "fmt1_4/4")
		.init(prefix: "9889", length: ["8"], areaCodeLength: nil, operator: "m1", format: "fmt1_4/4")
	]
)

