//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_351 = RegionPhoneMetadata(
    code: 351,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "all_3/3/3", national: "XXX XXX XXX", international: "XXX XXX XXX")
	],
    operators: [
		.init(id: "digi", name: "Digi Communications")
		.init(id: "lycamobile", name: "Lycamobile")
		.init(id: "meo", name: "MEO")
		.init(id: "nos", name: "NOS")
		.init(id: "nowo", name: "NOWO")
		.init(id: "onitelecom", name: "ONITELECOM")
		.init(id: "suma-movil", name: "Sumamovil Portugal")
		.init(id: "vodafone", name: "Vodafone")
	],
    ranges: [
		.init(prefix: "1693", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "21", length: ["9"], areaCodeLength: nil, operator: nil, format: "porto_lisbon_2/3/4")
		.init(prefix: "22", length: ["9"], areaCodeLength: nil, operator: nil, format: "porto_lisbon_2/3/4")
		.init(prefix: "231", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "232", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "233", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "234", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "235", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "236", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "238", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "239", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "241", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "242", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "243", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "244", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "245", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "249", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "251", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "252", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "253", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "254", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "255", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "256", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "257", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "258", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "259", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "261", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "262", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "263", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "265", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "266", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "268", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "269", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "271", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "272", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "273", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "274", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "275", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "276", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "277", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "278", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "279", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "281", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "282", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "283", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "284", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "285", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "286", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "289", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "291", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "292", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "295", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "296", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "30", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "600", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "60[178]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "609230", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "6[06]9233", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "60929", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "6093", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "6222", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "6[36]9230", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "6[35]9233", length: ["9"], areaCodeLength: nil, operator: "digi", format: "all_3/3/3")
		.init(prefix: "6[36]929", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "6[36]93", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "64[68]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "659230", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "65929", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "6593", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "67", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "7038[01]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "70596", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "707", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "708[17]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "760[1-57]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "761[2-47]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "762[237]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "80[02]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "808", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "809[1579]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "884[0-4689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "91", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/3")
		.init(prefix: "920[0-5]", length: ["9"], areaCodeLength: nil, operator: "lycamobile", format: "all_3/3/3")
		.init(prefix: "92[09][6-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "921", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/3")
		.init(prefix: "9220", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/3")
		.init(prefix: "922[12]", length: ["9"], areaCodeLength: nil, operator: "meo", format: "all_3/3/3")
		.init(prefix: "922[3-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "923[04]", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "9231", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "all_3/3/3")
		.init(prefix: "9232", length: ["9"], areaCodeLength: nil, operator: "meo", format: "all_3/3/3")
		.init(prefix: "9233", length: ["9"], areaCodeLength: nil, operator: "digi", format: "all_3/3/3")
		.init(prefix: "923[5-9]", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "924", length: ["9"], areaCodeLength: nil, operator: "meo", format: "all_3/3/3")
		.init(prefix: "92[5-7]", length: ["9"], areaCodeLength: nil, operator: "meo", format: "all_3/3/3")
		.init(prefix: "928[01]", length: ["9"], areaCodeLength: nil, operator: "nowo", format: "all_3/3/3")
		.init(prefix: "928[2-46-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "9285", length: ["9"], areaCodeLength: nil, operator: "onitelecom", format: "all_3/3/3")
		.init(prefix: "929[0-4]", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "9295", length: ["9"], areaCodeLength: nil, operator: "suma-movil", format: "all_3/3/3")
		.init(prefix: "93", length: ["9"], areaCodeLength: nil, operator: "nos", format: "all_3/3/3")
		.init(prefix: "9480", length: ["9"], areaCodeLength: nil, operator: nil, format: "all_3/3/3")
		.init(prefix: "96", length: ["9"], areaCodeLength: nil, operator: "meo", format: "all_3/3/3")
	]
)

