//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_31 = RegionPhoneMetadata(
    code: 31,
    timezone: "Europe/Amsterdam",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_2/3/4", national: "#XX XXX XXXX", international: "XX XXX XXXX")
		.init(id: "fixed_3/3/3", national: "#XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "fmt_3/4-7", national: "#XXX XXXX***", international: "XXX XXXX***")
		.init(id: "mobile_1/8", national: "#X XXXXXXXX", international: "X XXXXXXXX")
		.init(id: "mobile_3/3/5", national: "#XXX XXX XXXXX", international: "XXX XXX XXXXX")
		.init(id: "pager_2/7", national: "#XX XXXXXXX", international: "XX XXXXXXX")
		.init(id: "shortcode_4", national: "XXXX", international: )
		.init(id: "shortcode_6", national: "XXXXXX", international: )
		.init(id: "uan_2/3-4", national: "XX XXX*", international: )
	],
    operators: [
		.init(id: "aspider_solutions_nederland_bv", name: "ASPIDER Solutions Nederland B.V.")
		.init(id: "kpn", name: "KPN")
		.init(id: "lancelot_telecom", name: "Lancelot")
		.init(id: "lebara", name: "Lebara")
		.init(id: "lycamobile", name: "Lycamobile")
		.init(id: "motto", name: "Motto")
		.init(id: "privatemobility", name: "Private Mobility Nederland")
		.init(id: "t-mobile", name: "T-Mobile Thuis")
		.init(id: "t_mobile", name: "T-Mobile")
		.init(id: "tele2", name: "Tele2")
		.init(id: "teleena_mvne", name: "Teleena (MVNE)")
		.init(id: "telfort", name: "Telfort")
		.init(id: "v_tell", name: "Glotell B.V (V-Tell NL)")
		.init(id: "vectone_mobile_delight_mobile", name: "Vectone Mobile/Delight Mobile")
		.init(id: "vodafone_libertel_bv", name: "Vodafone Libertel B.V.")
	],
    ranges: [
		.init(prefix: "10", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "111", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "113", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "114", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "115", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "117", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "118", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "13", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "1401[035]", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1401[16-8]", length: ["6"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1402[0346]", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1402[259]", length: ["6"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1403[03568]", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1403[124]", length: ["6"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1404[0356]", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1404[17-9]", length: ["6"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1405[0358]", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1405[124679]", length: ["6"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1407", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "1408[458]", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_2/3-4")
		.init(prefix: "15", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "161", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "162", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "164", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "165", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "166", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "167", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "168", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "172", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "174", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "180", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "181", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "182", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "183", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "184", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "186", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "187", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "20", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "222", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "223", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "224", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "226", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "227", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "228", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "229", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "23", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "24", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "251", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "252", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "255", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "26", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "294", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "297", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "299", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "30", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "313", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "314", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "315", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "316", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "317", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "318", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "320", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "321", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "33", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "341", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "342", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "343", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "344", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "345", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "346", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "347", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "348", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "35", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "36", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "38", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "40", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "411", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "412", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "413", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "416", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "418", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "43", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "45", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "46", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "475", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "478", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "481", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "485", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "486", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "487", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "488", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "492", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "493", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "495", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "497", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "499", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "50", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "511", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "512", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "513", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "514", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "515", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "516", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "517", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "518", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "519", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "521", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "522", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "523", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "524", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "525", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "527", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "528", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "529", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "53", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "541", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "543", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "544", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "545", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "546", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "547", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "548", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "55", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "561", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "562", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "566", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "570", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "571", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "572", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "573", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "575", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "577", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "578", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "58", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "591", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "592", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "593", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "594", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "595", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "596", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "597", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "598", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "599", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "61[0239]", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "61[15]", length: ["9"], areaCodeLength: nil, operator: "vodafone_libertel_bv", format: "mobile_1/8")
		.init(prefix: "6[1-3]4", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_1/8")
		.init(prefix: "61[67]", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "6[124]8", length: ["9"], areaCodeLength: nil, operator: "t-mobile", format: "mobile_1/8")
		.init(prefix: "62[023]", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "62[1579]", length: ["9"], areaCodeLength: nil, operator: "vodafone_libertel_bv", format: "mobile_1/8")
		.init(prefix: "626", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "630", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "631", length: ["9"], areaCodeLength: nil, operator: "vodafone_libertel_bv", format: "mobile_1/8")
		.init(prefix: "632", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_1/8")
		.init(prefix: "633", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "635[045]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_1/8")
		.init(prefix: "6351", length: ["9"], areaCodeLength: nil, operator: "v_tell", format: "mobile_1/8")
		.init(prefix: "6352", length: ["9"], areaCodeLength: nil, operator: "lancelot_telecom", format: "mobile_1/8")
		.init(prefix: "6353", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "635[6-9]", length: ["9"], areaCodeLength: nil, operator: "aspider_solutions_nederland_bv", format: "mobile_1/8")
		.init(prefix: "636", length: ["9"], areaCodeLength: nil, operator: "tele2", format: "mobile_1/8")
		.init(prefix: "637", length: ["9"], areaCodeLength: nil, operator: "teleena_mvne", format: "mobile_1/8")
		.init(prefix: "63[89]", length: ["9"], areaCodeLength: nil, operator: "t-mobile", format: "mobile_1/8")
		.init(prefix: "640", length: ["9"], areaCodeLength: nil, operator: "tele2", format: "mobile_1/8")
		.init(prefix: "64[1-3]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_1/8")
		.init(prefix: "64[479]", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "645", length: ["9"], areaCodeLength: nil, operator: "telfort", format: "mobile_1/8")
		.init(prefix: "646", length: ["9"], areaCodeLength: nil, operator: "vodafone_libertel_bv", format: "mobile_1/8")
		.init(prefix: "65[0245]", length: ["9"], areaCodeLength: nil, operator: "vodafone_libertel_bv", format: "mobile_1/8")
		.init(prefix: "65[137]", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "656", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_1/8")
		.init(prefix: "6580", length: ["9"], areaCodeLength: nil, operator: "privatemobility", format: "mobile_1/8")
		.init(prefix: "658[1-6]", length: ["9"], areaCodeLength: nil, operator: "lebara", format: "mobile_1/8")
		.init(prefix: "658[7-9]", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "659[0-8]", length: ["9"], areaCodeLength: nil, operator: "vectone_mobile_delight_mobile", format: "mobile_1/8")
		.init(prefix: "6599", length: ["9"], areaCodeLength: nil, operator: "motto", format: "mobile_1/8")
		.init(prefix: "66[0-46-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "pager_2/7")
		.init(prefix: "665", length: ["9"], areaCodeLength: nil, operator: nil, format: "pager_2/7")
		.init(prefix: "680", length: ["9"], areaCodeLength: nil, operator: "vodafone_libertel_bv", format: "mobile_1/8")
		.init(prefix: "681", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_1/8")
		.init(prefix: "68[23]", length: ["9"], areaCodeLength: nil, operator: "kpn", format: "mobile_1/8")
		.init(prefix: "68[457]", length: ["9"], areaCodeLength: nil, operator: "lycamobile", format: "mobile_1/8")
		.init(prefix: "686", length: ["9"], areaCodeLength: nil, operator: "lycamobile", format: "mobile_1/8")
		.init(prefix: "68[89]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_1/8")
		.init(prefix: "70", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "71", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "72", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "73", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "74", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "75", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "76", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "77", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "78", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "79", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "800", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fmt_3/4-7")
		.init(prefix: "8[478]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "85", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "90[069]", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fmt_3/4-7")
		.init(prefix: "91", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "970", length: ["11"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/5")
	]
)

