//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_47 = RegionPhoneMetadata(
    code: 47,
    prefix: "00",
    extraRegion: "SJ",
    formats: [
		.init(id: "fmt_2/2/2/2", national: "XX XX XX XX", international: "XX XX XX XX")
		.init(id: "non_geo_3/2/3", national: "XXX XX XXX", international: "XXX XX XXX")
	],
    operators: [
		.init(id: "altibox", name: "altibox")
		.init(id: "chilimobil", name: "chilimobil")
		.init(id: "com4", name: "com4")
		.init(id: "erate", name: "erate")
		.init(id: "ice", name: "ice norge")
		.init(id: "kvantel", name: "kvantel")
		.init(id: "lyca_mobile", name: "lyca mobile")
		.init(id: "netcom", name: "NetCom")
		.init(id: "nextgentel", name: "nextgentel")
		.init(id: "nkom", name: "nkom (nasjonal kommunikasjonsmyndighet)")
		.init(id: "phonect", name: "phonect")
		.init(id: "sierra_wireless", name: "sierra wireless")
		.init(id: "svea_billing_services", name: "svea billing services")
		.init(id: "telavox", name: "telavox")
		.init(id: "telenor", name: "telenor norge")
		.init(id: "telia", name: "telia")
		.init(id: "telia_telecom_solution", name: "telia telecom solution")
	],
    ranges: [
		.init(prefix: "0[2-9]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "21[0-25-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "213[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "213[2-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "214[0235-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2141[0-35-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "21414", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2144[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "21449", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "219[013-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2192", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2199[0-79]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "21998", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "22", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "23[0-579]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "236[01346-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2362[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "23629", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2365[02-57-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2365[16]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "238[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2389", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "24[03-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "241[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2419", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "2420[02-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "24201", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "242[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "3[12]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "33", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "35", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "37", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "38", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "40[01][01]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "400[23]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "400[4-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "401[23]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4014", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "401[5-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "402[0134]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "402[28]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "40[23][5-7]", length: ["8"], areaCodeLength: nil, operator: "sierra_wireless", format: "fmt_2/2/2/2")
		.init(prefix: "4029", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "403[03489]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "403[12]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "40[45]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "406[0-4]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4065", length: ["8"], areaCodeLength: nil, operator: "telia_telecom_solution", format: "fmt_2/2/2/2")
		.init(prefix: "4066", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "4067", length: ["8"], areaCodeLength: nil, operator: "nextgentel", format: "fmt_2/2/2/2")
		.init(prefix: "406[89]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "407[0-689]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4077", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "40[89][01]", length: ["8"], areaCodeLength: nil, operator: "telia_telecom_solution", format: "fmt_2/2/2/2")
		.init(prefix: "40[89]2[0-4]", length: ["8"], areaCodeLength: nil, operator: "telia_telecom_solution", format: "fmt_2/2/2/2")
		.init(prefix: "40[89]2[5-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "40[89]3", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "408[4-689]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4087", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "409[4-9]", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "410[017]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "410[23589]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "410[46]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "411[04]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "411[1-356]", length: ["8"], areaCodeLength: nil, operator: "chilimobil", format: "fmt_2/2/2/2")
		.init(prefix: "411[7-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "41[23]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "41[4-7]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "41[89]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "45[0167]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "45[24]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "453[0-5]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4536", length: ["8"], areaCodeLength: nil, operator: "nkom", format: "fmt_2/2/2/2")
		.init(prefix: "453[78]", length: ["8"], areaCodeLength: nil, operator: "erate", format: "fmt_2/2/2/2")
		.init(prefix: "4539", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "455[019]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "455[2-8]", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "4580", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "458[12589]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "458[347]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4586", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "459[05689]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "459[1347]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4592", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "460", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4610", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "461[1-6]", length: ["8"], areaCodeLength: nil, operator: "chilimobil", format: "fmt_2/2/2/2")
		.init(prefix: "461[7-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4620", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "462[124-7]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4623", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "462[89]", length: ["8"], areaCodeLength: nil, operator: "erate", format: "fmt_2/2/2/2")
		.init(prefix: "463", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "464", length: ["8"], areaCodeLength: nil, operator: "netcom", format: "fmt_2/2/2/2")
		.init(prefix: "465[04]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "465[1-3]", length: ["8"], areaCodeLength: nil, operator: "ice", format: "fmt_2/2/2/2")
		.init(prefix: "465[5-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "466[0-3]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "466[4589]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4666", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4667", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "467[045]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "467[12]", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "4673", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "467[6-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "468", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "469[0-6]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4697", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4698", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4699", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "470", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "471[0-2]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "471[3-7]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "471[89]", length: ["8"], areaCodeLength: nil, operator: "chilimobil", format: "fmt_2/2/2/2")
		.init(prefix: "472", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "473", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "47[49]0", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "474[1-3]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4744", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "474[5-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "475[01]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "475[2-9]", length: ["8"], areaCodeLength: nil, operator: "altibox", format: "fmt_2/2/2/2")
		.init(prefix: "476[0-8]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4769", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "477[0156]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "477[2-47-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "478", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "479[1-3]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "479[4-7]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "479[89]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "48[0-2]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "483[0-2]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "483[3-6]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "48[39]7", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "483[89]", length: ["8"], areaCodeLength: nil, operator: "ice", format: "fmt_2/2/2/2")
		.init(prefix: "484[03-7]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4841", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4842", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "484[89]", length: ["8"], areaCodeLength: nil, operator: "erate", format: "fmt_2/2/2/2")
		.init(prefix: "4850", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4851", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "485[2-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "4858", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "4859", length: ["8"], areaCodeLength: nil, operator: "erate", format: "fmt_2/2/2/2")
		.init(prefix: "486[0-8]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4869", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "487", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "488[0-37]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "488[45]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "488[689]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "489[0-2]", length: ["8"], areaCodeLength: nil, operator: "ice", format: "fmt_2/2/2/2")
		.init(prefix: "489[359]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "4894", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "489[68]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "5[12]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "5[356]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "57", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "61", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "62", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "6[3467]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "69", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "7[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "7[23]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "74", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "7[56]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "77", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "78", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "79", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "80[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "8100[0-6]", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "8100[7-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "8101", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "810[2-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "81[23]", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "815", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "82[09]", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "85[0-5]", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "880", length: ["8"], areaCodeLength: nil, operator: nil, format: "non_geo_3/2/3")
		.init(prefix: "90[0-25-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "903", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "904[017]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "904[2-4]", length: ["8"], areaCodeLength: nil, operator: "svea_billing_services", format: "fmt_2/2/2/2")
		.init(prefix: "904[56]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "904[89]", length: ["8"], areaCodeLength: nil, operator: "telavox", format: "fmt_2/2/2/2")
		.init(prefix: "91[049]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "91[135-8]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "912[0-3]", length: ["8"], areaCodeLength: nil, operator: "chilimobil", format: "fmt_2/2/2/2")
		.init(prefix: "9124", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "912[5-9]", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "920", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "92[15][0-7]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "92[15][89]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "92[2468]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "923[0-57]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "923[689]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "927[0-689]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9277", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "929[0-6]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "929[7-9]", length: ["8"], areaCodeLength: nil, operator: "ice", format: "fmt_2/2/2/2")
		.init(prefix: "93[02468]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "93[1357][0-689]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9317", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "93[357]7", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "9390", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9391", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "939[2-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "94[01][0-2]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "940[35]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9404", length: ["8"], areaCodeLength: nil, operator: "com4", format: "fmt_2/2/2/2")
		.init(prefix: "940[6-9]", length: ["8"], areaCodeLength: nil, operator: "ice", format: "fmt_2/2/2/2")
		.init(prefix: "941[3-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "942", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "943", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "944[01]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "944[237-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "944[4-6]", length: ["8"], areaCodeLength: nil, operator: "ice", format: "fmt_2/2/2/2")
		.init(prefix: "945[0-4]", length: ["8"], areaCodeLength: nil, operator: "telia_telecom_solution", format: "fmt_2/2/2/2")
		.init(prefix: "945[5-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "946", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "9470", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "947[1-3]", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "947[4-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "948", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "949[078]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "949[1-6]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9499", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "95[0-247-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "95[356]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9600", length: ["8"], areaCodeLength: nil, operator: "phonect", format: "fmt_2/2/2/2")
		.init(prefix: "960[149]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "960[235-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "96[125]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "96[34]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "966[0-4]", length: ["8"], areaCodeLength: nil, operator: "erate", format: "fmt_2/2/2/2")
		.init(prefix: "966[5-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "967[0-5]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "967[6-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "96[78]9", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "968[0-8]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "969[0-2]", length: ["8"], areaCodeLength: nil, operator: "erate", format: "fmt_2/2/2/2")
		.init(prefix: "9693", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9694", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "969[5-9]", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "97[015-7]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "97[24]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "973[0-4]", length: ["8"], areaCodeLength: nil, operator: "ice", format: "fmt_2/2/2/2")
		.init(prefix: "973[5-9]", length: ["8"], areaCodeLength: nil, operator: "lyca_mobile", format: "fmt_2/2/2/2")
		.init(prefix: "978", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "979[0-4]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "979[5-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "98[02468]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "981", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "983[0-6]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "9837", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "983[89]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "985[0-35-9]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9854", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "9870", length: ["8"], areaCodeLength: nil, operator: "kvantel", format: "fmt_2/2/2/2")
		.init(prefix: "987[1-589]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
		.init(prefix: "9876", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "9877", length: ["8"], areaCodeLength: nil, operator: "chilimobil", format: "fmt_2/2/2/2")
		.init(prefix: "9890", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "989[1-8]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9899", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "990[0-6]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "9907", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "990[89]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "991", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "99[2-57]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "996[0-69]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "996[78]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "998[0-4]", length: ["8"], areaCodeLength: nil, operator: "telenor", format: "fmt_2/2/2/2")
		.init(prefix: "998[5-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_2/2/2/2")
		.init(prefix: "999", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/2/2/2")
	]
)

