//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_36 = RegionPhoneMetadata(
    code: 36,
    timezone: "Europe/Budapest",
    nationalPrefix: 06,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_1/3/4", national: "(# X) XXX XXXX", international: "X XXX XXXX")
		.init(id: "fixed_2/3/3", national: "(# XX) XXX XXX", international: "XX XXX XXX")
		.init(id: "fmt_2/3/3-4", national: "# XX XXX XXX*", international: "XX XXX XXX*")
	],
    operators: [
		.init(id: "digi", name: "DIGI")
		.init(id: "magyar_telekom", name: "Magyar Telekom")
		.init(id: "mvm_net", name: "MVM Net")
		.init(id: "netfone", name: "Netfone Telecom")
		.init(id: "tarr", name: "TARR")
		.init(id: "upc", name: "UPC")
		.init(id: "vidanet", name: "Vidanet")
		.init(id: "vodafone", name: "Vodafone")
		.init(id: "yettel", name: "Yettel Hungary")
	],
    ranges: [
		.init(prefix: "1", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "20", length: ["9"], areaCodeLength: nil, operator: "yettel", format: "fmt_2/3/3-4")
		.init(prefix: "21", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "22", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "23", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "24", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "25", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "26", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "27", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "28", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "29", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "30", length: ["9"], areaCodeLength: nil, operator: "magyar_telekom", format: "fmt_2/3/3-4")
		.init(prefix: "31[014-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "31200[01]", length: ["9"], areaCodeLength: nil, operator: "netfone", format: "fmt_2/3/3-4")
		.init(prefix: "31200[2-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3120[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "312[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "313[0457-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3131[0-8]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/3-4")
		.init(prefix: "31319[0-79]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/3-4")
		.init(prefix: "313198", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3132[0-8]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/3-4")
		.init(prefix: "31329[0-2]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/3-4")
		.init(prefix: "31329[3-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3133[0-2]", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/3-4")
		.init(prefix: "31333[01]", length: ["9"], areaCodeLength: nil, operator: "vidanet", format: "fmt_2/3/3-4")
		.init(prefix: "31333[2-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3133[4-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3136[0-57-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "31366[0-57-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "313666", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/3-4")
		.init(prefix: "31700[0-4]", length: ["9"], areaCodeLength: nil, operator: "tarr", format: "fmt_2/3/3-4")
		.init(prefix: "31700[5-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3170[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "317[1-6]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3177[01]", length: ["9"], areaCodeLength: nil, operator: "upc", format: "fmt_2/3/3-4")
		.init(prefix: "3177[2-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "3178", length: ["9"], areaCodeLength: nil, operator: "upc", format: "fmt_2/3/3-4")
		.init(prefix: "31790", length: ["9"], areaCodeLength: nil, operator: "upc", format: "fmt_2/3/3-4")
		.init(prefix: "3179[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "32", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "33", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "34", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "35", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "36", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "37", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "38", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "[48]0", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "42", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "44", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "45", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "46", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "47", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "48", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "49", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "50[03-7]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "50[12]", length: ["9"], areaCodeLength: nil, operator: "digi", format: "fmt_2/3/3-4")
		.init(prefix: "50[89]", length: ["9"], areaCodeLength: nil, operator: "mvm_net", format: "fmt_2/3/3-4")
		.init(prefix: "52", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "53", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "54", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "55", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "56", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "57", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "59", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "62", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "63", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "66", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "68", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "680[29]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "69", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "70", length: ["9"], areaCodeLength: nil, operator: "vodafone", format: "fmt_2/3/3-4")
		.init(prefix: "72", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "73", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "74", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "75", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "76", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "77", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "78", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "79", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "82", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "83", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "84", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "85", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "87", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "88", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "89", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "9[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/3-4")
		.init(prefix: "92", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "93", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "94", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "95", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "96", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
		.init(prefix: "99", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3")
	]
)

