//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_852 = RegionPhoneMetadata(
    code: 852,
    timezone: "Asia/Hong_Kong",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_4/4", national: "XXXX XXXX", international: "XXXX XXXX")
		.init(id: "fmt2_3/3/3", national: "XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "fmt3_3/2/3/3", national: "XXX XX XXX XXX", international: "XXX XX XXX XXX")
		.init(id: "fmt4_3/2-5", national: "XXX XX***", international: "XXX XX***")
	],
    operators: [
		.init(id: "21vianet", name: "21Vianet")
		.init(id: "3", name: "3")
		.init(id: "china_mobile", name: "China Mobile")
		.init(id: "china_unicom", name: "China Unicom")
		.init(id: "citic", name: "CITIC")
		.init(id: "hkbn", name: "Hong Kong Broadband Network")
		.init(id: "hkt", name: "HKT")
		.init(id: "hutchison_telecom", name: "Hutchison Telecom.")
		.init(id: "lycamobile", name: "Lycamobile")
		.init(id: "multibyte", name: "Multibyte")
		.init(id: "sct", name: "South China Telecommunications")
		.init(id: "smartone", name: "SmarTone")
		.init(id: "sun_mobile", name: "Sun Mobile")
		.init(id: "webbing", name: "Webbing")
	],
    ranges: [
		.init(prefix: "21", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "22[013-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "2[3-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "300[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "30[15-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "302[047]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "3089", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "31[0-24-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "34[0-247-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "346", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "350", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "35[124-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "36[0-24-79]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "368", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "37[02]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "37[14-69]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "384[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "385", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "386[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "389", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "39[0-246-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "395", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "440", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "441", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "444[5-9]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "445", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "460[0-6]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "4607", length: ["8"], areaCodeLength: nil, operator: "multibyte", format: "fmt1_4/4")
		.init(prefix: "46[07][89]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "461[0134]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "4612", length: ["8"], areaCodeLength: nil, operator: "sun_mobile", format: "fmt1_4/4")
		.init(prefix: "461[56]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "4617", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "462[0-4]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "462[5-9]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "463", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "464[07]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "464[1-5]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "4648", length: ["8"], areaCodeLength: nil, operator: "multibyte", format: "fmt1_4/4")
		.init(prefix: "4649", length: ["8"], areaCodeLength: nil, operator: "citic", format: "fmt1_4/4")
		.init(prefix: "465[0-3]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "465[4-8]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "4659", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "466[0-4]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "467[0-7]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "468", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "469[0-8]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "4699", length: ["8"], areaCodeLength: nil, operator: "sct", format: "fmt1_4/4")
		.init(prefix: "51[02367]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "51[148]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "519", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "52[01479]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "52[26]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "523[0-3]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "5234", length: ["8"], areaCodeLength: nil, operator: "lycamobile", format: "fmt1_4/4")
		.init(prefix: "5235", length: ["8"], areaCodeLength: nil, operator: "21vianet", format: "fmt1_4/4")
		.init(prefix: "523[6-9]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "528[0-2]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "5283", length: ["8"], areaCodeLength: nil, operator: "multibyte", format: "fmt1_4/4")
		.init(prefix: "528[4-8]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "5289", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "53[01479]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "53[26]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "533", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "538", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "54[0137]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "54[2489]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "5[45]6", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "55[09]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "55[128]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "55[37]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "554[0-8]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "5549", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "56[0-24]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "56[369]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "568", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "570[0145]", length: ["8"], areaCodeLength: nil, operator: "multibyte", format: "fmt1_4/4")
		.init(prefix: "570[23]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "5706", length: ["8"], areaCodeLength: nil, operator: "hkbn", format: "fmt1_4/4")
		.init(prefix: "570[78]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "5709", length: ["8"], areaCodeLength: nil, operator: "citic", format: "fmt1_4/4")
		.init(prefix: "571[0-7]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "57[16][89]", length: ["8"], areaCodeLength: nil, operator: "lycamobile", format: "fmt1_4/4")
		.init(prefix: "572", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "573[0-6]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "574[0-4]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "574[5-8]", length: ["8"], areaCodeLength: nil, operator: "multibyte", format: "fmt1_4/4")
		.init(prefix: "5749", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "576[0-7]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "577", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "57[89]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "580[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "5812", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "581[3-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "590[0-5]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "590[67]", length: ["8"], areaCodeLength: nil, operator: "21vianet", format: "fmt1_4/4")
		.init(prefix: "590[89]", length: ["8"], areaCodeLength: nil, operator: "lycamobile", format: "fmt1_4/4")
		.init(prefix: "59[1249]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "59[38]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "595[0-8]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "59[67]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "6[01]1", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "60[235]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "60[478]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "60[69]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "61[09]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "61[2-46-8]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "6[13]5", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "6[24][07]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "62[1-3]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "624", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "62[589]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "6260", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "6261", length: ["8"], areaCodeLength: nil, operator: "webbing", format: "fmt1_4/4")
		.init(prefix: "626[3-8]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "63[07-9]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "63[134]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "632", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "636[02]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "6361", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "636[3-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "64[1249]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "64[358]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "646", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "6[59]0", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "65[1349]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "65[256]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "65[78]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "66[0259]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "66[13]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "66[47]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "666[0-3]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "668", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "67[0346]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "67[157]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "672", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "679", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "68[029]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "68[18]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "683", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "68[457]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "69[13-59]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "69[27]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "69[68]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "707[1-5]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "7076", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "708[0-4]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "710[0-38]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "711[0-3679]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "713[013]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "7169", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "719[0136]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "72[02389]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "721[18]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "727[27-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "73[0-38]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "737[0-369]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "739[2357-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "747", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "75[178]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "755[0-5]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "760[0-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "762[236-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "76[35]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "77[27]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "778[7-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "78[23689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "787[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "79[02]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "795", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "796[0-246-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "797[0-36-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "798[238]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "800", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt2_3/3/3")
		.init(prefix: "81[0-4679]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "82[0-36]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "827[0-4]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "83[034]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "83[27]0", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "8329", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "84[09]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "848[0-2]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "848[5-9]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "900[0-24-9]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fmt3_3/2/3/3")
		.init(prefix: "9003", length: ["5-8"], areaCodeLength: nil, operator: nil, format: "fmt4_3/2-5")
		.init(prefix: "901", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "90[237-9]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "90[45]", length: ["8"], areaCodeLength: nil, operator: "hutchison_telecom", format: "fmt1_4/4")
		.init(prefix: "906", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "91[0589]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "912", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "91[367]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "9[13]4", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "9[26]0", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "92[135-7]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "92[24]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "928", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "9290", length: ["8"], areaCodeLength: nil, operator: "multibyte", format: "fmt1_4/4")
		.init(prefix: "9291", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "929[3-9]", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "93[03]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "93[18]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "93[25-7]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "94[06]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "94[127-9]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "94[3-5]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "95[07]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "95[18]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "95[235]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "954", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "956", length: ["8"], areaCodeLength: nil, operator: "china_unicom", format: "fmt1_4/4")
		.init(prefix: "959[0-4]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "96[12459]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "96[37]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "96[68]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "97[045]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "97[19]", length: ["8"], areaCodeLength: nil, operator: "china_mobile", format: "fmt1_4/4")
		.init(prefix: "97[23]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "97[6-8]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "98[078]", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
		.init(prefix: "98[1-3]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "98[4-6]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "9899", length: ["8"], areaCodeLength: nil, operator: "hkt", format: "fmt1_4/4")
	]
)

