//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_51 = RegionPhoneMetadata(
    code: 51,
    timezone: "America/Lima",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_1/7", national: "(#X) XXXXXXX", international: "X XXXXXXX")
		.init(id: "fixed_2/6", national: "(#XX) XXXXXX", international: "XX XXXXXX")
		.init(id: "fixed_3/5", national: "(#XXX) XXXXX", international: "XXX XXXXX")
		.init(id: "mobile_3/3/3", national: "XXX XXX XXX", international: "XXX XXX XXX")
	],
    operators: [
		.init(id: "__americatel", name: "Americatel")
		.init(id: "__idt", name: "IDT")
		.init(id: "__nextel", name: "Nextel")
		.init(id: "claro", name: "Claro")
		.init(id: "dolphin_telecom", name: "Dolphin Telecom")
		.init(id: "entel", name: "Entel")
		.init(id: "movistar", name: "Movistar")
	],
    ranges: [
		.init(prefix: "1[0-8]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/7")
		.init(prefix: "41[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "419[0-35-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "4194", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "42[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "429[0-35-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "4294", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "43[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "44[013-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "442", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "51[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "52[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "529[0-46-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "5295", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "53[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "539[0-46-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "5395", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "54[013-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "542", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "56[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "569[0-46-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "5695", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "61[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "619[0-57-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "6196", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "62[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "629[0-57-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "6296", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "63[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "639[0-57-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "6396", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "64[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "649[0-47-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "649[56]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "65[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "659[0-57-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "6596", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "66[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "669[0-57-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "6696", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "67[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "679[0-57-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "6796", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "7173", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "72[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "729[0-689]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "7297", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "73[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "74[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "749[0-689]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "7497", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "76[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "769[0-689]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "7697", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "800", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_3/5")
		.init(prefix: "801", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_3/5")
		.init(prefix: "80[24]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_3/5")
		.init(prefix: "805", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_3/5")
		.init(prefix: "810[069]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "810[58]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "82[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "829[0-79]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "8298", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "830", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "83[1-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "839[0-79]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "8398", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "84[0-8]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "849[0-69]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "849[78]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "8600", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "86[01][6-9]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "8629", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "870[569]", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "8750", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "8760", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/6")
		.init(prefix: "90[01]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "90[236-8]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "90[45]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "909", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "91[03-8]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "911", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "912", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "919[01]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9192[0-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9192[89]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "919[3-79]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "9198", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "920", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "92[157-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "92[2-4]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "926[0-245]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9263[0-5]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9263[67]", length: ["9"], areaCodeLength: nil, operator: "dolphin_telecom", format: "mobile_3/3/3")
		.init(prefix: "9263[89]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "926[6-9]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "93[015]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "932[0-6]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9327[01]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9327[2-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "932[89]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "93[346]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "937[0-2]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9373[0-3]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9373[4-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "937[4-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "93[89]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "940", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "941[0-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "941[89]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "942[014-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "942[237]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "943[0-24689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "943[35]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9437[0-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9437[89]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "944[0-357]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "944[4689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "945", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "946[0-5]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "946[67]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9468[0-3]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9468[4-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9469", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "947[04-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "947[1-3]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9477", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9480[0-4]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9480[5-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "948[14-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "948[237]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9490[0-6]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9490[7-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "949[1-3]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "949[4-68]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9497[0-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9497[89]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9499[0-79]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "94998[013-6]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "949982[01]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "949982[2-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "949987[0-4]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "949987[5-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "94998[89]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "95[01][04-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "95[023]10", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9501[1-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "950[237]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "951[1-37]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "952[025689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9521[1-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "952[34]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9527[0-2]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9527[3-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "953[02-478]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9531[1-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9535[017-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9535[2-6]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "953[69]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "954[04-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "954[17]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "954[23]0", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "954[23][1-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "955[0-4]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "95550", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9555[1-9]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "955[689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9557", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "956[014-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "956[237]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "957[0-37]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "957[4-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "958[09][0-4]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "958[09][5-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "958[1-37]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9584[0-6]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9584[7-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "958[568]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "959[04-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "959[137]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9592[0-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9592[89]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9600[0-3]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "9600[4-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "960[1-9]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "961[01569]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "961[2-478]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "962[014-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "962[237]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "963[0-478]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9635[0-4]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9635[5-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9636", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9639[0-589]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9639[67]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "964[04-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "964[1-3]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "965[0689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "965[1-57]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "966[0-25689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "966[37]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9664[0-8]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "96649", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "967[0-578]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9676[0-47]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9676[5689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9679[0189]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9679[2-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "968[014-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "96820", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "96821", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9682[2-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9683[0-5]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9683[6-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9687", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "969[0-24-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "969[37]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9700", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "970[13-8]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9702", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9709[0-8]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "97099", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "97[15]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "972[01]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "972[2-47]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9725[0-2]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9725[3-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "972[689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "973[0-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "973[89]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "974[09]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "97410", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9741[1-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "974[2-7]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9748[0-6]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9748[7-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "976[016-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "976[23]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "976[45]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "977[01]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "97720", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9772[1-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "977[3-9]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "978[014589]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "97820", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "97821", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9782[2-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "978[367]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "979[0-24-689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "979[37]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9800[0-2]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "9800[3-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "980[1-3]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "980[4-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "981[0-5]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "981[6-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "982[0-578]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9826[018]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "9826[2-79]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "9829[0-79]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "98298", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "983[0-378]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "983[45]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "983[69]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "984[05689]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "984[1-47]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "98[58]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "98[679]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "99[0569]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "99[1-37]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "994[0-2]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
		.init(prefix: "994[36-9]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/3/3")
		.init(prefix: "994[45]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "998[04-9]", length: ["9"], areaCodeLength: nil, operator: "movistar", format: "mobile_3/3/3")
		.init(prefix: "998[1-3]", length: ["9"], areaCodeLength: nil, operator: "entel", format: "mobile_3/3/3")
	]
)

