//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_996 = RegionPhoneMetadata(
    code: 996,
    timezone: "Asia/Bishkek",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_4/5", national: "#XXXX XXXXX", international: "XXXX XXXXX")
		.init(id: "fmt_3/3/3", national: "#XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "toll_3/3/1/2-3", national: "#XXX XXX X XX*", international: "XXX XXX X XX*")
	],
    operators: [
		.init(id: "aktel", name: "Aktel")
		.init(id: "alfa_telecom", name: "ALFA Telecom")
		.init(id: "katel", name: "Katel")
		.init(id: "nur_telecom", name: "Nur Telecom")
		.init(id: "sky_mobile", name: "Sky mobile")
		.init(id: "smart_connect", name: "Smart Connect")
		.init(id: "sotel", name: "Sotel")
		.init(id: "winline", name: "Winline")
	],
    ranges: [
		.init(prefix: "20[0-35]", length: ["9"], areaCodeLength: nil, operator: "aktel", format: "fmt_3/3/3")
		.init(prefix: "22", length: ["9"], areaCodeLength: nil, operator: "sky_mobile", format: "fmt_3/3/3")
		.init(prefix: "312[0-46-8]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "3125[0-79]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "31258", length: ["9"], areaCodeLength: nil, operator: "sky_mobile", format: "fmt_3/3/3")
		.init(prefix: "3129[0-689]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "31297[0-24-9]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "312973", length: ["9"], areaCodeLength: nil, operator: "nur_telecom", format: "fmt_3/3/3")
		.init(prefix: "3131", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3132", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3133", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3134", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3135", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3136", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3137", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3138", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3139", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3147", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "315", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "316", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3222", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3230", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3231", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3232", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3233", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3234", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3237", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3239", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "326[0-7]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3422", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3456", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3457", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3458", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3459", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3[46]6", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3522", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3534", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3535", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3536", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3537", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3559", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "356", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3622", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3653", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3655", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3656", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3657", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3722", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3734", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3736", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3738", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3741", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3742", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3743", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3744", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3745", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3746", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3747", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3748", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3749", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3759", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "37[67]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3922", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3941", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3942", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3943", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3944", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3945", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3946", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3947", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "3948", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "396", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/5")
		.init(prefix: "50[0-57-9]", length: ["9"], areaCodeLength: nil, operator: "nur_telecom", format: "fmt_3/3/3")
		.init(prefix: "506", length: ["9"], areaCodeLength: nil, operator: "winline", format: "fmt_3/3/3")
		.init(prefix: "51", length: ["9"], areaCodeLength: nil, operator: "katel", format: "fmt_3/3/3")
		.init(prefix: "52", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "54", length: ["9"], areaCodeLength: nil, operator: "aktel", format: "fmt_3/3/3")
		.init(prefix: "55", length: ["9"], areaCodeLength: nil, operator: "alfa_telecom", format: "fmt_3/3/3")
		.init(prefix: "56", length: ["9"], areaCodeLength: nil, operator: "winline", format: "fmt_3/3/3")
		.init(prefix: "57", length: ["9"], areaCodeLength: nil, operator: "sotel", format: "fmt_3/3/3")
		.init(prefix: "600", length: ["9"], areaCodeLength: nil, operator: "sky_mobile", format: "fmt_3/3/3")
		.init(prefix: "609", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "612", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "62[2-4]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/3/3")
		.init(prefix: "70", length: ["9"], areaCodeLength: nil, operator: "nur_telecom", format: "fmt_3/3/3")
		.init(prefix: "755", length: ["9"], areaCodeLength: nil, operator: "alfa_telecom", format: "fmt_3/3/3")
		.init(prefix: "77", length: ["9"], areaCodeLength: nil, operator: "sky_mobile", format: "fmt_3/3/3")
		.init(prefix: "800", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "toll_3/3/1/2-3")
		.init(prefix: "88[08]", length: ["9"], areaCodeLength: nil, operator: "alfa_telecom", format: "fmt_3/3/3")
		.init(prefix: "912", length: ["9"], areaCodeLength: nil, operator: "smart_connect", format: "fmt_3/3/3")
		.init(prefix: "99[05]", length: ["9"], areaCodeLength: nil, operator: "alfa_telecom", format: "fmt_3/3/3")
		.init(prefix: "996", length: ["9"], areaCodeLength: nil, operator: "sky_mobile", format: "fmt_3/3/3")
		.init(prefix: "99[7-9]", length: ["9"], areaCodeLength: nil, operator: "alfa_telecom", format: "fmt_3/3/3")
	]
)

