//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_372 = RegionPhoneMetadata(
    code: 372,
    timezone: "Europe/Bucharest",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "all_3/4", national: "XXX XXXX", international: "XXX XXXX")
		.init(id: "mobile_varcost_4/3-4", national: "XXXX XXX*", international: "XXXX XXX*")
		.init(id: "personal_2/2/4", national: "XX XX XXXX", international: "XX XX XXXX")
		.init(id: "tollfree_4/3/3", national: "XXXX XXX XXX", international: "XXXX XXX XXX")
	],
    operators: [
		.init(id: "elisa", name: "Elisa")
		.init(id: "tele_2", name: "Tele 2")
		.init(id: "telia_eesti", name: "Telia Eesti AS")
	],
    ranges: [
		.init(prefix: "32", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "33", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "35", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "38", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "39", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "40", length: ["8"], areaCodeLength: nil, operator: nil, format: "mobile_varcost_4/3-4")
		.init(prefix: "43", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "44", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "45", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "46", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "47", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "48", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "5[02]", length: ["7"], areaCodeLength: nil, operator: "telia_eesti", format: "all_3/4")
		.init(prefix: "5[02]", length: ["8"], areaCodeLength: nil, operator: nil, format: "mobile_varcost_4/3-4")
		.init(prefix: "51[0-8]", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "51[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "mobile_varcost_4/3-4")
		.init(prefix: "519", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "5195", length: ["7"], areaCodeLength: nil, operator: "telia_eesti", format: "all_3/4")
		.init(prefix: "53[0346-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "53[125]", length: ["8"], areaCodeLength: nil, operator: nil, format: "mobile_varcost_4/3-4")
		.init(prefix: "54[0-47-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "545", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "546[0457-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "546[12]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "5463[0-47-9]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "5463[56]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "5466[0-36]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "5466[457-9]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "55", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "55[0-478]", length: ["7"], areaCodeLength: nil, operator: "tele_2", format: "all_3/4")
		.init(prefix: "56", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "564[0-4]", length: ["7"], areaCodeLength: nil, operator: "elisa", format: "all_3/4")
		.init(prefix: "565[1-589]", length: ["7"], areaCodeLength: nil, operator: "elisa", format: "all_3/4")
		.init(prefix: "57", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "58[0-8]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "5890", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "589[1-9]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "59[02-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "591[0135-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "5912[01]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "5912[2-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "59140", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "59141[0-3]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "59141[4-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "5914[235-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "59144[0-3]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "59144[4-9]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "6", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "70[0-2]", length: ["8"], areaCodeLength: nil, operator: nil, format: "personal_2/2/4")
		.init(prefix: "7[12]", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "7[3-5]", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "76", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "77", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "78", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "79", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "8000", length: ["10"], areaCodeLength: nil, operator: nil, format: "tollfree_4/3/3")
		.init(prefix: "8001", length: ["8"], areaCodeLength: nil, operator: nil, format: "mobile_varcost_4/3-4")
		.init(prefix: "800[2-9]", length: ["7"], areaCodeLength: nil, operator: nil, format: "mobile_varcost_4/3-4")
		.init(prefix: "810000", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "8100[178]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "810[3-9]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "8110[236]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "8111", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "812[0-2459]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "8123", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "81[3-79]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "820000", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "82019", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "820[27]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "8203", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "820[46]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "8205[0-5]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "8205[6-9]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "821[0-5]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "821[6-8]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "8219[0-8]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "82199", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "82[24-6]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "823[5-9]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "827[0-3]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "827[4-79]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "8278[13-9]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "8282", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "828[34]", length: ["8"], areaCodeLength: nil, operator: "elisa", format: "mobile_varcost_4/3-4")
		.init(prefix: "828[56]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "8287[01]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "83", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "84[0-46-9]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "845[02-9]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "8451[0-2]", length: ["8"], areaCodeLength: nil, operator: "telia_eesti", format: "mobile_varcost_4/3-4")
		.init(prefix: "8451[3-9]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "mobile_varcost_4/3-4")
		.init(prefix: "88", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "89", length: ["8"], areaCodeLength: nil, operator: nil, format: "mobile_varcost_4/3-4")
		.init(prefix: "900", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
		.init(prefix: "901", length: ["7"], areaCodeLength: nil, operator: nil, format: "all_3/4")
	]
)

