//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_595 = RegionPhoneMetadata(
    code: 595,
    timezone: "America/Asuncion",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_2/3/3-4", national: "(#XX) XXX XXX*", international: "XX XXX XXX*")
		.init(id: "fixed_2/5", national: "(#XX) XXXXX", international: "XX XXXXX")
		.init(id: "fixed_3/3/3", national: "#XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "fixed_3/4-5", national: "(#XXX) XXXX*", international: "XXX XXXX*")
		.init(id: "mobile_3/6", national: "#XXX XXXXXX", international: "XXX XXXXXX")
		.init(id: "tollfree_3/3/4", national: "XXXX XXX XXXX", international: "XXXX XXX XXXX")
		.init(id: "uan_3/3-6", national: "#XXX XXX***", international: "XXX XXX***")
		.init(id: "voip_2/3/4", national: "XX XXX XXXX", international: "XX XXX XXXX")
	],
    operators: [
		.init(id: "claro", name: "Claro")
		.init(id: "personal", name: "Personal")
		.init(id: "tigo", name: "Tigo")
		.init(id: "vox", name: "VOX")
	],
    ranges: [
		.init(prefix: "[2-9]0", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "uan_3/3-6")
		.init(prefix: "21", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "21", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "22[4-68]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "22[4-68]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "24", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "25", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "26", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "271", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "271", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "275", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "275", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "28", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "291", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "291", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "292", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "292", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "293", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "293", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "294", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "294", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "295", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "295", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "318", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "318", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "32", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "32", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "33[167]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "33[167]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "34[237]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "34[237]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "345", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "345", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "351", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "351", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "36", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "37", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "38", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "38", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "39", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "39", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "41", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "41", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "42", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "42", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "43[12]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "43[12]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "44", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "44", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "451", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "451", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "453", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "453", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "46", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "46", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "47", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "47", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "48", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "48", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "49[1-47]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "49[1-47]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "5[1-4]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "5[1-4]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "550", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "550", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "552", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "552", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "553", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "553", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "554", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "554", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "61", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "61", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "631", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "631", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "632", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "632", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "633", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "633", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "644", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "644", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "671", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "671", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "672", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "672", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "673", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "673", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "674", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "674", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "675", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "676", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "676", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "677", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "677", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "678", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "678", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "71", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "71", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "72", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "72", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "73", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "73", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "740", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "740", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "741", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "741", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "742", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "742", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "743", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "743", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "744", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "744", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "75", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "761", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "761", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "762", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "762", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "763", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "763", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "764", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "764", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "7[67]5", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "7[67]5", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "767", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "767", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "768", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "768", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "780", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "780", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "781", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "781", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "782", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "782", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "783", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "783", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "784", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "784", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "785", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "785", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "78[68]", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "78[68]", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "787", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "787", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "81", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "81", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "82", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "82", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "83", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "83", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "858", length: ["8"], areaCodeLength: 3, operator: nil, format: "fixed_3/4-5")
		.init(prefix: "858", length: ["9"], areaCodeLength: 3, operator: nil, format: "fixed_3/3/3")
		.init(prefix: "86", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5")
		.init(prefix: "86", length: ["8", "9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/3-4")
		.init(prefix: "8700[0-4]", length: ["9"], areaCodeLength: nil, operator: nil, format: "voip_2/3/4")
		.init(prefix: "951", length: ["9"], areaCodeLength: nil, operator: "vox", format: "mobile_3/6")
		.init(prefix: "96[129]", length: ["9"], areaCodeLength: nil, operator: "vox", format: "mobile_3/6")
		.init(prefix: "97[1-6]", length: ["9"], areaCodeLength: nil, operator: "personal", format: "mobile_3/6")
		.init(prefix: "9800", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "9800", length: ["11"], areaCodeLength: nil, operator: nil, format: "tollfree_3/3/4")
		.init(prefix: "98[1-6]", length: ["9"], areaCodeLength: nil, operator: "tigo", format: "mobile_3/6")
		.init(prefix: "99[1-5]", length: ["9"], areaCodeLength: nil, operator: "claro", format: "mobile_3/6")
	]
)

