//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_62 = RegionPhoneMetadata(
    code: 62,
    nationalPrefix: 0,
    extraRegion: [],
    formats: [
		.init(id: "fixed_2/5-9", national: "(#XX) XXXXX****", international: "XX XXXXX****")
		.init(id: "fixed_3/5-8", national: "(#XXX) XXXXX***", international: "XXX XXXXX***")
		.init(id: "mobile_3/3-4/3", national: "#XXX-XXX*-XXX", international: "XXX-XXX*-XXX")
		.init(id: "mobile_3/4/4-5", national: "#XXX-XXXX-XXXX*", international: "XXX-XXXX-XXXX*")
		.init(id: "sharedcost_3/3/4", national: "#XXX XXX XXXX", international: "XXX XXX XXXX")
		.init(id: "tollfree_2/4/3/4", national: "XX XXXX XXX XXXX", international: )
		.init(id: "tollfree_3/3/3/3", national: "XXX XXX XXX XXX", international: )
		.init(id: "tollfree_3/5-7", national: "#XXX XXXXX**", international: "XXX XXXXX**")
		.init(id: "tollfree_3/6-8", national: "#XXX XXXXXX**", international: "XXX XXXXXX**")
		.init(id: "uan_1/3/3", national: "X XXX XXX", international: "X XXX XXX")
		.init(id: "varcost_3/1/3/3", national: "#XXX X XXX XXX", international: "XXX X XXX XXX")
	],
    operators: [
		.init(id: "axis", name: "AXIS")
		.init(id: "indosat", name: "Indosat Ooredoo Hutchison")
		.init(id: "smartfren", name: "Smartfren")
		.init(id: "telkomsel", name: "Telkomsel")
		.init(id: "xl", name: "XL")
	],
    ranges: [
		.init(prefix: "001803", length: ["12"], areaCodeLength: nil, operator: nil, format: "tollfree_3/3/3/3")
		.init(prefix: "001803", length: ["13"], areaCodeLength: nil, operator: nil, format: "tollfree_2/4/3/4")
		.init(prefix: "007803", length: ["13"], areaCodeLength: nil, operator: nil, format: "tollfree_2/4/3/4")
		.init(prefix: "1500", length: ["7"], areaCodeLength: nil, operator: nil, format: "uan_1/3/3")
		.init(prefix: "177", length: ["9-11"], areaCodeLength: nil, operator: nil, format: "tollfree_3/6-8")
		.init(prefix: "21", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "2114", length: ["7"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "21500", length: ["8"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "22", length: ["8-10"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "231", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "232", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "233", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "234", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "24", length: ["9", "10"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "251", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "252", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "253", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "254", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "260", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "261", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "262", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "263", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "264", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "265", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "266", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "267", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "2[68]8", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "271", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "272", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "273", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "274", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "275", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "276", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "280", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "281", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "282", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "283", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "284", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "285", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "286", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "287", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "289", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "291", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "292", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "293", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "294", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "295", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "296", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "297", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "298", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "31", length: ["7-10"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "321", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "322", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "323", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "324", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "325", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "326", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "327", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "328", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "33[16]", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "332", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "333", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "334", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "335", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "338", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "341", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "342", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "343", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "351", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "352", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "353", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "354", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "355", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "356", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "357", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "358", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "361", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "362", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "363", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "365", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "366", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "368", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "370", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "371", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "372", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "373", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "374", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "376", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "379", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "380", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "381", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "382", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "383", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "384", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "385", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "386", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "387", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "388", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "389", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "401", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "402", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "403", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "404", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "405", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "408", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "409", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "410", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "411", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "413", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "414", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "417", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "418", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "419", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "420", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "421", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "422", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "423", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "426", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "427", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "428", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "430", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "431", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "432", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "434", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "435", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "436", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "438", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "443", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "451", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "452", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "453", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "457", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "458", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "461", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "462", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "463", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "464", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "465", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "471", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "473", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "474", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "481", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "482", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "484", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "485", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "511", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "512", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "513", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "51[59]", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "516", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "517", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "518", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "522", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "525", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "526", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "527", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "528", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "531", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "532", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "534", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "535", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "536", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "537", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "538", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "539", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "541", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "542", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "543", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "545", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "548", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "549", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "551", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "552", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "553", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "554", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "556", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "561", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "562", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "563", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "564", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "565", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "566", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "567", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "568", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "61[0-8]", length: ["7-10"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "619", length: ["7-11"], areaCodeLength: 2, operator: nil, format: "fixed_2/5-9")
		.init(prefix: "620", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "621", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "622", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "623", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "624", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "625", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "626", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "627", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "628", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "629", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "631", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "632", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "633", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "634", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "635", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "636", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "639", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "641", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "642", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "643", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "644", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "645", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "646", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "650", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "651", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "652", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "653", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "654", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "655", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "656", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "657", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "658", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "659", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "702", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "711", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "712", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "713", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "714", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "715", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "716", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "717", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "718", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "719", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "721", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "722", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "723", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "724", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "725", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "726", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "727", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "728", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "729", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "730", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "731", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "732", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "733", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "734", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "735", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "736", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "737", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "738", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "739", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "741", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "742", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "743", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "744", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "745", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "746", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "747", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "748", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "751", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "752", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "753", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "754", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "755", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "756", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "757", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "75[89]", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "760", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "761", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "762", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "763", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "764", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "765", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "766", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "767", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "768", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "769", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "770", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "771", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "772", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "773", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "776", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "777", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "778", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "779", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "800", length: ["8-10"], areaCodeLength: nil, operator: nil, format: "tollfree_3/5-7")
		.init(prefix: "804", length: ["10"], areaCodeLength: nil, operator: nil, format: "sharedcost_3/3/4")
		.init(prefix: "8071", length: ["10"], areaCodeLength: nil, operator: nil, format: "varcost_3/1/3/3")
		.init(prefix: "809", length: ["10"], areaCodeLength: nil, operator: nil, format: "varcost_3/1/3/3")
		.init(prefix: "810", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "810", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "811", length: ["9", "10"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/3-4/3")
		.init(prefix: "811", length: ["11", "12"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/4/4-5")
		.init(prefix: "81[23]", length: ["9", "10"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/3-4/3")
		.init(prefix: "81[23]", length: ["11", "12"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/4/4-5")
		.init(prefix: "81[4-6]", length: ["9", "10"], areaCodeLength: nil, operator: "indosat", format: "mobile_3/3-4/3")
		.init(prefix: "81[4-6]", length: ["11", "12"], areaCodeLength: nil, operator: "indosat", format: "mobile_3/4/4-5")
		.init(prefix: "817", length: ["9", "10"], areaCodeLength: nil, operator: "xl", format: "mobile_3/3-4/3")
		.init(prefix: "817", length: ["11", "12"], areaCodeLength: nil, operator: "xl", format: "mobile_3/4/4-5")
		.init(prefix: "81[89]", length: ["9", "10"], areaCodeLength: nil, operator: "xl", format: "mobile_3/3-4/3")
		.init(prefix: "81[89]", length: ["11", "12"], areaCodeLength: nil, operator: "xl", format: "mobile_3/4/4-5")
		.init(prefix: "82[05-8]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "82[05-8]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "82[1-3]", length: ["9", "10"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/3-4/3")
		.init(prefix: "82[1-3]", length: ["11", "12"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/4/4-5")
		.init(prefix: "8[23][49]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "8[23][49]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "83[05-7]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "83[05-7]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "83[13]", length: ["9", "10"], areaCodeLength: nil, operator: "axis", format: "mobile_3/3-4/3")
		.init(prefix: "83[13]", length: ["11", "12"], areaCodeLength: nil, operator: "axis", format: "mobile_3/4/4-5")
		.init(prefix: "83[28]", length: ["9", "10"], areaCodeLength: nil, operator: "axis", format: "mobile_3/3-4/3")
		.init(prefix: "83[28]", length: ["11", "12"], areaCodeLength: nil, operator: "axis", format: "mobile_3/4/4-5")
		.init(prefix: "85[04]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "85[04]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "85[12]", length: ["9", "10"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/3-4/3")
		.init(prefix: "85[12]", length: ["11", "12"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/4/4-5")
		.init(prefix: "853", length: ["9", "10"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/3-4/3")
		.init(prefix: "853", length: ["11", "12"], areaCodeLength: nil, operator: "telkomsel", format: "mobile_3/4/4-5")
		.init(prefix: "85[5-8]", length: ["9", "10"], areaCodeLength: nil, operator: "indosat", format: "mobile_3/3-4/3")
		.init(prefix: "85[5-8]", length: ["11", "12"], areaCodeLength: nil, operator: "indosat", format: "mobile_3/4/4-5")
		.init(prefix: "859", length: ["9", "10"], areaCodeLength: nil, operator: "xl", format: "mobile_3/3-4/3")
		.init(prefix: "859", length: ["11", "12"], areaCodeLength: nil, operator: "xl", format: "mobile_3/4/4-5")
		.init(prefix: "86[0-79]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "86[0-79]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "868", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "868", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "87[0-5]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "87[0-5]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "876", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "876", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "87[7-9]", length: ["9", "10"], areaCodeLength: nil, operator: "xl", format: "mobile_3/3-4/3")
		.init(prefix: "87[7-9]", length: ["11", "12"], areaCodeLength: nil, operator: "xl", format: "mobile_3/4/4-5")
		.init(prefix: "88[04-6]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "88[04-6]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "88[1-389]", length: ["9", "10"], areaCodeLength: nil, operator: "smartfren", format: "mobile_3/3-4/3")
		.init(prefix: "88[1-389]", length: ["11", "12"], areaCodeLength: nil, operator: "smartfren", format: "mobile_3/4/4-5")
		.init(prefix: "887", length: ["9", "10"], areaCodeLength: nil, operator: "smartfren", format: "mobile_3/3-4/3")
		.init(prefix: "887", length: ["11", "12"], areaCodeLength: nil, operator: "smartfren", format: "mobile_3/4/4-5")
		.init(prefix: "89[0-4]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3-4/3")
		.init(prefix: "89[0-4]", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "mobile_3/4/4-5")
		.init(prefix: "89[5-9]", length: ["9", "10"], areaCodeLength: nil, operator: "indosat", format: "mobile_3/3-4/3")
		.init(prefix: "89[5-9]", length: ["11", "12"], areaCodeLength: nil, operator: "indosat", format: "mobile_3/4/4-5")
		.init(prefix: "901", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "902", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "910", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "911", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "913", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "914", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "915", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "916", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "917", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "918", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "920", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "921", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "922", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "923", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "924", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "927", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "929", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "951", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "952", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "955", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "956", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "957", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "958", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "962", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "963", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "966", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "967", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "969", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "971", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "975", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "979", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "980", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "981", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "983", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "984", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
		.init(prefix: "986", length: ["8-11"], areaCodeLength: 3, operator: nil, format: "fixed_3/5-8")
	]
)

