//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_48 = RegionPhoneMetadata(
    code: 48,
    timezone: "Europe/Warsaw",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_2/2/3", national: "XX XX XXX", international: "XX XX XXX")
		.init(id: "fixed_2/3/2/2", national: "XX XXX XX XX", international: "XX XXX XX XX")
		.init(id: "mobile_3/3/3", national: "XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "pager_3/2/2-3", national: "XXX XX XX*", international: "XXX XX XX*")
		.init(id: "shortcode_3/3", national: "XXX XXX", international: "XXX XXX")
		.init(id: "shortcode_5", national: "XXXXX", international: "XXXXX")
		.init(id: "toll_free_3/3/3-4", national: "XXX XXX XXX*", international: "XXX XXX XXX*")
	],
    operators: [
		.init(id: "agile_telecom", name: "AGILE TELECOM POLAND")
		.init(id: "amd_telecom", name: "AMD Telecom S.A.")
		.init(id: "bsg_estonia_ou", name: "BSG ESTONIA OU")
		.init(id: "caritas", name: "CARITAS")
		.init(id: "compatel_limited", name: "Compatel Limited")
		.init(id: "ez_mobile", name: "EZ PHONE MOBILE")
		.init(id: "im_consulting", name: "IM Consulting Izabela")
		.init(id: "interactive_digital_media", name: "Interactive Digital Media GmbH")
		.init(id: "jmdi", name: "JMDI")
		.init(id: "lancelot", name: "Lancelot Telecom")
		.init(id: "messagebird", name: "Messagebird B.V.")
		.init(id: "mobiledata", name: "Mobiledata Sp. z o.o.")
		.init(id: "mobiweb_telecom", name: "MobiWeb Telecom Limited")
		.init(id: "move_telecom", name: "Move Telecom S.A.")
		.init(id: "nimbusfive_gmbh", name: "NIMBUSFIVE GmbH")
		.init(id: "orange", name: "Orange")
		.init(id: "pkp_polskie_linie", name: "PKP Polskie Linie Kolejowe S.A.")
		.init(id: "play", name: "Play")
		.init(id: "plus", name: "Plus")
		.init(id: "polska", name: "Polska Spoka Gazownictwa Sp")
		.init(id: "sia_netbalt", name: "SIA NetBalt")
		.init(id: "sia_ntel_solutions", name: "SIA Ntel Solutions")
		.init(id: "smshighway", name: "SMSHIGHWAY LIMITED")
		.init(id: "softelnet", name: "Softelnet S.A. Sp. k.")
		.init(id: "t_mobile", name: "T-Mobile")
		.init(id: "telco_leaders", name: "TELCO LEADERS LTD")
		.init(id: "telenabler", name: "TELENABLER")
		.init(id: "telestrada", name: "TELESTRADA S.A.")
		.init(id: "twilio", name: "Twilio Ireland Limited")
		.init(id: "upc", name: "UPC Polska")
		.init(id: "voxbone", name: "VOXBONE SA")
	],
    ranges: [
		.init(prefix: "12", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "1219", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "13", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "1319", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "14", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "1419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "15", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "1519", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "16", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "1619", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "17", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "1719", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "18", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "1819", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "20", length: ["6"], areaCodeLength: nil, operator: nil, format: "shortcode_3/3")
		.init(prefix: "2111", length: ["9"], areaCodeLength: nil, operator: "polska", format: "mobile_3/3/3")
		.init(prefix: "2113[1-5]", length: ["9"], areaCodeLength: nil, operator: "polska", format: "mobile_3/3/3")
		.init(prefix: "211[45]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "212", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "22", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2219", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "23", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2319", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "24", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "25", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2519", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "26", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2619", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "29", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2919", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "32", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "3219", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "33", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "3319", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "34", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "3419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "39", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "41", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "4119", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "42", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "4219", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "43", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "4319", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "44", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "4419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "450", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "45[1-35-8]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "454", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "459[03]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "4591[0-4]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "45915", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "4591[6-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "459[25]0", length: ["9"], areaCodeLength: nil, operator: "sia_ntel_solutions", format: "mobile_3/3/3")
		.init(prefix: "4592[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "4594[02-49]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "4594[15-8]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "4595[1-6]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "45957", length: ["9"], areaCodeLength: nil, operator: "bsg_estonia_ou", format: "mobile_3/3/3")
		.init(prefix: "4595[89]", length: ["9"], areaCodeLength: nil, operator: "telestrada", format: "mobile_3/3/3")
		.init(prefix: "459[679]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "4598", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "46", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "4619", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "47", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "48", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "4819", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "5[01]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "52", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "5219", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "53[013-57]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "53[289]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "536[0-57-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "5366", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "54", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "5419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "55", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "5519", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "56", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "5619", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "57[04-8]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "57[12]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "573[0-49]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "57350", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "5735[1-5]", length: ["9"], areaCodeLength: nil, operator: "upc", format: "mobile_3/3/3")
		.init(prefix: "5735[689]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "57357", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "573[6-8]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "579[0689]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "579[1-3]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "5794[03-5]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "57941", length: ["9"], areaCodeLength: nil, operator: "messagebird", format: "mobile_3/3/3")
		.init(prefix: "57942", length: ["9"], areaCodeLength: nil, operator: "sia_netbalt", format: "mobile_3/3/3")
		.init(prefix: "5794[679]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "57948", length: ["9"], areaCodeLength: nil, operator: "sia_ntel_solutions", format: "mobile_3/3/3")
		.init(prefix: "57950", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "5795[124-79]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "57953", length: ["9"], areaCodeLength: nil, operator: "sia_netbalt", format: "mobile_3/3/3")
		.init(prefix: "57958", length: ["9"], areaCodeLength: nil, operator: "nimbusfive_gmbh", format: "mobile_3/3/3")
		.init(prefix: "57970", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "5797[1-5]", length: ["9"], areaCodeLength: nil, operator: "upc", format: "mobile_3/3/3")
		.init(prefix: "57976", length: ["9"], areaCodeLength: nil, operator: "telenabler", format: "mobile_3/3/3")
		.init(prefix: "57977", length: ["9"], areaCodeLength: nil, operator: "im_consulting", format: "mobile_3/3/3")
		.init(prefix: "5797[89]", length: ["9"], areaCodeLength: nil, operator: "ez_mobile", format: "mobile_3/3/3")
		.init(prefix: "58", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "5819", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "59", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "5919", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "60[02468]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "6[06][13579]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "61", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "6119", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "62", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "6219", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "63", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "6319", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "64", length: ["6"], areaCodeLength: nil, operator: nil, format: "shortcode_3/3")
		.init(prefix: "64", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "pager_3/2/2-3")
		.init(prefix: "64", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "65", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "6519", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "66[0248]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "666[0-57-9]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "6666", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "67", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "6719", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "68", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "6819", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "690[07-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "690[1-6]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "69[1357]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "69[2468]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "6990[02-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "69901", length: ["9"], areaCodeLength: nil, operator: "amd_telecom", format: "mobile_3/3/3")
		.init(prefix: "699[1349]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "6992[013-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "69922", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "69950", length: ["9"], areaCodeLength: nil, operator: "amd_telecom", format: "mobile_3/3/3")
		.init(prefix: "6995[1-5]", length: ["9"], areaCodeLength: nil, operator: "mobiledata", format: "mobile_3/3/3")
		.init(prefix: "69956", length: ["9"], areaCodeLength: nil, operator: "twilio", format: "mobile_3/3/3")
		.init(prefix: "69957", length: ["9"], areaCodeLength: nil, operator: "softelnet", format: "mobile_3/3/3")
		.init(prefix: "69958", length: ["9"], areaCodeLength: nil, operator: "im_consulting", format: "mobile_3/3/3")
		.init(prefix: "69959", length: ["9"], areaCodeLength: nil, operator: "move_telecom", format: "mobile_3/3/3")
		.init(prefix: "69960", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "6996[1-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "6997[09]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "6997[1-35-7]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "69974", length: ["9"], areaCodeLength: nil, operator: "compatel_limited", format: "mobile_3/3/3")
		.init(prefix: "69978", length: ["9"], areaCodeLength: nil, operator: "voxbone", format: "mobile_3/3/3")
		.init(prefix: "6998", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "70[01346-8]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "71", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "7119", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "720[0-79]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7208", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "72[1-6]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "727[04-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7271", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "727[23]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "7280", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "728[1-9]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "729[01]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "729[2-6]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "72970", length: ["9"], areaCodeLength: nil, operator: "amd_telecom", format: "mobile_3/3/3")
		.init(prefix: "7297[16]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "72972", length: ["9"], areaCodeLength: nil, operator: "compatel_limited", format: "mobile_3/3/3")
		.init(prefix: "7297[3489]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "72975", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "72977", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7298[03-5]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7298[12]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "7298[6-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "72990", length: ["9"], areaCodeLength: nil, operator: "telco_leaders", format: "mobile_3/3/3")
		.init(prefix: "7299[1-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "73[0-3]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "73[45]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "736[07-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "736[1-6]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "737[0-2]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "737[3-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "738", length: ["9"], areaCodeLength: nil, operator: "pkp_polskie_linie", format: "mobile_3/3/3")
		.init(prefix: "739[0-2]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "73930", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "7393[1-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "739[4-8]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7399[07-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "73991", length: ["9"], areaCodeLength: nil, operator: "agile_telecom", format: "mobile_3/3/3")
		.init(prefix: "73992", length: ["9"], areaCodeLength: nil, operator: "mobiweb_telecom", format: "mobile_3/3/3")
		.init(prefix: "73993", length: ["9"], areaCodeLength: nil, operator: "sia_netbalt", format: "mobile_3/3/3")
		.init(prefix: "7399[4-6]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "74", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "7419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "75", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "7519", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "76", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "7619", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "77", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "7719", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "780[0156]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "780[24]0", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7802[1-478]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "78025", length: ["9"], areaCodeLength: nil, operator: "interactive_digital_media", format: "mobile_3/3/3")
		.init(prefix: "78026", length: ["9"], areaCodeLength: nil, operator: "sia_netbalt", format: "mobile_3/3/3")
		.init(prefix: "78029", length: ["9"], areaCodeLength: nil, operator: "smshighway", format: "mobile_3/3/3")
		.init(prefix: "7803", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "7804[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "780[78]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "7809", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "78[1-35]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "78[478]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "78600", length: ["9"], areaCodeLength: nil, operator: "jmdi", format: "mobile_3/3/3")
		.init(prefix: "7860[1-69]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7860[78]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "786[12]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "786[3-6]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "78670", length: ["9"], areaCodeLength: nil, operator: "lancelot", format: "mobile_3/3/3")
		.init(prefix: "7867[1-3]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "7867[4-79]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "78678", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "786[89]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "789[0-4]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "789[5-9]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "79[0-46]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "795[06-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "795[1-5]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "79[78]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "799[06]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "799[1-57-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "800", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "toll_free_3/3/3-4")
		.init(prefix: "801", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "804", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "81", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8119", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "82", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8219", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "83", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8319", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "84", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "85", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8519", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "86", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8619", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "87", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8719", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "88[02689]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "881[089]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "8811", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "881[2-7]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "883[0-24-79]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "883[38]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "884[036-9]", length: ["9"], areaCodeLength: nil, operator: "play", format: "mobile_3/3/3")
		.init(prefix: "884[12]", length: ["9"], areaCodeLength: nil, operator: "t_mobile", format: "mobile_3/3/3")
		.init(prefix: "8844[0-35-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "88444", length: ["9"], areaCodeLength: nil, operator: "caritas", format: "mobile_3/3/3")
		.init(prefix: "8845", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "88[57]", length: ["9"], areaCodeLength: nil, operator: "plus", format: "mobile_3/3/3")
		.init(prefix: "89", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "8919", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "91", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "9119", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "94", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "9419", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
		.init(prefix: "95", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "9519", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_2/2/3")
	]
)

