//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_32 = RegionPhoneMetadata(
    code: 32,
    timezone: "Europe/Brussels",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_3/2/2/2", national: "#XXX XX XX XX", international: "XXX XX XX XX")
		.init(id: "fmt2_1/3/2/2", national: "#X XXX XX XX", international: "X XXX XX XX")
		.init(id: "fmt3_2/2/2/2", national: "#XX XX XX XX", international: "XX XX XX XX")
		.init(id: "fmt4_3/2/3", national: "#XXX XX XXX", international: "XXX XX XXX")
	],
    operators: [
		.init(id: "ericsson", name: "Ericsson NV")
		.init(id: "febo_telecom", name: "Febo Telecom")
		.init(id: "gateway_communications", name: "Gateway Communications")
		.init(id: "interactive_digital_media_gmbh", name: "Interactive Digital Media GmbH")
		.init(id: "join_experience_belgium", name: "Join Experience Belgium")
		.init(id: "lancelot", name: "Lancelot Telecom")
		.init(id: "lycamobile", name: "Lycamobile")
		.init(id: "messagebird", name: "MessageBird BV")
		.init(id: "mobile_vikings_or_jim", name: "Mobile Vikings/JIM Mobile")
		.init(id: "nmbs", name: "N.M.B.S.")
		.init(id: "onoff_telecom_sasu", name: "OnOff Télécom SASU")
		.init(id: "orange", name: "Orange")
		.init(id: "proximus", name: "Proximus")
		.init(id: "telenet", name: "Telenet")
		.init(id: "tismi_bv", name: "TISMI BV")
		.init(id: "vectone", name: "Vectone")
		.init(id: "voo", name: "VOO")
		.init(id: "voxbone_sa", name: "Voxbone SA")
		.init(id: "voyacom_sprl", name: "Voyacom SPRL")
	],
    ranges: [
		.init(prefix: "10", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "11", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "12", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "13", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "14", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "15", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "16", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "19", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "2[2-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt2_1/3/2/2")
		.init(prefix: "3[2-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt2_1/3/2/2")
		.init(prefix: "4[23]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt2_1/3/2/2")
		.init(prefix: "4500[02-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "45001", length: ["9"], areaCodeLength: nil, operator: "gateway_communications", format: "fmt1_3/2/2/2")
		.init(prefix: "450[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "45[1-47-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "455", length: ["9"], areaCodeLength: nil, operator: "voo", format: "fmt1_3/2/2/2")
		.init(prefix: "456", length: ["9"], areaCodeLength: nil, operator: "mobile_vikings_or_jim", format: "fmt1_3/2/2/2")
		.init(prefix: "460", length: ["9"], areaCodeLength: nil, operator: "proximus", format: "fmt1_3/2/2/2")
		.init(prefix: "461[0-79]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "4618", length: ["9"], areaCodeLength: nil, operator: "nmbs", format: "fmt1_3/2/2/2")
		.init(prefix: "46[24]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "463[01]", length: ["9"], areaCodeLength: nil, operator: "lancelot", format: "fmt1_3/2/2/2")
		.init(prefix: "463[2-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "46[57]0", length: ["9"], areaCodeLength: nil, operator: "telenet", format: "fmt1_3/2/2/2")
		.init(prefix: "465[1-9]", length: ["9"], areaCodeLength: nil, operator: "lycamobile", format: "fmt1_3/2/2/2")
		.init(prefix: "466[0-4]", length: ["9"], areaCodeLength: nil, operator: "lycamobile", format: "fmt1_3/2/2/2")
		.init(prefix: "466[5-7]", length: ["9"], areaCodeLength: nil, operator: "vectone", format: "fmt1_3/2/2/2")
		.init(prefix: "4668", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "4669", length: ["9"], areaCodeLength: nil, operator: "voxbone_sa", format: "fmt1_3/2/2/2")
		.init(prefix: "467[12]", length: ["9"], areaCodeLength: nil, operator: "join_experience_belgium", format: "fmt1_3/2/2/2")
		.init(prefix: "46730[0-57-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "467306", length: ["9"], areaCodeLength: nil, operator: "telenet", format: "fmt1_3/2/2/2")
		.init(prefix: "4673[1-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "4674", length: ["9"], areaCodeLength: nil, operator: "febo_telecom", format: "fmt1_3/2/2/2")
		.init(prefix: "4675", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "467[6-8]", length: ["9"], areaCodeLength: nil, operator: "lycamobile", format: "fmt1_3/2/2/2")
		.init(prefix: "4679", length: ["9"], areaCodeLength: nil, operator: "interactive_digital_media_gmbh", format: "fmt1_3/2/2/2")
		.init(prefix: "468[0-5]", length: ["9"], areaCodeLength: nil, operator: "telenet", format: "fmt1_3/2/2/2")
		.init(prefix: "4686", length: ["9"], areaCodeLength: nil, operator: "onoff_telecom_sasu", format: "fmt1_3/2/2/2")
		.init(prefix: "468[78]", length: ["9"], areaCodeLength: nil, operator: "lancelot", format: "fmt1_3/2/2/2")
		.init(prefix: "4689", length: ["9"], areaCodeLength: nil, operator: "febo_telecom", format: "fmt1_3/2/2/2")
		.init(prefix: "469", length: ["9"], areaCodeLength: nil, operator: "telenet", format: "fmt1_3/2/2/2")
		.init(prefix: "47", length: ["9"], areaCodeLength: nil, operator: "proximus", format: "fmt1_3/2/2/2")
		.init(prefix: "480[0148]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "4802", length: ["9"], areaCodeLength: nil, operator: "tismi_bv", format: "fmt1_3/2/2/2")
		.init(prefix: "4803", length: ["9"], areaCodeLength: nil, operator: "lancelot", format: "fmt1_3/2/2/2")
		.init(prefix: "4805", length: ["9"], areaCodeLength: nil, operator: "voyacom_sprl", format: "fmt1_3/2/2/2")
		.init(prefix: "4806", length: ["9"], areaCodeLength: nil, operator: "telenet", format: "fmt1_3/2/2/2")
		.init(prefix: "4807", length: ["9"], areaCodeLength: nil, operator: "messagebird", format: "fmt1_3/2/2/2")
		.init(prefix: "4809", length: ["9"], areaCodeLength: nil, operator: "ericsson", format: "fmt1_3/2/2/2")
		.init(prefix: "48[12]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt1_3/2/2/2")
		.init(prefix: "48[3-9]", length: ["9"], areaCodeLength: nil, operator: "telenet", format: "fmt1_3/2/2/2")
		.init(prefix: "49", length: ["9"], areaCodeLength: nil, operator: "orange", format: "fmt1_3/2/2/2")
		.init(prefix: "50", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "51", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "52", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "53", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "54", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "55", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "56", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "57", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "58", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "59", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "60", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "61", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "63", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "64", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "65", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "67", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "68", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "69", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "702[0-57]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "703[0457]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "7036", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "7044", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "7064", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "706[569]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "707[0579]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "71", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "780[57]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "781[014-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "782[25]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "783[15-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "7848", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "78[56]0", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "787[078]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "7876", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "7879", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "789", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "800[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt4_3/2/3")
		.init(prefix: "80[2-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "81", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "82", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "83", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "84", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "85", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "86", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "87", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "89", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt3_2/2/2/2")
		.init(prefix: "90", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt4_3/2/3")
		.init(prefix: "9[2-4]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt2_1/3/2/2")
	]
)

