//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_994 = RegionPhoneMetadata(
    code: 994,
    timezone: "Asia/Baku",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_2/3/2/2", national: "(#XX) XXX XX XX", international: "XX XXX XX XX")
		.init(id: "fmt_3/2/2/2", national: "#XXX XX XX XX", international: "XXX XX XX XX")
		.init(id: "mobile_2/3/2/2", national: "#XX XXX XX XX", international: "XX XXX XX XX")
	],
    operators: [
		.init(id: "azercell", name: "Azercell")
		.init(id: "aztelekom", name: "Aztelekom")
		.init(id: "bakcell", name: "Bakcell")
		.init(id: "fonex", name: "FONEX")
		.init(id: "nar_mobile", name: "Nar Mobile")
		.init(id: "naxtel", name: "Naxtel")
	],
    ranges: [
		.init(prefix: "10", length: ["9"], areaCodeLength: nil, operator: "azercell", format: "mobile_2/3/2/2")
		.init(prefix: "12", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "18", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2020", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2021", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2022", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2023", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2024", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2025", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2026", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2027", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2028", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2029", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2120", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2121", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2122", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2123", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2124", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2125", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2126", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2127", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2128", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2129", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "21428", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2220", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2221", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2222", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2223", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2224", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "222[56]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2227", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2229", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2230", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2231", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2232", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2233", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "223[46-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2235", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "22428", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2330", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2331", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2332", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2333", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "233[4679]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2335", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2338", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2420", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2421", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2422", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2[45]2[368]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2424", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2425", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2427", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2429", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2520", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2521", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2522", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2524", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2525", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2527", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2529", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2620", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2621", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2622", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2623", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2624", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2625", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2626", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2627", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2628", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2629", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2630", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2631", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2632", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "2638", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "3654[05]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36541", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "365[45]2", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36543", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36544", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36546", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36547", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36548", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36549", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36550", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "36554", length: ["9"], areaCodeLength: nil, operator: "naxtel", format: "mobile_2/3/2/2")
		.init(prefix: "40", length: ["9"], areaCodeLength: nil, operator: "fonex", format: "mobile_2/3/2/2")
		.init(prefix: "44", length: ["9"], areaCodeLength: nil, operator: "aztelekom", format: "mobile_2/3/2/2")
		.init(prefix: "46", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/2/2")
		.init(prefix: "5[01]", length: ["9"], areaCodeLength: nil, operator: "azercell", format: "mobile_2/3/2/2")
		.init(prefix: "55", length: ["9"], areaCodeLength: nil, operator: "bakcell", format: "mobile_2/3/2/2")
		.init(prefix: "60", length: ["9"], areaCodeLength: nil, operator: "naxtel", format: "mobile_2/3/2/2")
		.init(prefix: "7[07]", length: ["9"], areaCodeLength: nil, operator: "nar_mobile", format: "mobile_2/3/2/2")
		.init(prefix: "88", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/2/2")
		.init(prefix: "900200", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "99", length: ["9"], areaCodeLength: nil, operator: "bakcell", format: "mobile_2/3/2/2")
	]
)

