//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_995 = RegionPhoneMetadata(
    code: 995,
    timezone: "Asia/Tbilisi",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt_3/2/2/2", national: "#XXX XX XX XX", international: "XXX XX XX XX")
		.init(id: "mobile_3/2/2/2", national: "XXX XX XX XX", international: "XXX XX XX XX")
		.init(id: "tblisi_2/3/2/2", national: "#XX XXX XX XX", international: "XX XXX XX XX")
		.init(id: "voip_3/3/3", national: "#XXX XXX XXX", international: "XXX XXX XXX")
	],
    operators: [
		.init(id: "asanet", name: "Asanet")
		.init(id: "datacom", name: "Datacom")
		.init(id: "datahouse_global", name: "DataHouse Global")
		.init(id: "globalcell", name: "Globalcell")
		.init(id: "magticom", name: "MagtiCom")
		.init(id: "myphone", name: "MyPhone")
		.init(id: "pni", name: "Premium Net International SRL")
		.init(id: "silknet", name: "Silknet")
		.init(id: "veon", name: "Veon")
	],
    ranges: [
		.init(prefix: "32", length: ["9"], areaCodeLength: 2, operator: nil, format: "tblisi_2/3/2/2")
		.init(prefix: "341", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "342", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "344", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "345", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "346", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "347", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "348", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "349", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "350", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "351", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "352", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "353", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "354", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "355", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "356", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "357", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "358", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "359", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "360", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "361", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "362", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "363", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "364", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "365", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "366", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "367", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "368", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "369", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "370", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "371", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "372", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "373", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "374", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "410", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "411", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "412", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "413", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "414", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "415", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "416", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "417", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "418", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "419", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "422", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "423", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "424", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "425", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "426", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "427", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "431", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "432", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "433", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "434", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "435", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "436", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "437", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "439", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "442", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "443", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "444", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "445", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "446", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "447", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "448", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "472", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "473", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "479", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "491", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "492", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "493", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "494", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "495", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "496", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "497", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/2/2")
		.init(prefix: "5000", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50011", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50022", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50033", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50044", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50050[0-4]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "50050[5-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "50055", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50070[0-4]", length: ["9"], areaCodeLength: nil, operator: "myphone", format: "mobile_3/2/2/2")
		.init(prefix: "50077", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50088", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50099", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50505[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "50555[5-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "510[01]0[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "51100", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "51107[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "511[124]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "5113[01]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "51133[0-4]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "51151[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "51177[5-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "514", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "51555[5-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "51777[5-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "520[02]0[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "52222[0-4]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "522252[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "52252[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "530[03]0[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "53333[0-4]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "53353[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "540[04]0[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "544[0-36-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/2/2/2")
		.init(prefix: "5444[0-35-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/2/2/2")
		.init(prefix: "54444", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "5445", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "5500[05]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "550[05][1-46-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "550[1-46-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "55050", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "55055", length: ["9"], areaCodeLength: nil, operator: "datacom", format: "mobile_3/2/2/2")
		.init(prefix: "551", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "55200", length: ["9"], areaCodeLength: nil, operator: "pni", format: "mobile_3/2/2/2")
		.init(prefix: "55222[0-4]", length: ["9"], areaCodeLength: nil, operator: "asanet", format: "mobile_3/2/2/2")
		.init(prefix: "55[578]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "559[0-8]", length: ["9"], areaCodeLength: nil, operator: "globalcell", format: "mobile_3/2/2/2")
		.init(prefix: "5599[0-8]", length: ["9"], areaCodeLength: nil, operator: "globalcell", format: "mobile_3/2/2/2")
		.init(prefix: "55999[0-4]", length: ["9"], areaCodeLength: nil, operator: "globalcell", format: "mobile_3/2/2/2")
		.init(prefix: "55999[5-9]", length: ["9"], areaCodeLength: nil, operator: "datahouse_global", format: "mobile_3/2/2/2")
		.init(prefix: "568", length: ["9"], areaCodeLength: nil, operator: "veon", format: "mobile_3/2/2/2")
		.init(prefix: "570", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "57[149]", length: ["9"], areaCodeLength: nil, operator: "veon", format: "mobile_3/2/2/2")
		.init(prefix: "57500", length: ["9"], areaCodeLength: nil, operator: "asanet", format: "mobile_3/2/2/2")
		.init(prefix: "575[57]5", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "57577[7-9]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "57578[01]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "577", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "578", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/2/2/2")
		.init(prefix: "580[018]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "5802[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "5858[89]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "58855", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "58888", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "59000[0-4]", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "59090", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "59[15689]", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "59[27]", length: ["9"], areaCodeLength: nil, operator: "veon", format: "mobile_3/2/2/2")
		.init(prefix: "593", length: ["9"], areaCodeLength: nil, operator: "silknet", format: "mobile_3/2/2/2")
		.init(prefix: "706", length: ["9"], areaCodeLength: nil, operator: nil, format: "voip_3/3/3")
		.init(prefix: "707", length: ["9"], areaCodeLength: nil, operator: nil, format: "voip_3/3/3")
		.init(prefix: "790", length: ["9"], areaCodeLength: nil, operator: "magticom", format: "mobile_3/2/2/2")
		.init(prefix: "800", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_3/2/2/2")
	]
)

