//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_972 = RegionPhoneMetadata(
    code: 972,
    timezone: "Asia/Jerusalem",
    nationalPrefix: 0,
    extraRegion: [],
    formats: [
		.init(id: "fixed_1/3/4", national: "#X-XXX-XXXX", international: "X-XXX-XXXX")
		.init(id: "mobile_2/3/4", national: "#XX-XXX-XXXX", international: "XX-XXX-XXXX")
		.init(id: "premium_4/2/2", national: "XXXX-XX-XX", international: "XXXX-XX-XX")
		.init(id: "premium_4/3/3", national: "XXXX-XXX-XXX", international: "XXXX-XXX-XXX")
		.init(id: "tollfree_4/3", national: "XXXX-XXX", international: "XXXX-XXX")
		.init(id: "uan_4/6", national: "XXXX-XXXXXX", international: "XXXX-XXXXXX")
		.init(id: "varcost_1/3/3/3", national: "X-XXX-XXX-XXX", international: "X-XXX-XXX-XXX")
		.init(id: "voicemail_3/1-2/3/4", national: "XXX-X* XXX-XXXX", international: "XXX-X* XXX-XXXX")
	],
    operators: [
		.init(id: "019mobile", name: "019mobile")
		.init(id: "annatel", name: "Annatel")
		.init(id: "beezz", name: "Beezz")
		.init(id: "cellact", name: "Cellact")
		.init(id: "cellcom", name: "Cellcom")
		.init(id: "cellran_cellular", name: "Cellran Cellular Communications")
		.init(id: "free_telecom", name: "Free Telecom")
		.init(id: "golan_telecom", name: "Golan Telecom")
		.init(id: "home_cellular", name: "Home Cellular")
		.init(id: "hot_mobile", name: "Hot Mobile")
		.init(id: "jawwal", name: "Jawwal")
		.init(id: "maskyoo", name: "Maskyoo")
		.init(id: "merkaziya", name: "Merkaziya")
		.init(id: "ooredoo", name: "Ooredoo")
		.init(id: "orange", name: "Orange")
		.init(id: "paycall", name: "BITIT")
		.init(id: "pelephone", name: "Pelephone")
		.init(id: "rami_levy", name: "Rami Levy")
		.init(id: "xphone", name: "Xphone")
	],
    ranges: [
		.init(prefix: "1200", length: ["10"], areaCodeLength: nil, operator: nil, format: "premium_4/3/3")
		.init(prefix: "1212", length: ["8"], areaCodeLength: nil, operator: nil, format: "premium_4/2/2")
		.init(prefix: "1255", length: ["7"], areaCodeLength: nil, operator: nil, format: "tollfree_4/3")
		.init(prefix: "151", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "voicemail_3/1-2/3/4")
		.init(prefix: "153", length: ["11", "12"], areaCodeLength: nil, operator: nil, format: "voicemail_3/1-2/3/4")
		.init(prefix: "1599", length: ["10"], areaCodeLength: nil, operator: nil, format: "uan_4/6")
		.init(prefix: "1700", length: ["10"], areaCodeLength: nil, operator: nil, format: "varcost_1/3/3/3")
		.init(prefix: "180[019]", length: ["10"], areaCodeLength: nil, operator: nil, format: "varcost_1/3/3/3")
		.init(prefix: "190[0-2]", length: ["10"], areaCodeLength: nil, operator: nil, format: "varcost_1/3/3/3")
		.init(prefix: "1919", length: ["10"], areaCodeLength: nil, operator: nil, format: "varcost_1/3/3/3")
		.init(prefix: "2[0147]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "22", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "23[0-357]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "23[469]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "238[015]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "238[2-46-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "25[036-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "25[1245]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "26[0189]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "26[2-7]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "280", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "28[1-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "29[12578]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "29[3469]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "3[0-24]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "33[0-357]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "33[469]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "338[0-25]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "338[346-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "35[0-7]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "35[89]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "36[0-57-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "366", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "37[06-8]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "37[1-59]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "380", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "38[1-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "39[02-79]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "39[18]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "4[0147]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "4[26]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "43[0-257]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "433", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "43[469]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "438[015]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "438[26-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "438[34]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "450", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "45[1-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "48[0-7]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "48[89]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "49[02-467]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "49[1589]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "50[02-9]", length: ["9"], areaCodeLength: nil, operator: "pelephone", format: "mobile_2/3/4")
		.init(prefix: "51[2-9]", length: ["9"], areaCodeLength: nil, operator: "xphone", format: "mobile_2/3/4")
		.init(prefix: "52[02-9]", length: ["9"], areaCodeLength: nil, operator: "cellcom", format: "mobile_2/3/4")
		.init(prefix: "53", length: ["9"], areaCodeLength: nil, operator: "hot_mobile", format: "mobile_2/3/4")
		.init(prefix: "54[2-9]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_2/3/4")
		.init(prefix: "5501", length: ["9"], areaCodeLength: nil, operator: "beezz", format: "mobile_2/3/4")
		.init(prefix: "552[01]", length: ["9"], areaCodeLength: nil, operator: "paycall", format: "mobile_2/3/4")
		.init(prefix: "552[23]", length: ["9"], areaCodeLength: nil, operator: "home_cellular", format: "mobile_2/3/4")
		.init(prefix: "552[4-9]", length: ["9"], areaCodeLength: nil, operator: "019mobile", format: "mobile_2/3/4")
		.init(prefix: "553[01]", length: ["9"], areaCodeLength: nil, operator: "019mobile", format: "mobile_2/3/4")
		.init(prefix: "553[23]", length: ["9"], areaCodeLength: nil, operator: "free_telecom", format: "mobile_2/3/4")
		.init(prefix: "554[14]0", length: ["9"], areaCodeLength: nil, operator: "merkaziya", format: "mobile_2/3/4")
		.init(prefix: "5543", length: ["9"], areaCodeLength: nil, operator: "maskyoo", format: "mobile_2/3/4")
		.init(prefix: "5544[1-9]", length: ["9"], areaCodeLength: nil, operator: "cellran_cellular", format: "mobile_2/3/4")
		.init(prefix: "555[0-2]", length: ["9"], areaCodeLength: nil, operator: "annatel", format: "mobile_2/3/4")
		.init(prefix: "5555", length: ["9"], areaCodeLength: nil, operator: "rami_levy", format: "mobile_2/3/4")
		.init(prefix: "555[689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "556[6-8]", length: ["9"], areaCodeLength: nil, operator: "rami_levy", format: "mobile_2/3/4")
		.init(prefix: "557[0-2]", length: ["9"], areaCodeLength: nil, operator: "cellact", format: "mobile_2/3/4")
		.init(prefix: "5576", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "5577", length: ["9"], areaCodeLength: nil, operator: "019mobile", format: "mobile_2/3/4")
		.init(prefix: "558[7-9]", length: ["9"], areaCodeLength: nil, operator: "pelephone", format: "mobile_2/3/4")
		.init(prefix: "559[1-9]", length: ["9"], areaCodeLength: nil, operator: "019mobile", format: "mobile_2/3/4")
		.init(prefix: "56", length: ["9"], areaCodeLength: nil, operator: "ooredoo", format: "mobile_2/3/4")
		.init(prefix: "58[3-7]", length: ["9"], areaCodeLength: nil, operator: "golan_telecom", format: "mobile_2/3/4")
		.init(prefix: "59[2-9]", length: ["9"], areaCodeLength: nil, operator: "jawwal", format: "mobile_2/3/4")
		.init(prefix: "718", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "72[23]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "73[237]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "7380", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "7385[09]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "73888", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "747", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "76[258]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "77", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "782", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "7833", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "7855", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "7877", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "7881", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "79[2-9]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/4")
		.init(prefix: "8[014]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "8[279]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "83[0-27]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "833[03]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "833[124-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "83[4-69]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "838[015]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "838[2-46-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "85[05]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "85[1-46-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "86[09]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "86[1-8]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "88[04-7]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "88[1-389]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "9[0146]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "92", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "93[0-257]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "933[03]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "933[124-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "93[469]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "938[0145]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "938[236-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "950", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "95[1-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "97[0138]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "97[24-79]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "98[036-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "98[1245]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "99[0-46-9]", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "995", length: ["8"], areaCodeLength: 1, operator: nil, format: "fixed_1/3/4")
	]
)

