//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_98 = RegionPhoneMetadata(
    code: 98,
    timezone: "Asia/Tehran",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_2/4-5", national: "#XX XXXX*", international: "XX XXXX*")
		.init(id: "fixed_2/4/4", national: "#XX XXXX XXXX", international: "XX XXXX XXXX")
		.init(id: "nongeo_3/3/3-4", national: "#XXX XXX XXX*", international: "XXX XXX XXX*")
		.init(id: "uan_4-5", national: "#XXXX*", international: "XXXX*")
	],
    operators: [
		.init(id: "__samantel", name: "SamanTel")
		.init(id: "ir_mci", name: "IR-MCI")
		.init(id: "irancell", name: "Irancell")
		.init(id: "lotustel", name: "LOTUSTEL")
		.init(id: "mtce", name: "MTCE")
		.init(id: "rightel", name: "Rightel")
		.init(id: "shatel_mobile", name: "Shatel Mobile")
		.init(id: "taliya", name: "Taliya")
		.init(id: "telekish", name: "TeleKish")
	],
    ranges: [
		.init(prefix: "11", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "11[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "11[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "13", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "13[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "13[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "17", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "17[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "17[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "21", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "21[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "21[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "23", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "23[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "23[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "24", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "24[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "24[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "25", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "25[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "25[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "26", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "26[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "26[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "28", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "28[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "28[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "31", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "31[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "31[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "34", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "34[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "34[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "35", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "35[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "35[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "38", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "38[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "38[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "41", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "41[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "41[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "44", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "44[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "44[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "45", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "45[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "45[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "51", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "51[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "51[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "54", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "54[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "54[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "56", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "56[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "56[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "58", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "58[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "58[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "61", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "61[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "61[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "66", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "66[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "66[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "71", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "71[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "71[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "74", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "74[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "74[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "76", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "76[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "76[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "77", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "77[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "77[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "81", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "81[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "81[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "83", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "83[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "83[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "84", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "84[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "84[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "86", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "86[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "86[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "87", length: ["10"], areaCodeLength: 2, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "87[16]", length: ["6"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "87[289]", length: ["6", "7"], areaCodeLength: 2, operator: nil, format: "fixed_2/4-5")
		.init(prefix: "900", length: ["10"], areaCodeLength: nil, operator: "irancell", format: "nongeo_3/3/3-4")
		.init(prefix: "90[1-35]", length: ["10"], areaCodeLength: nil, operator: "irancell", format: "nongeo_3/3/3-4")
		.init(prefix: "9044", length: ["10"], areaCodeLength: nil, operator: "irancell", format: "nongeo_3/3/3-4")
		.init(prefix: "904[56]", length: ["10"], areaCodeLength: nil, operator: "irancell", format: "nongeo_3/3/3-4")
		.init(prefix: "91", length: ["10"], areaCodeLength: nil, operator: "ir_mci", format: "nongeo_3/3/3-4")
		.init(prefix: "92[0-3]", length: ["10"], areaCodeLength: nil, operator: "rightel", format: "nongeo_3/3/3-4")
		.init(prefix: "93[035-9]", length: ["10"], areaCodeLength: nil, operator: "irancell", format: "nongeo_3/3/3-4")
		.init(prefix: "931", length: ["10"], areaCodeLength: nil, operator: "mtce", format: "nongeo_3/3/3-4")
		.init(prefix: "932", length: ["10"], areaCodeLength: nil, operator: "taliya", format: "nongeo_3/3/3-4")
		.init(prefix: "934", length: ["10"], areaCodeLength: nil, operator: "telekish", format: "nongeo_3/3/3-4")
		.init(prefix: "94000[09]", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "942121", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "942[2689]0", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "9430[01]", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "94302", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "944111", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "94440", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "960[12]", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "962[16-8]", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "96308", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "963[14]5", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "963[23]", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "96366", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "9640", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "96480", length: ["5"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "965[01]", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "966[89]", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "9686", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "969[19]", length: ["4"], areaCodeLength: nil, operator: nil, format: "uan_4-5")
		.init(prefix: "99[01]", length: ["10"], areaCodeLength: nil, operator: "ir_mci", format: "nongeo_3/3/3-4")
		.init(prefix: "992", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "993", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "99[46]", length: ["10"], areaCodeLength: nil, operator: "ir_mci", format: "nongeo_3/3/3-4")
		.init(prefix: "99510", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "99550", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "9981", length: ["10"], areaCodeLength: nil, operator: "shatel_mobile", format: "nongeo_3/3/3-4")
		.init(prefix: "9982", length: ["10"], areaCodeLength: nil, operator: "shatel_mobile", format: "nongeo_3/3/3-4")
		.init(prefix: "99888", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "99900", length: ["10"], areaCodeLength: nil, operator: "lotustel", format: "nongeo_3/3/3-4")
		.init(prefix: "9990[13]", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "99902", length: ["10"], areaCodeLength: nil, operator: "ir_mci", format: "nongeo_3/3/3-4")
		.init(prefix: "9991", length: ["10"], areaCodeLength: nil, operator: "irancell", format: "nongeo_3/3/3-4")
		.init(prefix: "99921", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "99969", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "99977", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "9998[7-9]", length: ["10"], areaCodeLength: nil, operator: "rightel", format: "nongeo_3/3/3-4")
		.init(prefix: "9999[0-5]", length: ["10"], areaCodeLength: nil, operator: nil, format: "nongeo_3/3/3-4")
		.init(prefix: "9999[6-9]", length: ["10"], areaCodeLength: nil, operator: "rightel", format: "nongeo_3/3/3-4")
	]
)

