//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_992 = RegionPhoneMetadata(
    code: 992,
    timezone: "Asia/Dushanbe",
    prefix: "8~10",
    extraRegion: [],
    formats: [
		.init(id: "fixed_4/1/4", national: "XXXX X XXXX", international: "XXXX X XXXX")
		.init(id: "fixed_6/1/2", national: "XXXXXX X XX", international: "XXXXXX X XX")
		.init(id: "fmt_2/3/4", national: "XX XXX XXXX", international: "XX XXX XXXX")
		.init(id: "fmt_3/2/4", national: "XXX XX XXXX", international: "XXX XX XXXX")
	],
    operators: [
		.init(id: "babilon_m", name: "Babilon-M")
		.init(id: "megafon", name: "Megafon")
		.init(id: "o_mobile", name: "O-Mobile")
		.init(id: "tcell", name: "Tcell")
		.init(id: "zet_mobile", name: "ZET-MOBILE")
	],
    ranges: [
		.init(prefix: "[09]0", length: ["9"], areaCodeLength: nil, operator: "megafon", format: "fmt_2/3/4")
		.init(prefix: "0[127]", length: ["9"], areaCodeLength: nil, operator: "megafon", format: "fmt_2/3/4")
		.init(prefix: "0[3-589]", length: ["9"], areaCodeLength: nil, operator: "zet_mobile", format: "fmt_2/3/4")
		.init(prefix: "10", length: ["9"], areaCodeLength: nil, operator: "o_mobile", format: "fmt_2/3/4")
		.init(prefix: "11", length: ["9"], areaCodeLength: nil, operator: "tcell", format: "fmt_2/3/4")
		.init(prefix: "17", length: ["9"], areaCodeLength: nil, operator: "babilon_m", format: "fmt_2/3/4")
		.init(prefix: "2[02]", length: ["9"], areaCodeLength: nil, operator: "o_mobile", format: "fmt_2/3/4")
		.init(prefix: "30", length: ["9"], areaCodeLength: nil, operator: "o_mobile", format: "fmt_2/3/4")
		.init(prefix: "3130", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3131", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3132", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3133", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3134", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3135", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3136", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3137", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3138", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3139", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "314[02-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3141", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "315[0-27-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3153", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3154", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3155", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3156", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "322[013-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3222", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3240", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "324[14]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3242", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3243", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3245", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3246", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3247", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3248", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3249", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3250", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3251", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3252", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "325[3-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "331[039]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3311", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3312", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3314", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3315", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3316", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "331700", length: ["9"], areaCodeLength: 6, operator: nil, format: "fixed_6/1/2")
		.init(prefix: "33170[1-9]", length: ["9"], areaCodeLength: 6, operator: nil, format: "fixed_6/1/2")
		.init(prefix: "3317[1-9]", length: ["9"], areaCodeLength: 6, operator: nil, format: "fixed_6/1/2")
		.init(prefix: "3318", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "332[013-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3322", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "342[013-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3422", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "344[046-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3441", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3442", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3443", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3445", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "345[07-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3451", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3452", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3453", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3454", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3455", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3456", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "346[013689]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3462", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3464", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3465", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3467", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "347[0-46-8]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3475", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3479", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "352[013-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3522", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "355[07-9]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3551", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3552", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3553", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3554", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3555", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "3556", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/1/4")
		.init(prefix: "372", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/4")
		.init(prefix: "40", length: ["9"], areaCodeLength: nil, operator: "zet_mobile", format: "fmt_2/3/4")
		.init(prefix: "41[18]", length: ["9"], areaCodeLength: nil, operator: "megafon", format: "fmt_2/3/4")
		.init(prefix: "44[02-479]", length: ["9"], areaCodeLength: nil, operator: "zet_mobile", format: "fmt_3/2/4")
		.init(prefix: "446", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "474", length: ["9"], areaCodeLength: 3, operator: nil, format: "fmt_3/2/4")
		.init(prefix: "487", length: ["9"], areaCodeLength: 2, operator: nil, format: "fmt_2/3/4")
		.init(prefix: "50", length: ["9"], areaCodeLength: nil, operator: "tcell", format: "fmt_2/3/4")
		.init(prefix: "55", length: ["9"], areaCodeLength: nil, operator: "megafon", format: "fmt_2/3/4")
		.init(prefix: "7[07]", length: ["9"], areaCodeLength: nil, operator: "tcell", format: "fmt_2/3/4")
		.init(prefix: "71", length: ["9"], areaCodeLength: nil, operator: "babilon_m", format: "fmt_2/3/4")
		.init(prefix: "78", length: ["9"], areaCodeLength: nil, operator: "megafon", format: "fmt_2/3/4")
		.init(prefix: "80", length: ["9"], areaCodeLength: nil, operator: "zet_mobile", format: "fmt_2/3/4")
		.init(prefix: "81[1-9]", length: ["9"], areaCodeLength: nil, operator: "zet_mobile", format: "fmt_2/3/4")
		.init(prefix: "[89]7", length: ["9"], areaCodeLength: nil, operator: "megafon", format: "fmt_2/3/4")
		.init(prefix: "88", length: ["9"], areaCodeLength: nil, operator: "megafon", format: "fmt_2/3/4")
		.init(prefix: "91", length: ["9"], areaCodeLength: nil, operator: "zet_mobile", format: "fmt_2/3/4")
		.init(prefix: "9[239]", length: ["9"], areaCodeLength: nil, operator: "tcell", format: "fmt_2/3/4")
		.init(prefix: "9[48]", length: ["9"], areaCodeLength: nil, operator: "babilon_m", format: "fmt_2/3/4")
		.init(prefix: "9[56]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/3/4")
	]
)

