//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_63 = RegionPhoneMetadata(
    code: 63,
    timezone: "Asia/Manila",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_1/4/4", national: "(#X) XXXX XXXX", international: "X XXXX XXXX")
		.init(id: "fixed_1/5", national: "(#X) XXXXX", international: "X XXXXX")
		.init(id: "fixed_2/3/4", national: "(#XX) XXX XXXX", international: "XX XXX XXXX")
		.init(id: "fixed_4/4-6", national: "(#XXXX) XXXX**", international: "XXXX XXXX**")
		.init(id: "fixed_5/4", national: "(#XXXXX) XXXX", international: "XXXXX XXXX")
		.init(id: "mobile_3/3/4", national: "#XXX XXX XXXX", international: "XXX XXX XXXX")
		.init(id: "tollfree_4/1-2/3/4", national: "XXXX X* XXX XXXX", international: "XXXX X* XXX XXXX")
		.init(id: "tollfree_4/3/4", national: "XXXX XXX XXXX", international: "XXXX XXX XXXX")
	],
    operators: [
		.init(id: "__sun", name: "Sun")
		.init(id: "dito", name: "Dito")
		.init(id: "globe", name: "Globe")
		.init(id: "smart", name: "Smart")
	],
    ranges: [
		.init(prefix: "1800", length: ["11"], areaCodeLength: nil, operator: nil, format: "tollfree_4/3/4")
		.init(prefix: "1800", length: ["12", "13"], areaCodeLength: nil, operator: nil, format: "tollfree_4/1-2/3/4")
		.init(prefix: "2", length: ["6"], areaCodeLength: 1, operator: nil, format: "fixed_1/5")
		.init(prefix: "2[3-8]", length: ["9"], areaCodeLength: 1, operator: nil, format: "fixed_1/4/4")
		.init(prefix: "32[0-24-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "3230", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "323[1-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "33[0-8]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "339[0-689]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "3397", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "34[0-57-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "3460", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "3461", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "346[2-8]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "3469", length: ["9"], areaCodeLength: 5, operator: nil, format: "fixed_5/4")
		.init(prefix: "35", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "36", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "38", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "42[0-289]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "423[0-46-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4235", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "42[46][0-35-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "42[46]4", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "425[02-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4251", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "427[0-8]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4279", length: ["9"], areaCodeLength: 5, operator: nil, format: "fixed_5/4")
		.init(prefix: "43[0-8]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "439[0-57-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4396", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "44[013-57-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "442[013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4422", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "446[0-24-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4463", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "45[0-8]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "459[0-25689]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "459[347]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "46", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "47[0-57-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "476[02-46-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "476[15]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "48", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "49[0-246-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4930", length: ["9"], areaCodeLength: 5, operator: nil, format: "fixed_5/4")
		.init(prefix: "493[1-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "495[0-57-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "4956", length: ["9"], areaCodeLength: 5, operator: nil, format: "fixed_5/4")
		.init(prefix: "52[013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "522[02-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "5221", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "53", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "54[0-35-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "544[0-57-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "5446", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "55", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "56", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "62", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "63", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "64[013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "642[014-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "642[23]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "65", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "68", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "72", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "74", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "75", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "77", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "78", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "813", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "817", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/4")
		.init(prefix: "82", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "83", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "84", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "85", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "86[013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "862[013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "8622", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "87", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "88[016-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "88[24][013-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "88[24]2", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "8822", length: ["10"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "883[0-35-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "8834", length: ["9"], areaCodeLength: 5, operator: nil, format: "fixed_5/4")
		.init(prefix: "8842", length: ["8"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "885[024-9]", length: ["9"], areaCodeLength: 2, operator: nil, format: "fixed_2/3/4")
		.init(prefix: "885[13]", length: ["9"], areaCodeLength: 4, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "89[5-8]", length: ["10"], areaCodeLength: nil, operator: "dito", format: "mobile_3/3/4")
		.init(prefix: "90[56]", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "90[7-9]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "91[0-289]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "91[4-7]", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "92[0-3589]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "9[24]4", length: ["10"], areaCodeLength: nil, operator: "dito", format: "mobile_3/3/4")
		.init(prefix: "92[67]", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "93[0-389]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "9[39]4", length: ["10"], areaCodeLength: nil, operator: "dito", format: "mobile_3/3/4")
		.init(prefix: "9[369][5-7]", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "94[236-9]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "945", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "95[018]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "95[2-79]", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "96[0-489]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "970", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "97[125-8]", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "97[349]", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/4")
		.init(prefix: "98[158]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
		.init(prefix: "98[367]", length: ["10"], areaCodeLength: nil, operator: "globe", format: "mobile_3/3/4")
		.init(prefix: "989", length: ["10"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/4")
		.init(prefix: "99[1-3]", length: ["10"], areaCodeLength: nil, operator: "dito", format: "mobile_3/3/4")
		.init(prefix: "99[89]", length: ["10"], areaCodeLength: nil, operator: "smart", format: "mobile_3/3/4")
	]
)

