//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_371 = RegionPhoneMetadata(
    code: 371,
    timezone: "Europe/Bucharest",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_2/3/3", national: "XX XXX XXX", international: "XX XXX XXX")
	],
    operators: [
		.init(id: "bite", name: "Bite Latvia")
		.init(id: "lmt", name: "LMT")
		.init(id: "tele2", name: "Tele2")
		.init(id: "triatel", name: "Triatel")
		.init(id: "unistars", name: "UNISTARS")
	],
    ranges: [
		.init(prefix: "20[03-5]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "201[0-79]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2018", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "202", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "20[67]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "208[0-8]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2089", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "209[0-35-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2094", length: ["8"], areaCodeLength: nil, operator: "triatel", format: "fmt1_2/3/3")
		.init(prefix: "21", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "220[0-4]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "220[5-9]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "22[125]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "223[0-8]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "2239", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "224", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "226[0-589]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2266", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "2267", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "227[013-689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2272", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2277", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "228[0-4]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2285", length: ["8"], areaCodeLength: nil, operator: "unistars", format: "fmt1_2/3/3")
		.init(prefix: "228[67]", length: ["8"], areaCodeLength: nil, operator: "triatel", format: "fmt1_2/3/3")
		.init(prefix: "2288", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "2289", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "229[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2299", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "23[03][07]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "23100", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2310[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "231[17]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "231[2-689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "232[027]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "23[23]3[0238]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "2323[14579]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "232[4-69]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2328", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "233[124-689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "23400", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2340[13-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "23402", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "234[1-3689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2344[0-35-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "23444", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2345[0-57-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "23456", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "2347", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "23500", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2350[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "235[1-4689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "235[57]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "236[0-57-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2366", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "237[0-689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2377", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "238[0-4]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "238[5-79]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2388", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "239[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2399", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2400", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "240[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "241[02-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2411", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "242[024]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "24[24][135-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "243[0-24-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2433", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "244[02]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2444", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "245[05]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "245[1-46-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "246[06]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "246[1-57-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "247[0-6]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2477", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "247[89]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "248[0-79]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "2488", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "249[0-8]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "2499", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2500", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "250[1-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "251", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "25[239]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "25[467]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "255[0-5]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "255[6-9]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "258[0-49]", length: ["8"], areaCodeLength: nil, operator: "triatel", format: "fmt1_2/3/3")
		.init(prefix: "258[5-8]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "26[07-9]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "26[1-6]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "27[01]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "272[0-57]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2726", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "2728", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2729", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "27[38]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "27[45]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "276[0-7]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "276[89]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "277[0-689]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "2777", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "2790", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "279[13-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "279[29]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "28[0367]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "28[1289]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "284[0-3]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "284[4-8]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "2849", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "285[0-46-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "2855", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "290[02]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt1_2/3/3")
		.init(prefix: "290[13-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "29[1-4]", length: ["8"], areaCodeLength: nil, operator: "lmt", format: "fmt1_2/3/3")
		.init(prefix: "29[5-9]", length: ["8"], areaCodeLength: nil, operator: "tele2", format: "fmt1_2/3/3")
		.init(prefix: "60", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "61", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "62", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "630", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "631", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "632", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "633", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "634", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "63[56]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "637", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "638", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "639", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "640", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "641", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "6[48]2", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "643", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "644", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "645", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "646", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "647", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "648", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "649", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "65[05]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "651", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "652", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "653", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "65[48]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "656", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "657", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "659", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "6[679]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "68[0157-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "683", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "684", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "686", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "80", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "81", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
		.init(prefix: "90", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_2/3/3")
	]
)

