//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_370 = RegionPhoneMetadata(
    code: 370,
    timezone: "Europe/Bucharest",
    nationalPrefix: 8,0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_1/3/4", national: "(#-X) XXX XXXX", international: "X XXX XXXX")
		.init(id: "fixed_2/6", national: "(#-XX) XXXXXX", international: "XX XXXXXX")
		.init(id: "fmt_3/5", national: "(#-XXX) XXXXX", international: "XXX XXXXX")
		.init(id: "nongeo_3/2/3", national: "# XXX XX XXX", international: "XXX XX XXX")
	],
    operators: [
		.init(id: "bite", name: "BITĖ")
		.init(id: "lancelot", name: "Lancelot Telecom")
		.init(id: "tele_2", name: "Tele 2")
		.init(id: "telia", name: "Telia")
	],
    ranges: [
		.init(prefix: "310", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "31[12467]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "313", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "315", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "318", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "319", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "340", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "34[148]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "342", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "343", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "345", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "346", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "347", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "349", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "37", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "380", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "381", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "382", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "383", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "38[48]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "385", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "386", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "387", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "389", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "41", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "42[0349]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "421", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "422", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "425", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "426", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "427", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "428", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "440", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "441", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "442", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "443", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "444", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "445", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "446", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "447", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "448", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "449", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "450", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "451", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "45[2-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "458", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "459", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "460", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "46[1-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_2/6")
		.init(prefix: "469", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "52[0-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_1/3/4")
		.init(prefix: "528", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "529", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6[07]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "6[12]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6[35]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "64[0-49]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "64[5-8]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "660", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "6610[0-46-9]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "66105", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "661[1-79]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "6618[0-57-9]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "66186", length: ["8"], areaCodeLength: nil, operator: "lancelot", format: "fmt_3/5")
		.init(prefix: "66[29]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6630", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6631[0-2]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6631[3-9]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "6632[03]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "6632[14-9]", length: ["8"], areaCodeLength: nil, operator: "lancelot", format: "fmt_3/5")
		.init(prefix: "66322", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "663[3-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "664", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "665[013]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6652[01]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6652[2-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "665[4-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "666[0157-9]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "66620", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "66621", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6662[2-9]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "666[34]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6666", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "667[06-9]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "6671[02-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6671[19]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "6672[0-7]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6672[89]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "667[3-5]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6680", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "668[12589]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6683[0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "66839", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "6684[0-2]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "6684[3-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6686[0-5]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "6686[6-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6687[0-589]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6687[67]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "68[026-8]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "68[159]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "68[34]", length: ["8"], areaCodeLength: nil, operator: "tele_2", format: "fmt_3/5")
		.init(prefix: "69[019]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "69[2-68]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "697[0-3579]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6974[0147-9]", length: ["8"], areaCodeLength: nil, operator: "telia", format: "fmt_3/5")
		.init(prefix: "6974[23]", length: ["8"], areaCodeLength: nil, operator: "bite", format: "fmt_3/5")
		.init(prefix: "6974[56]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "6976", length: ["8"], areaCodeLength: nil, operator: "lancelot", format: "fmt_3/5")
		.init(prefix: "6978", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt_3/5")
		.init(prefix: "70[05]", length: ["8"], areaCodeLength: nil, operator: nil, format: "nongeo_3/2/3")
		.init(prefix: "70[67]", length: ["8"], areaCodeLength: nil, operator: nil, format: "nongeo_3/2/3")
		.init(prefix: "80[02]", length: ["8"], areaCodeLength: nil, operator: nil, format: "nongeo_3/2/3")
		.init(prefix: "[89]01", length: ["8"], areaCodeLength: nil, operator: nil, format: "nongeo_3/2/3")
		.init(prefix: "808", length: ["8"], areaCodeLength: nil, operator: nil, format: "nongeo_3/2/3")
		.init(prefix: "90[0239]", length: ["8"], areaCodeLength: nil, operator: nil, format: "nongeo_3/2/3")
		.init(prefix: "910", length: ["8"], areaCodeLength: nil, operator: nil, format: "nongeo_3/2/3")
	]
)

