//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_358 = RegionPhoneMetadata(
    code: 358,
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: "AX",
    formats: [
		.init(id: "fmt_1/4-9", national: "#X XXXX*****", international: "X XXXX*****")
		.init(id: "fmt_2/4-8", national: "#XX XXXX****", international: "XX XXXX****")
		.init(id: "fmt_2/6-10", national: "#XX XXXXXX****", international: "XX XXXXXX****")
		.init(id: "fmt_3/3-7", national: "#XXX XXX****", international: "XXX XXX****")
		.init(id: "shortcode_5", national: "#XXXXX", international: )
		.init(id: "shortcode_6", national: "XXXXXX", international: )
	],
    operators: [
		.init(id: "__globetel", name: "Globetel")
		.init(id: "__nettia", name: "NETTIA")
		.init(id: "ainacom", name: "AinaCom")
		.init(id: "amt", name: "AMT")
		.init(id: "beepsend", name: "Beepsend")
		.init(id: "benemen", name: "Benemen Oy")
		.init(id: "compatel", name: "Compatel")
		.init(id: "cuuma", name: "Cuuma")
		.init(id: "dna", name: "DNA")
		.init(id: "elisa", name: "Elisa")
		.init(id: "interactive_digital_media", name: "Interactive Digital Media")
		.init(id: "liikennevirasto", name: "Liikennevirasto")
		.init(id: "mi", name: "MI")
		.init(id: "mobiweb", name: "MobiWeb")
		.init(id: "nettia", name: "NETTIA")
		.init(id: "nextgen_mobile_cardboardfish", name: "NextGen Mobile / CardBoardFish")
		.init(id: "nokia", name: "Nokia")
		.init(id: "nokia_solutions_and_networks", name: "Nokia Solutions and Networks")
		.init(id: "nord_connect", name: "Nord Connect SIA")
		.init(id: "sms_provider_corp", name: "SMS Provider Corp")
		.init(id: "suomen_virveverkko", name: "Suomen Virveverkko")
		.init(id: "telavox", name: "Telavox AB")
		.init(id: "telia", name: "Telia")
		.init(id: "tismi", name: "Tismi")
		.init(id: "top_connect", name: "Top Connect OU")
		.init(id: "voxbone", name: "Voxbone")
	],
    ranges: [
		.init(prefix: "100", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "10[1-9]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "13[1-8]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "13[1-8]", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "14[1-8]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "14[1-8]", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "15[1-8]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "15[1-8]", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "16[1-8]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "16[1-8]", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "17[1-8]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "17[1-8]", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "18[1-8]", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "19[1-8]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "19[1-8]", length: ["6-9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "[23]00", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "20[13-8]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "202[023]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "202[023]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "202[14-9]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "202[14-9]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "20[3-5]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "209[0-7]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "209[0-7]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "209[89]", length: ["5"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "209[89]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "2[1-8]", length: ["5-9"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
		.init(prefix: "29", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "30[1-9]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
		.init(prefix: "3[1-8]", length: ["5-9"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
		.init(prefix: "39", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
		.init(prefix: "4[02]", length: ["6-10"], areaCodeLength: nil, operator: "telia", format: "fmt_2/4-8")
		.init(prefix: "4[14]", length: ["6-10"], areaCodeLength: nil, operator: "dna", format: "fmt_2/4-8")
		.init(prefix: "43[013-579]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "432[01]", length: ["6-10"], areaCodeLength: nil, operator: "cuuma", format: "fmt_2/4-8")
		.init(prefix: "4322", length: ["6-10"], areaCodeLength: nil, operator: "benemen", format: "fmt_2/4-8")
		.init(prefix: "4323", length: ["6-10"], areaCodeLength: nil, operator: "top_connect", format: "fmt_2/4-8")
		.init(prefix: "4324", length: ["6-10"], areaCodeLength: nil, operator: "nord_connect", format: "fmt_2/4-8")
		.init(prefix: "4325", length: ["6-10"], areaCodeLength: nil, operator: "nettia", format: "fmt_2/4-8")
		.init(prefix: "432[6-9]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "43[68]", length: ["6-10"], areaCodeLength: nil, operator: "dna", format: "fmt_2/4-8")
		.init(prefix: "450", length: ["6-10"], areaCodeLength: nil, operator: "telia", format: "fmt_2/4-8")
		.init(prefix: "45[1-368]", length: ["6-10"], areaCodeLength: nil, operator: "elisa", format: "fmt_2/4-8")
		.init(prefix: "4540", length: ["6-10"], areaCodeLength: nil, operator: "mobiweb", format: "fmt_2/4-8")
		.init(prefix: "4541", length: ["6-10"], areaCodeLength: nil, operator: "ainacom", format: "fmt_2/4-8")
		.init(prefix: "454[2-4]", length: ["6-10"], areaCodeLength: nil, operator: "nokia", format: "fmt_2/4-8")
		.init(prefix: "4545", length: ["6-10"], areaCodeLength: nil, operator: "interactive_digital_media", format: "fmt_2/4-8")
		.init(prefix: "4546", length: ["6-10"], areaCodeLength: nil, operator: "nextgen_mobile_cardboardfish", format: "fmt_2/4-8")
		.init(prefix: "4547", length: ["6-10"], areaCodeLength: nil, operator: "sms_provider_corp", format: "fmt_2/4-8")
		.init(prefix: "4548", length: ["6-10"], areaCodeLength: nil, operator: "voxbone", format: "fmt_2/4-8")
		.init(prefix: "4549", length: ["6-10"], areaCodeLength: nil, operator: "beepsend", format: "fmt_2/4-8")
		.init(prefix: "455[0248]", length: ["6-10"], areaCodeLength: nil, operator: "suomen_virveverkko", format: "fmt_2/4-8")
		.init(prefix: "455[13]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "4555", length: ["6-10"], areaCodeLength: nil, operator: "nokia_solutions_and_networks", format: "fmt_2/4-8")
		.init(prefix: "4556", length: ["6-10"], areaCodeLength: nil, operator: "liikennevirasto", format: "fmt_2/4-8")
		.init(prefix: "4557", length: ["6-10"], areaCodeLength: nil, operator: "compatel", format: "fmt_2/4-8")
		.init(prefix: "4559", length: ["6-10"], areaCodeLength: nil, operator: "mi", format: "fmt_2/4-8")
		.init(prefix: "457[035]", length: ["6-10"], areaCodeLength: nil, operator: "amt", format: "fmt_2/4-8")
		.init(prefix: "4571", length: ["6-10"], areaCodeLength: nil, operator: "tismi", format: "fmt_2/4-8")
		.init(prefix: "4572", length: ["6-10"], areaCodeLength: nil, operator: "telavox", format: "fmt_2/4-8")
		.init(prefix: "457[46-9]", length: ["6-10"], areaCodeLength: nil, operator: "dna", format: "fmt_2/4-8")
		.init(prefix: "459", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "46", length: ["6-10"], areaCodeLength: nil, operator: "elisa", format: "fmt_2/4-8")
		.init(prefix: "4[78]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "4946", length: ["6-10"], areaCodeLength: nil, operator: "elisa", format: "fmt_2/4-8")
		.init(prefix: "50", length: ["6-10"], areaCodeLength: nil, operator: "elisa", format: "fmt_2/4-8")
		.init(prefix: "5[1-8]", length: ["5-9"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
		.init(prefix: "600", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "60[12]", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "606", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "6[1-8]", length: ["5-9"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
		.init(prefix: "700", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "70[1-5]", length: ["8-12"], areaCodeLength: nil, operator: nil, format: "fmt_2/6-10")
		.init(prefix: "70[78]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "7099", length: ["8", "9"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "71", length: ["9"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "73", length: ["10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "75[03-9]", length: ["6-10"], areaCodeLength: nil, operator: nil, format: "fmt_2/4-8")
		.init(prefix: "800", length: ["7-9"], areaCodeLength: nil, operator: nil, format: "fmt_3/3-7")
		.init(prefix: "8[1-8]", length: ["5-9"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
		.init(prefix: "9[1-8]", length: ["5-9"], areaCodeLength: nil, operator: nil, format: "fmt_1/4-9")
	]
)

