//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_853 = RegionPhoneMetadata(
    code: 853,
    timezone: "Asia/Shanghai",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fmt1_4/3", national: "XXXX XXX", international: "XXXX XXX")
		.init(id: "fmt1_4/4", national: "XXXX XXXX", international: "XXXX XXXX")
	],
    operators: [
		.init(id: "3", name: "3")
		.init(id: "china_telecom", name: "China Telecom")
		.init(id: "ctm", name: "CTM")
		.init(id: "guangxing_communication_co", name: "Guangxing Communication Co")
		.init(id: "smartone", name: "SmarTone")
	],
    ranges: [
		.init(prefix: "0800", length: ["7"], areaCodeLength: nil, operator: nil, format: "fmt1_4/3")
		.init(prefix: "28[2-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "6200", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "620[1-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "621", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "622", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "62[38]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "624[016-9]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "624[23]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "624[45]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "625[0-3]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "625[4-9]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "626[0-389]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "626[4-7]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "627[01]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "627[2-5]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "627[6-9]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "629[016-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "629[2-5]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "630[0-29]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "630[3-8]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "631", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "632[01]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "632[23]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "632[4-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "633[0-5]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "633[6-9]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "634[0-3]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "6344", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "634[5-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "635", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "636", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "637[0-7]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "63[79][89]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "638[0-5]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "638[6-9]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "639[01]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "639[2-7]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "650[0-4]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "65[01][5-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "651[0-4]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "65[27][0-3]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "652[4-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "653[016-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "653[2-5]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "654[01]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "6542[0-4]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "6542[5-9]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "654[34]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "654[56]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "6547[0-4]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "6547[5-9]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "654[89]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "655[0-5]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "655[6-9]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "656", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "657[4-9]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "658[0-5]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "658[6-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "659[0-7]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "659[89]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "6600[02-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "66001", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "6601", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "660[24]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "6603", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "6605", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "661[0167]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "661[2389]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "661[45]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "662", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "663", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "664[01]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "664[2-68]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "6647", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "66[49]9", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "665[0-589]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "665[67]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "66[68]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "667[01]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "667[2579]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "667[38]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "667[46]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "669[01]", length: ["8"], areaCodeLength: nil, operator: "guangxing_communication_co", format: "fmt1_4/4")
		.init(prefix: "669[2368]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "669[457]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "6800[0-79]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "680[1-4]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "68[07][5-9]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "68[18][0-4]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "681[5-9]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "68[28][5-9]", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "68[37][0-4]", length: ["8"], areaCodeLength: nil, operator: "smartone", format: "fmt1_4/4")
		.init(prefix: "68[45][0-4]", length: ["8"], areaCodeLength: nil, operator: "3", format: "fmt1_4/4")
		.init(prefix: "684[5-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "685[5-9]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "686", length: ["8"], areaCodeLength: nil, operator: "china_telecom", format: "fmt1_4/4")
		.init(prefix: "689[0-4]", length: ["8"], areaCodeLength: nil, operator: "ctm", format: "fmt1_4/4")
		.init(prefix: "811", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "8[2-47][0-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "8[2-47]9", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "85[09]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "85[1-8]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "88[0689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "88[13-57]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "882[014-9]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "882[23]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "89[0-79]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
		.init(prefix: "898", length: ["8"], areaCodeLength: nil, operator: nil, format: "fmt1_4/4")
	]
)

