//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yury Dryhin on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_352 = RegionPhoneMetadata(
    code: 352,
    timezone: "Europe/Luxembourg",
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_line_2/2/2", national: "XX XX XX", international: "XX XX XX")
		.init(id: "fixed_line_2/2/2/1-2", national: "XX XX XX X*", international: "XX XX XX X*")
		.init(id: "fixed_line_2/2/2/1-5", national: "XX XX XX X****", international: "XX XX XX X****")
		.init(id: "fixed_line_2/2/2/2/1-2", national: "XX XX XX XX X*", international: "XX XX XX XX X*")
		.init(id: "fixed_line_2/2/2/3", national: "XX XX XX XXX", international: "XX XX XX XXX")
		.init(id: "fixed_line_2/2/3", national: "XX XX XXX", international: "XX XX XXX")
		.init(id: "fixed_line_2/3", national: "XX XXX", international: "XX XXX")
		.init(id: "mobile_3/3/3", national: "XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "var_cost_3/2/3", national: "XXX XX XXX", international: "XXX XX XXX")
	],
    operators: [
		.init(id: "join", name: "JOIN")
		.init(id: "orange", name: "Orange")
		.init(id: "post", name: "POST")
		.init(id: "tango", name: "Tango")
	],
    ranges: [
		.init(prefix: "20[1-689]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "20[2-689]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "20[2-689]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "20[2-689]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "20[2-689]", length: ["7"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/3")
		.init(prefix: "20[2-689]", length: ["9"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/3")
		.init(prefix: "20[2-689]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[28]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[28]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[28]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[28]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "23", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "23", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "23", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "23", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "23", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "23", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "24[01]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "24[01]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "24[01]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "24[01]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "242[04-6]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "242[04-6]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "242[04-6]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "242[04-6]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]21", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]21", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]21", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2421", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]21", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]2[28]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]2[28]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]2[28]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "242[28]", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]2[28]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]23", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]23", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]23", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2423", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]23", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]27", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]27", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]27", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2427", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]27", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]29", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]29", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]29", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2429", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]29", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]30", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]30", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]30", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]30", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]30", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]30", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]31", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]31", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]31", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]31", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]31", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]31", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]32", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]32", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]32", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]32", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]32", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]32", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]33", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]33", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]33", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]33", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]33", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]33", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]34", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]34", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]34", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]34", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]34", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]34", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]35", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]35", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]35", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]35", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]35", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]35", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]36", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]36", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]36", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]36", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]36", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]36", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]37", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]37", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]37", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]37", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]37", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]37", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2438", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2438", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2438", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2438", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2438", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2438", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]39", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]39", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]39", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]39", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]39", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]39", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]4[09]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]4[09]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]4[09]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]4[09]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]4[09]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]4[09]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "244[146]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "244[146]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "244[146]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "244[146]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "244[146]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "244[146]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]42", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]42", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]42", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]42", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]42", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]42", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]43", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]43", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]43", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]43", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]43", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]43", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]45", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]45", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]45", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]45", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]45", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]45", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]47", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]47", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]47", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]47", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]47", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]47", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]48", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]48", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]48", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]48", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]48", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]48", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]50", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]50", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]50", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]50", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]50", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]50", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]51", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]51", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]51", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]51", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]51", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]51", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]52", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]52", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]52", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]52", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]52", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]52", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]5[34]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]5[34]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]5[34]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]5[34]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]5[34]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]5[34]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]55", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]55", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]55", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]55", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]55", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]55", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]56", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]56", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]56", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]56", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]56", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]56", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]57", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]57", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]57", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]57", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]57", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]57", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]58", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]58", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]58", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]58", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]58", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]58", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]59", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]59", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]59", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]59", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]59", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]59", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "246[0-689]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "246[0-689]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "246[0-689]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "246[0-689]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "246[0-689]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "246[0-689]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]67", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]67", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]67", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]67", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]67", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]67", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "247[07]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "247[07]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "247[07]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "247[07]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "247[07]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "247[07]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]71", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]71", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]71", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]71", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]71", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]71", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]72", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]72", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]72", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]72", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]72", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]72", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]73", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]73", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]73", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]73", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]73", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]73", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]74", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]74", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]74", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]74", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]74", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]74", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]75", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]75", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]75", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]75", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]75", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]75", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]76", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]76", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]76", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]76", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]76", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]76", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]78", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]78", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]78", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]78", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]78", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]78", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]79", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]79", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]79", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]79", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]79", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]79", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]80", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]80", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]80", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]80", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]80", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]80", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]81", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]81", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]81", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]81", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]81", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]81", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "248[269]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "248[269]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "248[269]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "248[269]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "248[269]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "248[269]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]83", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]83", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]83", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]83", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]83", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]83", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]84", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]84", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]84", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]84", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]84", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]84", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]85", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]85", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]85", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]85", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]85", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]85", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]87", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]87", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]87", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]87", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]87", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]87", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]88", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]88", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]88", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[467]88", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[467]88", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[467]88", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "249[013468]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "249[013468]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "249[013468]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "249[013468]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]92", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]92", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]92", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2492", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]92", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]95", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]95", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]95", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2495", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]95", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]97", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]97", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]97", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2497", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]97", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]99", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[467]99", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[467]99", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2499", length: ["7-10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[467]99", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "25", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "25", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "25", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "25", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67][01]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67][01]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67][01]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67][01]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67][01]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67][01]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]2[046]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]2[046]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]2[046]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]2[046]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]2[046]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]2[046]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]21", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]21", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]2[28]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]2[28]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]23", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]23", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]25", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]25", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]25", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]25", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]25", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]25", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]27", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]27", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]29", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]29", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]38", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]38", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]38", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]38", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]38", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]38", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]4[146]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]4[146]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]4[146]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]4[146]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]4[146]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]4[146]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]6[0-689]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]6[0-689]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]6[0-689]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]6[0-689]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]6[0-689]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]6[0-689]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]7[07]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]7[07]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]7[07]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]7[07]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]7[07]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]7[07]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]8[269]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]8[269]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]8[269]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]8[269]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]8[269]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]8[269]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]9[013468]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "2[67]9[013468]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "2[67]9[013468]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "2[67]9[013468]", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]9[013468]", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]9[013468]", length: ["11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "2[67]92", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]92", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]95", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]95", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]97", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]97", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "2[67]99", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-2")
		.init(prefix: "2[67]99", length: ["9", "10"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/2/1-2")
		.init(prefix: "29", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "29", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "29", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "29", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "30", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "30", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "30", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "30", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "31", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "31", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "31", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "31", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "32", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "32", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "32", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "32", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "33", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "33", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "33", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "33", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "34", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "34", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "34", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "34", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "35[013-9]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "35[013-9]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "35[013-9]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "35[013-9]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "36", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "36", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "36", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "36", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "37", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "37", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "37", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "37", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "38", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "38", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "38", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "38", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "39", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "39", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "39", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "39", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "4[09]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "4[09]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "4[09]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "4[09]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "4[146]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "4[146]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "4[146]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "4[146]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "42", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "42", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "42", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "42", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "43", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "43", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "43", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "43", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "45", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "45", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "45", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "45", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "47", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "47", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "47", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "47", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "48", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "48", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "48", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "48", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "50", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "50", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "50", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "50", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "51", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "51", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "51", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "51", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "52", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "52", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "52", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "52", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "5[34]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "5[34]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "5[34]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "5[34]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "55", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "55", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "55", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "55", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "56", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "56", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "56", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "56", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "57", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "57", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "57", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "57", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "58", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "58", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "58", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "58", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "59", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "59", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "59", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "59", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "6[25][18]", length: ["9"], areaCodeLength: nil, operator: "post", format: "mobile_3/3/3")
		.init(prefix: "655", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "656", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "66[18]", length: ["9"], areaCodeLength: nil, operator: "orange", format: "mobile_3/3/3")
		.init(prefix: "67[18]", length: ["9"], areaCodeLength: nil, operator: "join", format: "mobile_3/3/3")
		.init(prefix: "679", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "681", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "69[18]", length: ["9"], areaCodeLength: nil, operator: "tango", format: "mobile_3/3/3")
		.init(prefix: "7[07]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "7[07]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "7[07]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "7[07]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "71", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "71", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "71", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "71", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "72", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "72", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "72", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "72", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "73", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "73", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "73", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "73", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "74", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "74", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "74", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "74", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "75", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "75", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "75", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "75", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "76", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "76", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "76", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "76", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "78", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "78", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "78", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "78", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "79", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "79", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "79", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "79", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "800", length: ["8"], areaCodeLength: nil, operator: nil, format: "var_cost_3/2/3")
		.init(prefix: "801", length: ["8"], areaCodeLength: nil, operator: nil, format: "var_cost_3/2/3")
		.init(prefix: "80[2-9]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "80[2-9]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "80[2-9]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "80[2-9]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "81", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "81", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "81", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "81", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "83", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "83", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "83", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "83", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "84", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "84", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "84", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "84", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "85", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "85", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "85", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "85", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "8[69]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "8[69]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "8[69]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "8[69]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "87", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "87", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "87", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "87", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "88", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "88", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "88", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "88", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "90[015]", length: ["8"], areaCodeLength: nil, operator: nil, format: "var_cost_3/2/3")
		.init(prefix: "90[89]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "90[89]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "90[89]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "90[89]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "92", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "92", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "92", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "92", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "9[34]", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "9[34]", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "9[34]", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "9[34]", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "95", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "95", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "95", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "95", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "97", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "97", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "97", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "97", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
		.init(prefix: "99", length: ["4"], areaCodeLength: nil, operator: nil, format: )
		.init(prefix: "99", length: ["5"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/3")
		.init(prefix: "99", length: ["6"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2")
		.init(prefix: "99", length: ["7-11"], areaCodeLength: nil, operator: nil, format: "fixed_line_2/2/2/1-5")
	]
)

