//
//  RegionPhoneMetadata.swift
//  PhoneNumberField
//
//  Created by Yuri on 05.09.2023.
//  Copyright © 2023 DTechLabs. All rights reserved.
//

import Foundation

let RegionPhoneMetadata_84 = RegionPhoneMetadata(
    code: 84,
    timezone: "Asia/Bangkok",
    nationalPrefix: 0,
    prefix: "00",
    extraRegion: [],
    formats: [
		.init(id: "fixed_2/4/4", national: "#XX XXXX XXXX", international: "XX XXXX XXXX")
		.init(id: "fixed_3/4/3", national: "#XXX XXXX XXX", international: "XXX XXXX XXX")
		.init(id: "fixed_4/4-6", national: "XXXX XXXX**", international: "XXXX XXXX**")
		.init(id: "mobile_2/3/2/2", national: "#XX XXX XX XX", international: "XX XXX XX XX")
		.init(id: "mobile_3/3/3", national: "#XXX XXX XXX", international: "XXX XXX XXX")
		.init(id: "uan_2/5", national: "#XX XXXXX", international: "XX XXXXX")
		.init(id: "uan_3/4", national: "#XXX XXXX", international: )
		.init(id: "uan_3/4-5", national: "#XXX XXXX*", international: )
	],
    operators: [
		.init(id: "g_mobile", name: "G-Mobile")
		.init(id: "indochina_telecom", name: "Indochina Telecom")
		.init(id: "mobifone", name: "MobiFone")
		.init(id: "reddi", name: "Reddi")
		.init(id: "vietnamobile", name: "Vietnamobile")
		.init(id: "viettel", name: "Viettel")
		.init(id: "viettel_mobile", name: "Viettel Mobile")
		.init(id: "vinaphone", name: "Vinaphone")
	],
    ranges: [
		.init(prefix: "120[13]", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "1228", length: ["8"], areaCodeLength: nil, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "1800", length: ["8-10"], areaCodeLength: nil, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "1900", length: ["8-10"], areaCodeLength: nil, operator: nil, format: "fixed_4/4-6")
		.init(prefix: "199", length: ["7"], areaCodeLength: nil, operator: nil, format: "uan_3/4")
		.init(prefix: "203", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "204", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "205", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "206", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "207", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "208", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "209", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "210", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "211", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "212", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "213", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "214", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "215", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "216", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "218", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "219", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "220", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "221", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "222", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "225", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "226", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "227", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "228", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "229", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "232", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "233", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "234", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "235", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "236", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "237", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "238", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "239", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "24[2-8]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "251", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "252", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "254", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "255", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "256", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "257", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "258", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "259", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "260", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "261", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "262", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "263", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "269", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "270", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "271", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "272", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "273", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "274", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "275", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "276", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "277", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "28[2-9]", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_2/4/4")
		.init(prefix: "290", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "291", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "292", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "293", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "294", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "296", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "297", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "299", length: ["10"], areaCodeLength: nil, operator: nil, format: "fixed_3/4/3")
		.init(prefix: "30", length: ["9"], areaCodeLength: nil, operator: "mobifone", format: "mobile_3/3/3")
		.init(prefix: "3[1-9]", length: ["9"], areaCodeLength: nil, operator: "viettel_mobile", format: "mobile_3/3/3")
		.init(prefix: "51", length: ["9"], areaCodeLength: nil, operator: "mobifone", format: "mobile_3/3/3")
		.init(prefix: "52[238]", length: ["9"], areaCodeLength: nil, operator: "vietnamobile", format: "mobile_3/3/3")
		.init(prefix: "559", length: ["9"], areaCodeLength: nil, operator: "reddi", format: "mobile_3/3/3")
		.init(prefix: "5[68]", length: ["9"], areaCodeLength: nil, operator: "vietnamobile", format: "mobile_3/3/3")
		.init(prefix: "59", length: ["9"], areaCodeLength: nil, operator: "g_mobile", format: "mobile_3/3/3")
		.init(prefix: "672", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_2/3/2/2")
		.init(prefix: "69", length: ["7", "8"], areaCodeLength: nil, operator: nil, format: "uan_3/4-5")
		.init(prefix: "7[06-9]", length: ["9"], areaCodeLength: nil, operator: "mobifone", format: "mobile_3/3/3")
		.init(prefix: "799", length: ["7"], areaCodeLength: nil, operator: nil, format: "uan_3/4")
		.init(prefix: "80", length: ["7"], areaCodeLength: nil, operator: nil, format: "uan_2/5")
		.init(prefix: "8[1-578]", length: ["9"], areaCodeLength: nil, operator: "vinaphone", format: "mobile_3/3/3")
		.init(prefix: "86", length: ["9"], areaCodeLength: nil, operator: "viettel_mobile", format: "mobile_3/3/3")
		.init(prefix: "89[689]", length: ["9"], areaCodeLength: nil, operator: "mobifone", format: "mobile_3/3/3")
		.init(prefix: "897", length: ["9"], areaCodeLength: nil, operator: "mobifone", format: "mobile_3/3/3")
		.init(prefix: "9[03]", length: ["9"], areaCodeLength: nil, operator: "mobifone", format: "mobile_3/3/3")
		.init(prefix: "9[14]", length: ["9"], areaCodeLength: nil, operator: "vinaphone", format: "mobile_3/3/3")
		.init(prefix: "92", length: ["9"], areaCodeLength: nil, operator: "vietnamobile", format: "mobile_3/3/3")
		.init(prefix: "95", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "9[6-8]", length: ["9"], areaCodeLength: nil, operator: "viettel", format: "mobile_3/3/3")
		.init(prefix: "99[01]", length: ["9"], areaCodeLength: nil, operator: nil, format: "mobile_3/3/3")
		.init(prefix: "99[3-7]", length: ["9"], areaCodeLength: nil, operator: "g_mobile", format: "mobile_3/3/3")
		.init(prefix: "99[89]", length: ["9"], areaCodeLength: nil, operator: "indochina_telecom", format: "mobile_3/3/3")
	]
)

